/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.policyengine;

import org.apache.commons.lang3.StringUtils;
import org.apache.hadoop.fs.Path;
import org.apache.ranger.plugin.policyevaluator.RangerPolicyEvaluator;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerPluginPerfTester
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestRangerPluginPerfTester {
    private static void resetRangerPluginPerfTesterStatics() throws Exception {
        setStaticStringField("serviceType", null);
        setStaticStringField("serviceName", null);
        setStaticStringField("appId", null);
        setStaticStringField("rangerHostName", null);
        setStaticStringField("policyCacheDir", null);

        Field pollingInterval = RangerPluginPerfTester.class.getDeclaredField("pollingInterval");

        pollingInterval.setAccessible(true);
        pollingInterval.setInt(null, 30 * 1000);

        Field socketReadTimeout = RangerPluginPerfTester.class.getDeclaredField("socketReadTimeout");

        socketReadTimeout.setAccessible(true);
        socketReadTimeout.setInt(null, 30 * 1000);

        Field useCachedPolicyEvaluator =
                RangerPluginPerfTester.class.getDeclaredField("useCachedPolicyEvaluator");

        useCachedPolicyEvaluator.setAccessible(true);
        useCachedPolicyEvaluator.setBoolean(null, false);
    }

    private static void setStaticStringField(final String name, final String value)
            throws Exception {
        Field f = RangerPluginPerfTester.class.getDeclaredField(name);

        f.setAccessible(true);
        f.set(null, value);
    }

    @Test
    public void test01_parseArguments_negative_helpFlagReturnsFalse() throws Exception {
        resetRangerPluginPerfTesterStatics();

        assertFalse(parsePluginArgumentsMuted(new String[] {"-h"}));
    }

    @Test
    public void test02_parseArguments_positive_validArgsAllowBuildingConfigurationFile()
            throws Exception {
        resetRangerPluginPerfTesterStatics();

        String[] args = new String[] {
                "-s", "hive",
                "-n", "demoService",
                "-a", "demoApp",
                "-r", "localhost",
                "-p", "45000",
                "-t", "8000",
                "-c", System.getProperty("java.io.tmpdir"),
                "-e", "other",
        };

        assertTrue(parsePluginArgumentsMuted(args));

        Path written = RangerPluginPerfTester.buildConfigurationFile();

        assertNotNull(written);
        File configFile = new File(written.toString());
        assertTrue(configFile.exists());

        String xml =
                new String(Files.readAllBytes(configFile.toPath()), StandardCharsets.UTF_8);
        assertTrue(xml.contains(RangerPolicyEvaluator.EVALUATOR_TYPE_OPTIMIZED));
    }

    @Test
    public void test03_parseArguments_positive_cacheEvaluatorWritesCachedTypeInConfig()
            throws Exception {
        resetRangerPluginPerfTesterStatics();

        String[] args = new String[] {
                "-s", "hive",
                "-n", "demoService",
                "-a", "demoApp",
                "-r", "localhost",
                "-p", "45000",
                "-t", "8000",
                "-c", System.getProperty("java.io.tmpdir"),
                "-e", "cache",
        };

        assertTrue(parsePluginArgumentsMuted(args));

        Path written = RangerPluginPerfTester.buildConfigurationFile();

        assertNotNull(written);
        String xml =
                new String(
                        Files.readAllBytes(new File(written.toString()).toPath()),
                        StandardCharsets.UTF_8);
        assertTrue(xml.contains(RangerPolicyEvaluator.EVALUATOR_TYPE_CACHED));
    }

    @Test
    public void test04_parseArguments_negative_unrecognizedTokenReturnsFalse() throws Exception {
        resetRangerPluginPerfTesterStatics();

        assertFalse(
                parsePluginArgumentsMuted(new String[] {"--not-a-real-option"}));
    }

    @Test
    public void test05_showUsage_positive_runsWithoutThrowing() throws Exception {
        resetRangerPluginPerfTesterStatics();

        runMuted(() -> RangerPluginPerfTester.showUsage());
    }

    @Test
    public void test06_parseArguments_negative_missingOptionValueTriggersParseException()
            throws Exception {
        resetRangerPluginPerfTesterStatics();

        assertFalse(parsePluginArgumentsMuted(new String[] {"-s"}));
    }

    @Test
    public void test07_parseArguments_positive_caseInsensitiveCacheEvaluatorMatched()
            throws Exception {
        resetRangerPluginPerfTesterStatics();

        String[] args =
                new String[] {
                    "-s", "hive",
                    "-n", "demoService",
                    "-a", "demoApp",
                    "-r", "localhost",
                    "-p", "45000",
                    "-t", "8000",
                    "-c", System.getProperty("java.io.tmpdir"),
                    "-e", "cAcHe",
                };

        assertTrue(parsePluginArgumentsMuted(args));

        Path written = RangerPluginPerfTester.buildConfigurationFile();

        assertNotNull(written);
        String xml =
                new String(Files.readAllBytes(new File(written.toString()).toPath()), StandardCharsets.UTF_8);
        assertTrue(xml.contains(RangerPolicyEvaluator.EVALUATOR_TYPE_CACHED));
    }

    @Test
    public void test08_parseArguments_positive_nonNumericSocketAndPollingRetainDefaults()
            throws Exception {
        resetRangerPluginPerfTesterStatics();

        String[] args =
                new String[] {
                    "-s", "hive",
                    "-n", "demoService",
                    "-a", "demoApp",
                    "-r", "localhost",
                    "-p", "not-a-number",
                    "-t", "also-not-an-int",
                    "-c", System.getProperty("java.io.tmpdir"),
                    "-e", "other",
                };

        assertTrue(parsePluginArgumentsMuted(args));

        Path written = RangerPluginPerfTester.buildConfigurationFile();

        assertNotNull(written);
        String xml =
                new String(Files.readAllBytes(new File(written.toString()).toPath()), StandardCharsets.UTF_8);

        assertEquals(2, StringUtils.countMatches(xml, "30000"));
    }

    private static boolean parsePluginArgumentsMuted(final String[] args) throws Exception {
        final boolean[] parsed = new boolean[1];

        runMuted(
                () ->
                        parsed[0] = RangerPluginPerfTester.parseArguments(args));

        return parsed[0];
    }

    @FunctionalInterface
    private interface MutedExecutable {
        void execute() throws Exception;
    }

    private static void runMuted(MutedExecutable executable) throws Exception {
        PrintStream originalOut = System.out;
        PrintStream originalErr = System.err;

        ByteArrayOutputStream sink = new ByteArrayOutputStream();
        PrintStream         mute   = new PrintStream(sink);

        System.setOut(mute);
        System.setErr(mute);

        try {
            executable.execute();
        } finally {
            mute.flush();
            System.setOut(originalOut);
            System.setErr(originalErr);
            mute.close();
        }
    }
}
