/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.policyengine;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.Method;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static java.util.Objects.requireNonNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerPolicyenginePerfTester
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestRangerPolicyenginePerfTester {
    @Test
    public void test01_buildPerfModuleNames_positive_readsModuleTokensFromClasspathFile()
            throws Exception {
        Method method = RangerPolicyenginePerfTester.class.getDeclaredMethod(
                "buildPerfModuleNames", URL.class);
        method.setAccessible(true);

        URL url =
                requireNonNull(
                                TestRangerPolicyenginePerfTester.class.getResource(
                                        "/testdata/test_modules.txt"))
                        .toURI()
                        .toURL();

        @SuppressWarnings("unchecked")
        List<String> names = (List<String>) method.invoke(null, url);

        assertNotNull(names);
        assertTrue(names.size() > 0);
    }

    @Test
    public void test02_buildPerfModuleNames_positive_skipsCommentsAndBlankLines()
            throws Exception {
        Method method = RangerPolicyenginePerfTester.class.getDeclaredMethod(
                "buildPerfModuleNames", URL.class);
        method.setAccessible(true);

        Path tmp = Files.createTempFile("ranger-modules", ".txt");
        tmp.toFile().deleteOnExit();

        Files.write(tmp, "# ignored\n\n  foo  bar \n".getBytes(StandardCharsets.UTF_8));

        URL url = tmp.toUri().toURL();

        @SuppressWarnings("unchecked")
        List<String> names = (List<String>) method.invoke(null, url);

        assertTrue(names.contains("foo"));
        assertTrue(names.contains("bar"));
    }

    @Test
    public void test03_buildPerfModuleNames_negative_ioFailureReturnsReadableEmptyList()
            throws Exception {
        Method method = RangerPolicyenginePerfTester.class.getDeclaredMethod(
                "buildPerfModuleNames", URL.class);
        method.setAccessible(true);

        Path tmp = Files.createTempFile("ranger-modules-missing", ".txt");

        Files.write(tmp, "# sample\n".getBytes(StandardCharsets.UTF_8));

        URL url = tmp.toUri().toURL();

        Files.delete(tmp);

        @SuppressWarnings("unchecked")
        final Object[] namesHolder = new Object[1];

        runMuted(() -> namesHolder[0] = method.invoke(null, url));

        List<String> names = (List<String>) namesHolder[0];

        assertTrue(names.isEmpty());
    }

    @FunctionalInterface
    private interface MutedExecutable {
        void execute() throws Exception;
    }

    private static void runMuted(final MutedExecutable executable) throws Exception {
        PrintStream originalOut = System.out;
        PrintStream originalErr = System.err;

        ByteArrayOutputStream sink = new ByteArrayOutputStream();
        PrintStream         mute   = new PrintStream(sink);

        System.setOut(mute);
        System.setErr(mute);

        try {
            executable.execute();
        } finally {
            mute.flush();
            System.setOut(originalOut);
            System.setErr(originalErr);
            mute.close();
        }
    }
}
