/
CREATE SEQUENCE RANGER_MASTERKEY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE ranger_masterkey (
id NUMBER(20) NOT NULL,
create_time DATE DEFAULT NULL NULL,
update_time DATE DEFAULT NULL NULL,
added_by_id NUMBER(20) DEFAULT NULL NULL,
upd_by_id NUMBER(20) DEFAULT NULL NULL,
cipher VARCHAR(255) DEFAULT NULL NULL,
bitlength NUMBER(11) DEFAULT NULL NULL,
masterkey VARCHAR(2048) DEFAULT NULL NULL,
PRIMARY KEY (id)
);

CREATE SEQUENCE RANGER_KEYSTORE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE ranger_keystore(
id NUMBER(20) NOT NULL,
create_time DATE DEFAULT NULL NULL,
update_time DATE DEFAULT NULL NULL,
added_by_id NUMBER(20) DEFAULT NULL NULL,
upd_by_id NUMBER(20) DEFAULT NULL NULL,
kms_alias VARCHAR(255) NOT NULL,
kms_createdDate NUMBER(20) DEFAULT NULL NULL,
kms_cipher VARCHAR(255) DEFAULT NULL NULL,
kms_bitLength NUMBER(20) DEFAULT NULL NULL,
kms_description VARCHAR(512) DEFAULT NULL NULL,
kms_version NUMBER(20) DEFAULT NULL NULL,
kms_attributes VARCHAR(1024) DEFAULT NULL NULL,
kms_encoded VARCHAR(2048),
PRIMARY KEY (id)
);