/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.ranger.service;

import org.apache.hadoop.thirdparty.com.google.common.base.Joiner;
import org.apache.ranger.biz.RangerBizUtil;
import org.apache.ranger.biz.ServiceDBStore;
import org.apache.ranger.common.ContextUtil;
import org.apache.ranger.common.JSONUtil;
import org.apache.ranger.common.StringUtil;
import org.apache.ranger.common.UserSessionBase;
import org.apache.ranger.db.RangerDaoManager;
import org.apache.ranger.db.XXPortalUserDao;
import org.apache.ranger.db.XXServiceConfigDefDao;
import org.apache.ranger.db.XXServiceConfigMapDao;
import org.apache.ranger.db.XXServiceDao;
import org.apache.ranger.db.XXServiceDefDao;
import org.apache.ranger.db.XXServiceVersionInfoDao;
import org.apache.ranger.entity.XXPortalUser;
import org.apache.ranger.entity.XXService;
import org.apache.ranger.entity.XXServiceConfigMap;
import org.apache.ranger.entity.XXServiceDef;
import org.apache.ranger.entity.XXServiceVersionInfo;
import org.apache.ranger.plugin.model.RangerService;
import org.apache.ranger.plugin.util.PasswordUtils;
import org.apache.ranger.security.context.RangerContextHolder;
import org.apache.ranger.security.context.RangerSecurityContext;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerServiceService
 */

@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestRangerServiceService {
    private static final Long userId = 8L;
    @InjectMocks
    RangerServiceService    serviceService = new RangerServiceService();
    @Mock
    RangerDaoManager        daoManager;
    @Mock
    RangerBizUtil           bizUtil;
    @Mock
    RangerServiceService    svcService;
    @Mock
    JSONUtil                jsonUtil;
    @Mock
    RangerServiceDefService serviceDefService;
    @Mock
    RangerPolicyService     policyService;
    @Mock
    StringUtil              stringUtil;
    @Mock
    XUserService            xUserService;

    public void setup() {
        RangerSecurityContext context = new RangerSecurityContext();
        context.setUserSession(new UserSessionBase());
        RangerContextHolder.setSecurityContext(context);
        UserSessionBase currentUserSession = ContextUtil.getCurrentUserSession();
        currentUserSession.setUserAdmin(true);
    }

    @Test
    public void test1ValidateForCreate() {
        RangerService service = rangerService();
        serviceService.validateForCreate(service);
        Assertions.assertNotNull(service);
    }

    @Test
    public void test2ValidateForUpdate() {
        RangerService vService = rangerService();
        XXService     xService = xService();

        serviceService.validateForUpdate(vService, xService);
        Assertions.assertNotNull(vService);
    }

    @Test
    public void test3PopulateViewBean() {
        XXServiceConfigMapDao xServiceConfigMapDao = Mockito
                .mock(XXServiceConfigMapDao.class);
        XXPortalUserDao xPortalUserDao = Mockito.mock(XXPortalUserDao.class);
        XXServiceDefDao xServiceDefDao = Mockito.mock(XXServiceDefDao.class);
        XXService       xService       = xService();
        String          name           = "fdfdfds";
        XXServiceConfigDefDao xServiceConfigDefDao = Mockito.mock(XXServiceConfigDefDao.class);

        List<XXServiceConfigMap> svcConfigMapList = new ArrayList<>();
        XXServiceConfigMap       xConfMap         = new XXServiceConfigMap();
        xConfMap.setAddedByUserId(null);
        xConfMap.setConfigkey(name);
        xConfMap.setConfigvalue(name);
        xConfMap.setCreateTime(new Date());
        xConfMap.setServiceId(null);

        xConfMap.setUpdatedByUserId(null);
        xConfMap.setUpdateTime(new Date());
        svcConfigMapList.add(xConfMap);

        XXPortalUser tUser = new XXPortalUser();
        tUser.setAddedByUserId(userId);
        tUser.setCreateTime(new Date());
        tUser.setEmailAddress("test@gmail.com");
        tUser.setFirstName(name);
        tUser.setId(userId);
        tUser.setLastName(name);

        XXServiceDef xServiceDef = new XXServiceDef();
        xServiceDef.setAddedByUserId(userId);
        xServiceDef.setCreateTime(new Date());
        xServiceDef.setDescription("test");
        xServiceDef.setGuid("1427365526516_835_0");
        xServiceDef.setId(userId);

        XXServiceVersionInfoDao xServiceVersionInfoDao = Mockito.mock(XXServiceVersionInfoDao.class);

        XXServiceVersionInfo serviceVersionInfo = new XXServiceVersionInfo();
        serviceVersionInfo.setServiceId(xService.getId());
        serviceVersionInfo.setPolicyVersion(xService.getPolicyVersion());
        serviceVersionInfo.setPolicyUpdateTime(xService.getPolicyUpdateTime());
        serviceVersionInfo.setTagVersion(xService.getTagVersion());
        serviceVersionInfo.setTagUpdateTime(xService.getTagUpdateTime());

        Mockito.when(daoManager.getXXServiceVersionInfo()).thenReturn(xServiceVersionInfoDao);
        Mockito.when(xServiceVersionInfoDao.findByServiceId(xService.getId())).thenReturn(serviceVersionInfo);

        Mockito.when(daoManager.getXXPortalUser()).thenReturn(xPortalUserDao);
        Mockito.when(xPortalUserDao.getById(userId)).thenReturn(tUser);

        Mockito.when(daoManager.getXXServiceDef()).thenReturn(xServiceDefDao);
        Mockito.when(xServiceDefDao.getById(xService.getType())).thenReturn(xServiceDef);

        Mockito.when(daoManager.getXXServiceConfigMap()).thenReturn(xServiceConfigMapDao);
        Mockito.when(xServiceConfigMapDao.findByServiceId(xService.getId())).thenReturn(svcConfigMapList);

        Mockito.when(daoManager.getXXServiceConfigDef()).thenReturn(xServiceConfigDefDao);
        Mockito.when(xServiceConfigDefDao.findConfigNamesByServiceDefIdAndType(xService.getType(), ServiceDBStore.CONFIG_TYPE_PASSWORD)).thenReturn(new ArrayList<>());

        RangerService dbService = serviceService.populateViewBean(xService);

        Assertions.assertNotNull(dbService);
        Assertions.assertEquals(userId, dbService.getId());
        Assertions.assertEquals(xService.getAddedByUserId(), dbService.getId());
        Assertions.assertEquals(xService.getId(), dbService.getId());
        Assertions.assertEquals(xService.getDescription(), dbService.getDescription());
        Assertions.assertEquals(xService.getGuid(), dbService.getGuid());
        Assertions.assertEquals(xService.getName(), dbService.getName());
        Assertions.assertEquals(xService.getPolicyUpdateTime(), dbService.getPolicyUpdateTime());
        Assertions.assertEquals(xService.getPolicyVersion(), dbService.getPolicyVersion());
        Assertions.assertEquals(xService.getVersion(), dbService.getVersion());

        Mockito.verify(daoManager).getXXServiceDef();
        Mockito.verify(daoManager).getXXServiceConfigMap();
    }

    @Test
    public void test4GetPopulatedViewObject() {
        XXServiceConfigMapDao xServiceConfigMapDao = Mockito.mock(XXServiceConfigMapDao.class);
        XXPortalUserDao       xPortalUserDao       = Mockito.mock(XXPortalUserDao.class);
        XXServiceDefDao       xServiceDefDao       = Mockito.mock(XXServiceDefDao.class);
        XXServiceConfigDefDao xServiceConfigDefDao = Mockito.mock(XXServiceConfigDefDao.class);
        XXService             xService             = xService();
        String                name                 = "fdfdfds";

        List<XXServiceConfigMap> svcConfigMapList = new ArrayList<>();
        XXServiceConfigMap       xConfMap         = new XXServiceConfigMap();
        xConfMap.setAddedByUserId(null);
        xConfMap.setConfigkey(name);
        xConfMap.setConfigvalue(name);
        xConfMap.setCreateTime(new Date());
        xConfMap.setServiceId(null);
        xConfMap.setUpdatedByUserId(null);
        xConfMap.setUpdateTime(new Date());
        svcConfigMapList.add(xConfMap);

        XXPortalUser tUser = new XXPortalUser();
        tUser.setAddedByUserId(userId);
        tUser.setCreateTime(new Date());
        tUser.setEmailAddress("test@gmail.com");
        tUser.setFirstName(name);
        tUser.setId(userId);
        tUser.setLastName(name);

        XXServiceDef xServiceDef = new XXServiceDef();
        xServiceDef.setAddedByUserId(userId);
        xServiceDef.setCreateTime(new Date());
        xServiceDef.setDescription("test");
        xServiceDef.setGuid("1427365526516_835_0");
        xServiceDef.setId(userId);

        XXServiceVersionInfoDao xServiceVersionInfoDao = Mockito.mock(XXServiceVersionInfoDao.class);

        XXServiceVersionInfo serviceVersionInfo = new XXServiceVersionInfo();
        serviceVersionInfo.setServiceId(xService.getId());
        serviceVersionInfo.setPolicyVersion(xService.getPolicyVersion());
        serviceVersionInfo.setPolicyUpdateTime(xService.getPolicyUpdateTime());
        serviceVersionInfo.setTagVersion(xService.getTagVersion());
        serviceVersionInfo.setTagUpdateTime(xService.getTagUpdateTime());

        Mockito.when(daoManager.getXXServiceVersionInfo()).thenReturn(xServiceVersionInfoDao);
        Mockito.when(xServiceVersionInfoDao.findByServiceId(xService.getId())).thenReturn(serviceVersionInfo);

        Mockito.when(daoManager.getXXPortalUser()).thenReturn(xPortalUserDao);
        Mockito.when(xPortalUserDao.getById(userId)).thenReturn(tUser);

        Mockito.when(daoManager.getXXServiceDef()).thenReturn(xServiceDefDao);
        Mockito.when(xServiceDefDao.getById(xService.getType())).thenReturn(xServiceDef);

        Mockito.when(daoManager.getXXServiceConfigMap()).thenReturn(xServiceConfigMapDao);
        Mockito.when(xServiceConfigMapDao.findByServiceId(xService.getId())).thenReturn(svcConfigMapList);

        Mockito.when(daoManager.getXXServiceConfigDef()).thenReturn(xServiceConfigDefDao);
        Mockito.when(xServiceConfigDefDao.findConfigNamesByServiceDefIdAndType(xService.getType(), ServiceDBStore.CONFIG_TYPE_PASSWORD)).thenReturn(new ArrayList<>());

        RangerService dbService = serviceService.getPopulatedViewObject(xService);

        Assertions.assertNotNull(dbService);
        Assertions.assertEquals(userId, dbService.getId());
        Assertions.assertEquals(xService.getAddedByUserId(), dbService.getId());
        Assertions.assertEquals(xService.getId(), dbService.getId());
        Assertions.assertEquals(xService.getDescription(), dbService.getDescription());
        Assertions.assertEquals(xService.getGuid(), dbService.getGuid());
        Assertions.assertEquals(xService.getName(), dbService.getName());
        Assertions.assertEquals(xService.getPolicyUpdateTime(), dbService.getPolicyUpdateTime());
        Assertions.assertEquals(xService.getPolicyVersion(), dbService.getPolicyVersion());
        Assertions.assertEquals(xService.getVersion(), dbService.getVersion());

        Mockito.verify(daoManager).getXXServiceDef();
        Mockito.verify(daoManager).getXXServiceConfigMap();
    }

    @Test
    public void test4aPopulateViewBeanMasksAllServiceDefTypePasswordConfigs() {
        XXServiceConfigMapDao xServiceConfigMapDao = Mockito.mock(XXServiceConfigMapDao.class);
        XXPortalUserDao       xPortalUserDao       = Mockito.mock(XXPortalUserDao.class);
        XXServiceDefDao       xServiceDefDao       = Mockito.mock(XXServiceDefDao.class);
        XXServiceConfigDefDao xServiceConfigDefDao = Mockito.mock(XXServiceConfigDefDao.class);
        XXService             xService             = xService();

        final String keyGenericPassword    = "password";
        final String keyKeystorePassword   = "nifi.ssl.keystorePassword";
        final String keyTruststorePassword = "nifi.ssl.truststorePassword";
        final String keyUrl                = "nifi.url";

        List<XXServiceConfigMap> svcConfigMapList = new ArrayList<>();
        svcConfigMapList.add(configMap(keyGenericPassword, "s3cr3t-admin"));
        svcConfigMapList.add(configMap(keyKeystorePassword, "s3cr3t-keystore"));
        svcConfigMapList.add(configMap(keyTruststorePassword, "s3cr3t-truststore"));
        svcConfigMapList.add(configMap(keyUrl, "https://nifi.example.com:8443/nifi-api"));

        XXPortalUser tUser = new XXPortalUser();
        tUser.setAddedByUserId(userId);
        tUser.setCreateTime(new Date());
        tUser.setEmailAddress("test@gmail.com");
        tUser.setFirstName("nifi-prod");
        tUser.setId(userId);
        tUser.setLastName("nifi-prod");

        XXServiceDef xServiceDef = new XXServiceDef();
        xServiceDef.setAddedByUserId(userId);
        xServiceDef.setCreateTime(new Date());
        xServiceDef.setDescription("test");
        xServiceDef.setGuid("1427365526516_835_0");
        xServiceDef.setId(userId);

        XXServiceVersionInfoDao xServiceVersionInfoDao = Mockito.mock(XXServiceVersionInfoDao.class);
        XXServiceVersionInfo    serviceVersionInfo     = new XXServiceVersionInfo();
        serviceVersionInfo.setServiceId(xService.getId());
        serviceVersionInfo.setPolicyVersion(xService.getPolicyVersion());
        serviceVersionInfo.setPolicyUpdateTime(xService.getPolicyUpdateTime());
        serviceVersionInfo.setTagVersion(xService.getTagVersion());
        serviceVersionInfo.setTagUpdateTime(xService.getTagUpdateTime());

        Mockito.when(daoManager.getXXServiceVersionInfo()).thenReturn(xServiceVersionInfoDao);
        Mockito.when(xServiceVersionInfoDao.findByServiceId(xService.getId())).thenReturn(serviceVersionInfo);

        Mockito.when(daoManager.getXXPortalUser()).thenReturn(xPortalUserDao);
        Mockito.when(xPortalUserDao.getById(userId)).thenReturn(tUser);

        Mockito.when(daoManager.getXXServiceDef()).thenReturn(xServiceDefDao);
        Mockito.when(xServiceDefDao.getById(xService.getType())).thenReturn(xServiceDef);

        Mockito.when(daoManager.getXXServiceConfigMap()).thenReturn(xServiceConfigMapDao);
        Mockito.when(xServiceConfigMapDao.findByServiceId(xService.getId())).thenReturn(svcConfigMapList);

        /* the config item names the NiFi service-def declares with "type":"password" -
         * already filtered by type at the DB layer, so only those two names come back */
        List<String> nifiPasswordTypedNames = Arrays.asList(keyKeystorePassword, keyTruststorePassword);

        Mockito.when(daoManager.getXXServiceConfigDef()).thenReturn(xServiceConfigDefDao);
        Mockito.when(xServiceConfigDefDao.findConfigNamesByServiceDefIdAndType(xService.getType(), ServiceDBStore.CONFIG_TYPE_PASSWORD)).thenReturn(nifiPasswordTypedNames);

        RangerService        dbService = serviceService.getPopulatedViewObject(xService);
        Map<String, String>  configs   = dbService.getConfigs();

        Assertions.assertEquals("*****", configs.get(keyGenericPassword), "literal 'password' key must still be masked");
        Assertions.assertEquals("*****", configs.get(keyKeystorePassword), "type=password key nifi.ssl.keystorePassword must now be masked");
        Assertions.assertEquals("*****", configs.get(keyTruststorePassword), "type=password key nifi.ssl.truststorePassword must now be masked");
        Assertions.assertEquals("https://nifi.example.com:8443/nifi-api", configs.get(keyUrl), "non-secret config must be returned verbatim");
    }

    @Test
    public void test4bGetConfigsWithDecryptedPasswordResolvesMixedCaseKeys() throws Exception {
        final String  configKey  = "nifi.ssl.keystorePassword"; // mixed case, as NiFi's service-def declares it
        final String  plainValue = "s3cr3t-keystore";

        String iv                = PasswordUtils.generateIvIfNeeded(ServiceDBStore.CRYPT_ALGO);
        Joiner joiner            = Joiner.on(",").skipNulls();
        String cryptConfigString = joiner.join(ServiceDBStore.CRYPT_ALGO, ServiceDBStore.ENCRYPT_KEY, ServiceDBStore.SALT, ServiceDBStore.ITERATION_COUNT, iv, plainValue);
        String encryptedPwd      = PasswordUtils.encryptPassword(cryptConfigString);
        String storedValue       = joiner.join(ServiceDBStore.CRYPT_ALGO, ServiceDBStore.ENCRYPT_KEY, ServiceDBStore.SALT, ServiceDBStore.ITERATION_COUNT, iv, encryptedPwd);

        XXServiceConfigMapDao xServiceConfigMapDao = Mockito.mock(XXServiceConfigMapDao.class);
        XXServiceConfigDefDao xServiceConfigDefDao = Mockito.mock(XXServiceConfigDefDao.class);

        Map<String, String> configs = new HashMap<>();
        configs.put(configKey, ServiceDBStore.HIDDEN_PASSWORD_STR); // UI didn't change this field -> sentinel value

        RangerService service = new RangerService();
        service.setId(userId);
        service.setType("nifi");
        service.setConfigs(configs);

        XXServiceConfigMap storedConfigMap = new XXServiceConfigMap();
        storedConfigMap.setConfigkey(configKey);
        storedConfigMap.setConfigvalue(storedValue);

        Mockito.when(daoManager.getXXServiceConfigDef()).thenReturn(xServiceConfigDefDao);
        Mockito.when(xServiceConfigDefDao.findConfigNamesByServiceDefNameAndType("nifi", ServiceDBStore.CONFIG_TYPE_PASSWORD)).thenReturn(Collections.singletonList(configKey));
        Mockito.when(daoManager.getXXServiceConfigMap()).thenReturn(xServiceConfigMapDao);
        Mockito.when(xServiceConfigMapDao.findByServiceAndConfigKey(userId, configKey)).thenReturn(storedConfigMap);

        Mockito.when(stringUtil.isEmpty(Mockito.anyString())).thenReturn(false);

        Map<String, String> result = serviceService.getConfigsWithDecryptedPassword(service);

        Assertions.assertEquals(storedValue, result.get(configKey),
                "mixed-case password-typed key must be resolved via case-insensitive lookup, not silently skipped");
    }

    private XXServiceConfigMap configMap(String key, String value) {
        XXServiceConfigMap xConfMap = new XXServiceConfigMap();
        xConfMap.setConfigkey(key);
        xConfMap.setConfigvalue(value);
        xConfMap.setCreateTime(new Date());
        xConfMap.setUpdateTime(new Date());
        return xConfMap;
    }

    @Test
    public void test5GetAllServices() {
        XXServiceDao          xServiceDao          = Mockito.mock(XXServiceDao.class);
        XXPortalUserDao       xPortalUserDao       = Mockito.mock(XXPortalUserDao.class);
        XXServiceConfigMapDao xServiceConfigMapDao = Mockito.mock(XXServiceConfigMapDao.class);
        XXServiceDefDao       xServiceDefDao       = Mockito.mock(XXServiceDefDao.class);
        XXServiceConfigDefDao xServiceConfigDefDao = Mockito.mock(XXServiceConfigDefDao.class);

        String name = "fdfdfds";

        List<XXServiceConfigMap> svcConfigMapList = new ArrayList<>();
        XXServiceConfigMap       xConfMap         = new XXServiceConfigMap();
        xConfMap.setAddedByUserId(null);
        xConfMap.setConfigkey(name);
        xConfMap.setConfigvalue(name);
        xConfMap.setCreateTime(new Date());
        xConfMap.setServiceId(null);
        xConfMap.setUpdatedByUserId(null);
        xConfMap.setUpdateTime(new Date());
        svcConfigMapList.add(xConfMap);

        List<XXService> xServiceList = new ArrayList<>();
        XXService       xService     = xService();
        xServiceList.add(xService);

        XXPortalUser tUser = new XXPortalUser();
        tUser.setAddedByUserId(userId);
        tUser.setCreateTime(new Date());
        tUser.setEmailAddress("test@gmail.com");
        tUser.setFirstName(name);
        tUser.setId(userId);
        tUser.setLastName(name);

        XXServiceDef xServiceDef = new XXServiceDef();
        xServiceDef.setAddedByUserId(userId);
        xServiceDef.setCreateTime(new Date());
        xServiceDef.setDescription("test");
        xServiceDef.setGuid("1427365526516_835_0");
        xServiceDef.setId(userId);

        XXServiceVersionInfoDao xServiceVersionInfoDao = Mockito.mock(XXServiceVersionInfoDao.class);

        XXServiceVersionInfo serviceVersionInfo = new XXServiceVersionInfo();
        serviceVersionInfo.setServiceId(xService.getId());
        serviceVersionInfo.setPolicyVersion(xService.getPolicyVersion());
        serviceVersionInfo.setPolicyUpdateTime(xService.getPolicyUpdateTime());
        serviceVersionInfo.setTagVersion(xService.getTagVersion());
        serviceVersionInfo.setTagUpdateTime(xService.getTagUpdateTime());

        Mockito.when(daoManager.getXXServiceVersionInfo()).thenReturn(xServiceVersionInfoDao);
        Mockito.when(xServiceVersionInfoDao.findByServiceId(xService.getId())).thenReturn(serviceVersionInfo);

        Mockito.when(daoManager.getXXService()).thenReturn(xServiceDao);
        Mockito.when(xServiceDao.getAll()).thenReturn(xServiceList);

        Mockito.when(daoManager.getXXPortalUser()).thenReturn(xPortalUserDao);
        Mockito.when(xPortalUserDao.getById(userId)).thenReturn(tUser);

        Mockito.when(daoManager.getXXServiceDef()).thenReturn(xServiceDefDao);
        Mockito.when(xServiceDefDao.getById(xService.getType())).thenReturn(xServiceDef);

        Mockito.when(daoManager.getXXServiceConfigMap()).thenReturn(xServiceConfigMapDao);
        Mockito.when(xServiceConfigMapDao.findByServiceId(xService.getId())).thenReturn(svcConfigMapList);

        Mockito.when(daoManager.getXXServiceConfigDef()).thenReturn(xServiceConfigDefDao);
        Mockito.when(xServiceConfigDefDao.findConfigNamesByServiceDefIdAndType(xService.getType(), ServiceDBStore.CONFIG_TYPE_PASSWORD)).thenReturn(new ArrayList<>());

        List<RangerService> dbServiceList = serviceService.getAllServices();
        Assertions.assertNotNull(dbServiceList);

        Mockito.verify(daoManager).getXXServiceDef();
        Mockito.verify(daoManager).getXXServiceConfigMap();
    }

    @Test
    public void test6GetTransactionLogCreate() {
        RangerService rangerService = rangerService();

        serviceService.createTransactionLog(rangerService, null, 1);
    }

    @Test
    public void test7GetTransactionLogUpdate() {
        RangerService rangerService = rangerService();

        serviceService.createTransactionLog(rangerService, null, 2);
    }

    @Test
    public void test8GetTransactionLogDelete() {
        RangerService rangerService = rangerService();

        serviceService.createTransactionLog(rangerService, null, 3);
    }

    private RangerService rangerService() {
        Map<String, String> configs = new HashMap<String, String>();
        configs.put("username", "servicemgr");
        configs.put("password", "servicemgr");
        configs.put("namenode", "servicemgr");
        configs.put("hadoop.security.authorization", "No");
        configs.put("hadoop.security.authentication", "Simple");
        configs.put("hadoop.security.auth_to_local", "");
        configs.put("dfs.datanode.kerberos.principal", "");
        configs.put("dfs.namenode.kerberos.principal", "");
        configs.put("dfs.secondary.namenode.kerberos.principal", "");
        configs.put("hadoop.rpc.protection", "Privacy");
        configs.put("commonNameForCertificate", "");

        RangerService rangerService = new RangerService();
        rangerService.setId(userId);
        rangerService.setConfigs(configs);
        rangerService.setCreateTime(new Date());
        rangerService.setDescription("service");
        rangerService.setGuid("serviceguid");
        rangerService.setIsEnabled(true);
        rangerService.setName("Hdfs service");
        rangerService.setPolicyUpdateTime(new Date());
        rangerService.setPolicyVersion(1L);
        rangerService.setType(null);
        rangerService.setUpdatedBy("Admin");
        rangerService.setUpdateTime(new Date());
        rangerService.setVersion(userId);

        return rangerService;
    }

    private XXService xService() {
        XXService xService = new XXService();
        xService.setAddedByUserId(userId);
        xService.setCreateTime(new Date());
        xService.setDescription("Hdfs service");
        xService.setGuid("serviceguid");
        xService.setId(userId);
        xService.setIsEnabled(true);
        xService.setName("Hdfs");
        xService.setPolicyUpdateTime(new Date());
        xService.setPolicyVersion(1L);
        xService.setType(1L);
        xService.setUpdatedByUserId(userId);
        xService.setUpdateTime(new Date());

        return xService;
    }
}
