/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.tagsync.source.file;

import org.apache.ranger.tagsync.model.TagSink;
import org.apache.ranger.tagsync.process.TagSyncConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for FileTagSource
 */

@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestFileTagSource {
    @Mock
    private TagSink mockTagSink;
    private FileTagSource fileTagSource;
    private Properties properties;

    @TempDir
    Path tempDir;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        fileTagSource = new FileTagSource();
        properties = new Properties();
    }

    @AfterEach
    public void tearDown() {
        if (fileTagSource != null) {
            fileTagSource.stop();
        }
    }

    @Test
    public void test01InitializeWithValidFile() throws IOException {
        File tagFile = tempDir.resolve("tags.json").toFile();
        try (FileWriter writer = new FileWriter(tagFile)) {
            writer.write("{\"serviceTags\":{\"serviceName\":\"test\"}}");
        }

        properties.setProperty(TagSyncConfig.TAGSYNC_FILESOURCE_FILENAME_PROP, tagFile.getAbsolutePath());
        boolean result = fileTagSource.initialize(properties);
        assertTrue(result);
    }

    @Test
    public void test02InitializeWithNonExistentFileSucceeds() {
        properties.setProperty(TagSyncConfig.TAGSYNC_FILESOURCE_FILENAME_PROP, "/non/existent/file.json");
        boolean result = fileTagSource.initialize(properties);
        assertTrue(result);
    }

    @Test
    public void test03InitializeWithNullProperties() {
        boolean result = fileTagSource.initialize(null);
        assertFalse(result);
    }

    @Test
    public void test04SetTagSink() {
        fileTagSource.setTagSink(mockTagSink);
        assertNotNull(fileTagSource);
    }

    @Test
    public void test05StartReturnsTrue() throws IOException {
        File tagFile = tempDir.resolve("tags.json").toFile();
        try (FileWriter writer = new FileWriter(tagFile)) {
            writer.write("{\"serviceTags\":{\"serviceName\":\"test\"}}");
        }

        properties.setProperty(TagSyncConfig.TAGSYNC_FILESOURCE_FILENAME_PROP, tagFile.getAbsolutePath());
        fileTagSource.initialize(properties);

        boolean result = fileTagSource.start();
        assertTrue(result);
    }

    @Test
    public void test06StopDoesNotThrowException() {
        fileTagSource.stop();
        assertNotNull(fileTagSource);
    }

    @Test
    public void test07GetNameReturnsCorrectName() {
        String expectedName = "FileTagSource";
        fileTagSource.setName(expectedName);
        assertEquals(expectedName, fileTagSource.getName());
    }

    @Test
    public void test08InitializeWithCustomCheckInterval() throws IOException {
        File tagFile = tempDir.resolve("tags.json").toFile();
        try (FileWriter writer = new FileWriter(tagFile)) {
            writer.write("{\"serviceTags\":{\"serviceName\":\"test\"}}");
        }

        properties.setProperty(TagSyncConfig.TAGSYNC_FILESOURCE_FILENAME_PROP, tagFile.getAbsolutePath());
        properties.setProperty("ranger.tagsync.filesource.modtime.check.interval.millis", "30000");
        boolean result = fileTagSource.initialize(properties);
        assertTrue(result);
    }
}
