/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ranger.services.sqoop.client;

import org.apache.ranger.plugin.client.BaseClient;
import org.apache.ranger.plugin.client.HadoopException;
import org.apache.ranger.plugin.service.ResourceLookupContext;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.security.auth.Subject;

import java.lang.reflect.Constructor;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.CALLS_REAL_METHODS;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

/**
 * @generated by Cursor
 * @description : Unit Test cases for SqoopResourceMgr
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestSqoopResourceMgr {
    @Test
    void testGetSqoopResourcesNegativeReturnsNullWhenConfigsMissing() {
        ResourceLookupContext ctx = mock(ResourceLookupContext.class);

        List<String> discovered = SqoopResourceMgr.getSqoopResources("sqoop-svc", Collections.emptyMap(), ctx);

        assertNull(discovered);
    }

    @Test
    void testGetSqoopResourcesNegativeReturnsNullWhenResourceNameUnknown() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://localhost");
        configs.put("username", "u");
        ResourceLookupContext ctx = mock(ResourceLookupContext.class);
        when(ctx.getUserInput()).thenReturn("x");
        when(ctx.getResourceName()).thenReturn("unknown-kind");
        when(ctx.getResources()).thenReturn(Collections.emptyMap());

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.getSqoopClient(anyString(), any())).thenAnswer(invocation -> {
                String serviceName = invocation.getArgument(0);
                Map<String, String> cfg = invocation.getArgument(1);
                return new SqoopClient(serviceName, cfg) {
                    @Override
                    protected Subject getLoginSubject() {
                        return null;
                    }
                };
            });

            assertNull(SqoopResourceMgr.getSqoopResources("svc", configs, ctx));
        }
    }

    @Test
    void testGetSqoopResourcesNegativeReturnsNullWhenResourceNameBlank() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://localhost");
        configs.put("username", "u");
        ResourceLookupContext ctx = mock(ResourceLookupContext.class);
        when(ctx.getUserInput()).thenReturn("z");
        when(ctx.getResourceName()).thenReturn("");
        when(ctx.getResources()).thenReturn(Collections.emptyMap());

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.getSqoopClient(anyString(), any())).thenAnswer(invocation -> {
                String serviceName = invocation.getArgument(0);
                Map<String, String> cfg = invocation.getArgument(1);
                return new SqoopClient(serviceName, cfg) {
                    @Override
                    protected Subject getLoginSubject() {
                        return null;
                    }
                };
            });

            assertNull(SqoopResourceMgr.getSqoopResources("svc", configs, ctx));
        }
    }

    @Test
    void testGetSqoopResourcesNegativeReturnsNullWhenSqoopClientMissing() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://localhost");
        configs.put("username", "u");
        ResourceLookupContext ctx = mock(ResourceLookupContext.class);
        when(ctx.getUserInput()).thenReturn("pre");
        when(ctx.getResourceName()).thenReturn(SqoopResourceMgr.CONNECTOR);
        when(ctx.getResources()).thenReturn(Collections.singletonMap(SqoopResourceMgr.CONNECTOR, Collections.emptyList()));

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.getSqoopClient(anyString(), any())).thenReturn(null);

            assertNull(SqoopResourceMgr.getSqoopResources("svc", configs, ctx));
        }
    }

    @Test
    void testGetSqoopResourcesPositiveHandlesConnectorLookupWithoutFailure() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://127.0.0.1:1");
        configs.put("username", "integration-user");

        ResourceLookupContext ctx = mock(ResourceLookupContext.class);
        when(ctx.getUserInput()).thenReturn("*");
        when(ctx.getResourceName()).thenReturn(SqoopResourceMgr.CONNECTOR);
        when(ctx.getResources()).thenReturn(Collections.singletonMap(SqoopResourceMgr.CONNECTOR, Collections.emptyList()));

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.getSqoopClient(anyString(), any())).thenAnswer(invocation -> {
                String serviceName = invocation.getArgument(0);
                Map<String, String> cfg = invocation.getArgument(1);
                return new SqoopClient(serviceName, cfg) {
                    @Override
                    protected Subject getLoginSubject() {
                        return null;
                    }
                };
            });

            List<String> discovered = SqoopResourceMgr.getSqoopResources("sqoop-svc", configs, ctx);

            assertNotNull(discovered);
            assertTrue(discovered.isEmpty());
        }
    }

    @Test
    void testGetSqoopResourcesPositiveJobBranchDelegatesToClient() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://localhost");
        configs.put("username", "u");
        ResourceLookupContext ctx = mock(ResourceLookupContext.class);
        when(ctx.getUserInput()).thenReturn("");
        when(ctx.getResourceName()).thenReturn(SqoopResourceMgr.JOB);
        when(ctx.getResources()).thenReturn(Collections.singletonMap(SqoopResourceMgr.JOB, Collections.emptyList()));

        SqoopClient mockClient = mock(SqoopClient.class);
        when(mockClient.getJobList(any(), any())).thenReturn(Collections.singletonList("job-a"));

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.getSqoopClient(anyString(), any())).thenReturn(mockClient);

            List<String> out = SqoopResourceMgr.getSqoopResources("svc", configs, ctx);

            assertEquals(Collections.singletonList("job-a"), out);
        }
    }

    @Test
    void testGetSqoopResourcesPositiveLinkBranchDelegatesToClient() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://localhost");
        configs.put("username", "u");
        ResourceLookupContext ctx = mock(ResourceLookupContext.class);
        when(ctx.getUserInput()).thenReturn(null);
        when(ctx.getResourceName()).thenReturn(SqoopResourceMgr.LINK);
        when(ctx.getResources()).thenReturn(Collections.singletonMap(SqoopResourceMgr.LINK, Collections.emptyList()));

        SqoopClient mockClient = mock(SqoopClient.class);
        when(mockClient.getLinkList(any(), any())).thenReturn(Collections.singletonList("link-b"));

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.getSqoopClient(anyString(), any())).thenReturn(mockClient);

            List<String> out = SqoopResourceMgr.getSqoopResources("svc", configs, ctx);

            assertEquals(Collections.singletonList("link-b"), out);
        }
    }

    @Test
    void testPrivateConstructorInstantiableOnlyThroughReflection() throws Exception {
        Constructor<SqoopResourceMgr> ctor = SqoopResourceMgr.class.getDeclaredConstructor();
        ctor.setAccessible(true);
        SqoopResourceMgr instance = ctor.newInstance();
        assertNotNull(instance);
    }

    @Test
    void testValidateConfigNegativePropagatesWhenConnectionConfigsAbsent() {
        assertThrows(HadoopException.class, () -> SqoopResourceMgr.validateConfig("sqoop-svc", Collections.emptyMap()));
    }

    @Test
    void testValidateConfigNegativePropagatesUncheckedFailuresFromConnectionTest() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://localhost");
        configs.put("username", "u");

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.connectionTest(anyString(), any())).thenThrow(new IllegalStateException("boom"));

            assertThrows(IllegalStateException.class, () -> SqoopResourceMgr.validateConfig("svc", configs));
        }
    }

    @Test
    void testValidateConfigPositiveReturnsStructuredConnectivityPayload() {
        Map<String, String> configs = new HashMap<>();
        configs.put("sqoop.url", "http://127.0.0.1:1");
        configs.put("username", "integration-user");

        try (MockedStatic<SqoopClient> mocked = mockStatic(SqoopClient.class, CALLS_REAL_METHODS)) {
            mocked.when(() -> SqoopClient.connectionTest(anyString(), any())).thenAnswer(invocation -> {
                Map<String, Object> responseData = new HashMap<>();
                BaseClient.generateResponseDataMap(true, "ok", "ok", null, null, responseData);
                return responseData;
            });

            Map<String, Object> outcome = SqoopResourceMgr.validateConfig("sqoop-svc", configs);

            assertNotNull(outcome);
            assertTrue(Boolean.TRUE.equals(outcome.get("connectivityStatus")));
        }
    }
}
