/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.ugsyncutil.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * @generated by Cursor
 * @description : Unit Test cases for FileSyncSourceInfo
 */

@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestFileSyncSourceInfo {
    @Test
    public void test01_GettersSettersAndToString() {
        FileSyncSourceInfo info = new FileSyncSourceInfo();
        info.setFileName("users.json");
        info.setSyncTime("2025-09-17T10:00:00Z");
        info.setLastModified("2025-09-17T09:00:00Z");
        info.setTotalUsersSynced(10);
        info.setTotalGroupsSynced(5);
        info.setTotalUsersDeleted(2);
        info.setTotalGroupsDeleted(1);

        Assertions.assertEquals("users.json", info.getFileName());
        Assertions.assertEquals("2025-09-17T10:00:00Z", info.getSyncTime());
        Assertions.assertEquals("2025-09-17T09:00:00Z", info.getLastModified());
        Assertions.assertEquals(10, info.getTotalUsersSynced());
        Assertions.assertEquals(5, info.getTotalGroupsSynced());
        Assertions.assertEquals(2, info.getTotalUsersDeleted());
        Assertions.assertEquals(1, info.getTotalGroupsDeleted());

        String str = info.toString();
        Assertions.assertTrue(str.contains("FileSycnSourceInfo"));
        Assertions.assertTrue(str.contains("users.json"));
        Assertions.assertTrue(str.contains("2025-09-17T10:00:00Z"));
        Assertions.assertTrue(str.contains("2025-09-17T09:00:00Z"));
        Assertions.assertTrue(str.contains("10"));
        Assertions.assertTrue(str.contains("5"));
        Assertions.assertTrue(str.contains("2"));
        Assertions.assertTrue(str.contains("1"));

        StringBuilder sb = new StringBuilder();
        info.toString(sb);
        Assertions.assertEquals(str, sb.toString());
    }
}
