/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ranger.services.yarn;

import org.apache.ranger.authorization.yarn.authorizer.RangerYarnAuthorizer;
import org.apache.ranger.plugin.model.RangerPolicy;
import org.apache.ranger.plugin.model.RangerService;
import org.apache.ranger.plugin.model.RangerServiceDef;
import org.apache.ranger.plugin.model.RangerServiceDef.RangerAccessTypeDef;
import org.apache.ranger.plugin.model.RangerServiceDef.RangerResourceDef;
import org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher;
import org.apache.ranger.plugin.service.RangerBaseService;
import org.apache.ranger.plugin.service.ResourceLookupContext;
import org.apache.ranger.services.yarn.client.YarnResourceMgr;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mockStatic;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerServiceYarn
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestRangerServiceYarn {
    @Test
    void test01_validateConfig_whenConfigsNull_returnsEmptyMap() {
        RangerServiceYarn svc = new RangerServiceYarn();

        Map<String, Object> response = svc.validateConfig();

        assertTrue(response.isEmpty());
    }

    @Test
    void test02_validateConfig_delegatesToYarnResourceMgr() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("yarn.url", "http://rm:8088");
        cfg.put("username", "u");
        cfg.put("password", "p");
        Map<String, Object> expected = new HashMap<>();
        expected.put("connectivityStatus", Boolean.TRUE);

        try (MockedStatic<YarnResourceMgr> mocked = mockStatic(YarnResourceMgr.class)) {
            mocked.when(() -> YarnResourceMgr.validateConfig(eq("sn"), eq(cfg))).thenReturn(expected);

            RangerServiceYarn svc = new RangerServiceYarn();
            svc.setServiceName("sn");
            svc.setConfigs(cfg);

            assertSame(expected, svc.validateConfig());
        }
    }

    @Test
    void test03_lookupResource_whenContextNull_returnsEmpty() {
        assertTrue(new RangerServiceYarn().lookupResource(null).isEmpty());
    }

    @Test
    void test04_lookupResource_delegatesToYarnResourceMgr() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("yarn.url", "http://rm:8088");
        ResourceLookupContext ctx = new ResourceLookupContext();
        List<String> expected = Collections.singletonList("default");

        try (MockedStatic<YarnResourceMgr> mocked = mockStatic(YarnResourceMgr.class)) {
            mocked.when(() -> YarnResourceMgr.getYarnResources(eq("sn"), eq(cfg), eq(ctx))).thenReturn(expected);

            RangerServiceYarn svc = new RangerServiceYarn();
            svc.setServiceName("sn");
            svc.setConfigs(cfg);

            assertEquals(expected, svc.lookupResource(ctx));
        }
    }

    @Test
    void test05_getDefaultRangerPolicies_whenHierarchyDisabled_returnsEmptyList() throws Exception {
        RangerServiceDef def = new RangerServiceDef();
        def.setName("yarn");
        def.setResources(new ArrayList<>());
        Map<String, String> options = new HashMap<>();
        options.put("create.default.policy.per.hierarchy", "false");
        def.setOptions(options);

        RangerService rs = new RangerService();
        rs.setName("yarn-svc");
        rs.setConfigs(new HashMap<>());

        RangerServiceYarn svc = new RangerServiceYarn();
        svc.init(def, rs);

        List<RangerPolicy> policies = svc.getDefaultRangerPolicies();

        assertTrue(policies.isEmpty());
    }

    @Test
    void test06_init_setsServiceFieldsFromRangerService() {
        RangerServiceDef def = new RangerServiceDef();
        def.setName("yarn");
        RangerService rs = new RangerService();
        rs.setName("svc1");
        rs.setType("yarn");
        Map<String, String> cfg = new HashMap<>();
        cfg.put("yarn.url", "http://rm:8088");
        rs.setConfigs(cfg);

        RangerServiceYarn svc = new RangerServiceYarn();
        svc.init(def, rs);

        assertEquals("svc1", svc.getServiceName());
        assertEquals("yarn", svc.getServiceType());
        assertEquals(cfg, svc.getConfigs());
        assertSame(def, svc.getServiceDef());
    }

    @Test
    void test07_validateConfig_whenYarnResourceMgrThrows_propagates() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("yarn.url", "http://rm:8088");

        try (MockedStatic<YarnResourceMgr> mocked = mockStatic(YarnResourceMgr.class)) {
            mocked.when(() -> YarnResourceMgr.validateConfig(eq("sn"), eq(cfg)))
                    .thenThrow(new IllegalStateException("bad"));

            RangerServiceYarn svc = new RangerServiceYarn();
            svc.setServiceName("sn");
            svc.setConfigs(cfg);

            assertThrows(IllegalStateException.class, svc::validateConfig);
        }
    }

    @Test
    void test08_lookupResource_whenYarnResourceMgrThrows_propagates() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("yarn.url", "http://rm:8088");
        ResourceLookupContext ctx = new ResourceLookupContext();

        try (MockedStatic<YarnResourceMgr> mocked = mockStatic(YarnResourceMgr.class)) {
            mocked.when(() -> YarnResourceMgr.getYarnResources(eq("sn"), eq(cfg), eq(ctx)))
                    .thenThrow(new IllegalStateException("lookup"));

            RangerServiceYarn svc = new RangerServiceYarn();
            svc.setServiceName("sn");
            svc.setConfigs(cfg);

            assertThrows(IllegalStateException.class, () -> svc.lookupResource(ctx));
        }
    }

    @Test
    void test09_getDefaultRangerPolicies_withHierarchy_addsSubmitAppForLookupUser() throws Exception {
        RangerServiceDef def = new RangerServiceDef();
        def.setName("yarn");
        Map<String, String> options = new HashMap<>();
        options.put("create.default.policy.per.hierarchy", "true");
        def.setOptions(options);

        RangerAccessTypeDef accessType = new RangerAccessTypeDef();
        accessType.setName(RangerServiceYarn.ACCESS_TYPE_SUBMIT_APP);
        def.setAccessTypes(Collections.singletonList(accessType));

        RangerResourceDef queue = new RangerResourceDef();
        queue.setName(RangerYarnAuthorizer.KEY_RESOURCE_QUEUE);
        queue.setMandatory(true);
        queue.setMatcher(RangerDefaultResourceMatcher.class.getName());
        def.setResources(Collections.singletonList(queue));

        RangerService rs = new RangerService();
        rs.setName("yarn-defpol");
        rs.setConfigs(new HashMap<>());

        RangerServiceYarn svc = new RangerServiceYarn();
        Field lookUpField = RangerBaseService.class.getDeclaredField("lookUpUser");
        lookUpField.setAccessible(true);
        lookUpField.set(svc, "lookup-runner");
        svc.init(def, rs);

        List<RangerPolicy> policies = svc.getDefaultRangerPolicies();

        assertFalse(policies.isEmpty());
    }

    @Test
    void test10_getDefaultRangerPolicies_customPolicyWithoutAllInName_doesNotAugmentResources() throws Exception {
        RangerServiceDef def = new RangerServiceDef();
        def.setName("yarn");
        def.setResources(new ArrayList<>());
        Map<String, String> options = new HashMap<>();
        options.put("create.default.policy.per.hierarchy", "false");
        def.setOptions(options);

        RangerService rs = new RangerService();
        rs.setName("yarn-custom");
        Map<String, String> svcCfg = new HashMap<>();
        svcCfg.put("setup.additional.default.policies", "true");
        svcCfg.put("default-policy.1.name", "restricted-queues");
        svcCfg.put("default-policy.1.resource.queue", "root");
        rs.setConfigs(svcCfg);

        RangerServiceYarn svc = new RangerServiceYarn();
        svc.init(def, rs);

        List<RangerPolicy> policies = svc.getDefaultRangerPolicies();

        assertEquals(1, policies.size());
        assertFalse(policies.get(0).getName().contains("all"));
    }

    @Test
    void test11_getDefaultRangerPolicies_whenLookupUserBlank_skipsUserGrant() throws Exception {
        RangerServiceDef def = new RangerServiceDef();
        def.setName("yarn");
        Map<String, String> options = new HashMap<>();
        options.put("create.default.policy.per.hierarchy", "true");
        def.setOptions(options);

        RangerAccessTypeDef accessType = new RangerAccessTypeDef();
        accessType.setName(RangerServiceYarn.ACCESS_TYPE_SUBMIT_APP);
        def.setAccessTypes(Collections.singletonList(accessType));

        RangerResourceDef queue = new RangerResourceDef();
        queue.setName(RangerYarnAuthorizer.KEY_RESOURCE_QUEUE);
        queue.setMandatory(true);
        queue.setMatcher(RangerDefaultResourceMatcher.class.getName());
        def.setResources(Collections.singletonList(queue));

        RangerService rs = new RangerService();
        rs.setName("yarn-nolookup");
        rs.setConfigs(new HashMap<>());

        RangerServiceYarn svc = new RangerServiceYarn();
        Field lookUpField = RangerBaseService.class.getDeclaredField("lookUpUser");
        lookUpField.setAccessible(true);
        lookUpField.set(svc, "");
        svc.init(def, rs);

        assertFalse(svc.getDefaultRangerPolicies().isEmpty());
    }

    @Test
    void test12_getDefaultRangerPolicies_policyNameContainsAllButNoQueueResource_logsWarning() throws Exception {
        RangerServiceDef def = new RangerServiceDef();
        def.setName("yarn");
        def.setResources(new ArrayList<>());
        Map<String, String> options = new HashMap<>();
        options.put("create.default.policy.per.hierarchy", "false");
        def.setOptions(options);

        RangerService rs = new RangerService();
        rs.setName("yarn-warn-q");
        Map<String, String> svcCfg = new HashMap<>();
        svcCfg.put("setup.additional.default.policies", "true");
        svcCfg.put("default-policy.1.name", "custom-all-queues");
        svcCfg.put("default-policy.1.resource.cluster", "c1");
        rs.setConfigs(svcCfg);

        RangerServiceYarn svc = new RangerServiceYarn();
        svc.init(def, rs);

        assertFalse(svc.getDefaultRangerPolicies().isEmpty());
    }
}
