#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
ranger.authorizer.impl.class=org.apache.ranger.authz.remote.RangerRemoteAuthorizer
# localhost is not working for kerberos authn, so using ranger-pdp.rangernw which is the hostname of the ranger-pdp container in docker-compose
ranger.authz.remote.pdp.url=http://ranger-pdp.rangernw:6500
ranger.authz.remote.pdp.connect.timeout.ms=5000
ranger.authz.remote.pdp.read.timeout.ms=30000

ranger.authz.remote.authn.type=kerberos
ranger.authz.remote.authn.kerberos.principal=testuser1/ranger-pdp.rangernw@EXAMPLE.COM
ranger.authz.remote.authn.kerberos.keytab=/etc/keytabs/testuser1.keytab
# Optional JAAS overrides
ranger.authz.remote.authn.kerberos.jaas.context.name=RangerRemoteClientKerberos
ranger.authz.remote.authn.kerberos.jaas.login.module=com.sun.security.auth.module.Krb5LoginModule
ranger.authz.remote.authn.kerberos.jaas.store.key=true
ranger.authz.remote.authn.kerberos.jaas.is.initiator=true
ranger.authz.remote.authn.kerberos.jaas.do.not.prompt=true
ranger.authz.remote.authn.kerberos.jaas.use.ticket.cache=false
ranger.authz.remote.authn.kerberos.jaas.refresh.krb5.config=true
ranger.authz.remote.authn.kerberos.spnego.strip.port=true
ranger.authz.remote.authn.kerberos.spnego.use.canonical.hostname=true
