services:
  ranger-opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
    container_name: ranger-opensearch
    hostname: ranger-opensearch.rangernw
    volumes:
      - ./scripts/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-data:/usr/share/opensearch/data
      - opensearch-logs:/usr/share/opensearch/logs
    networks:
      - ranger
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      ranger-kdc:
        condition: service_started
      ranger:
        condition: service_started
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

volumes:
  opensearch-data:
  opensearch-logs:

networks:
  ranger:
    name: rangernw

