services:
  ranger-db:
    build:
      context: .
      dockerfile: Dockerfile.ranger-oracle
      args:
        - ORACLE_VERSION=${ORACLE_VERSION}
    image: ranger-oracle
    container_name: ranger-oracle
    hostname: ranger-db.example.com
    networks:
      - ranger
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 30

networks:
  ranger:
    name: rangernw
