# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG IMPALA_VERSION
FROM apache/impala:${IMPALA_VERSION}-impalad_coord_exec

USER root

RUN mkdir -p /var/lib/ranger/impala
RUN mkdir -p -m 755 /var/log/impala
RUN chown impala:impala /var/lib/ranger/impala
RUN chown impala:impala -R /var/log/impala

# Install impala-shell and its dependencies
RUN apt-get update
RUN apt-get install -y libkrb5-dev
RUN apt-get install -y python3-dev python3-pip python3
RUN apt-get install -y gcc g++
RUN apt-get install -y libsasl2-dev libssl-dev
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install impala-shell
USER impala

ENTRYPOINT ["/opt/impala/bin/daemon_entrypoint.sh", "/opt/impala/bin/impalad",\
     "-log_dir=/opt/impala/logs",\
     "-abort_on_config_error=false", "-state_store_host=impala-statestored",\
     "-catalog_service_host=impala-catalogd", "-mem_limit_includes_jvm=true",\
     "-use_local_catalog=true", "--rpc_use_loopback=true",\
     "-use_resolved_hostname=true",\
     "--ranger_service_type=hive",\
     "--ranger_app_id=impala",\
     "--authorization_provider=ranger",\
     ""]
