# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG RANGER_BASE_IMAGE=apache/ranger-base
ARG RANGER_BASE_VERSION=20260123-2-8
FROM ${RANGER_BASE_IMAGE}:${RANGER_BASE_VERSION}

ARG ELASTICSEARCH_VERSION
ARG ELASTICSEARCH_PLUGIN_VERSION

COPY ./dist/ranger-${ELASTICSEARCH_PLUGIN_VERSION}-elasticsearch-plugin.tar.gz /home/ranger/dist/
COPY ./downloads/elasticsearch-${ELASTICSEARCH_VERSION}-linux-x86_64.tar.gz   /home/ranger/dist/
COPY ./scripts/elasticsearch/*.sh                                             ${RANGER_SCRIPTS}/
COPY ./scripts/elasticsearch/patch-ranger-security-xml.py                     ${RANGER_SCRIPTS}/
COPY ./scripts/elasticsearch/patch-ranger-audit-xml.py                        ${RANGER_SCRIPTS}/
COPY ./downloads/jaxb-api-2.2.11.jar                                          ${RANGER_SCRIPTS}/elasticsearch-lib/
COPY ./downloads/jaxb-runtime-2.3.2.jar                                       ${RANGER_SCRIPTS}/elasticsearch-lib/
COPY ./downloads/javax.activation-api-1.2.0.jar                               ${RANGER_SCRIPTS}/elasticsearch-lib/

RUN groupadd -r elasticsearch 2>/dev/null || true && \
    useradd -r -g hadoop -d /opt/elasticsearch -s /bin/bash elasticsearch 2>/dev/null || true && \
    tar xvfz /home/ranger/dist/elasticsearch-${ELASTICSEARCH_VERSION}-linux-x86_64.tar.gz --directory=/opt/ && \
    ln -s /opt/elasticsearch-${ELASTICSEARCH_VERSION} /opt/elasticsearch && \
    rm -f /home/ranger/dist/elasticsearch-${ELASTICSEARCH_VERSION}-linux-x86_64.tar.gz && \
    mkdir -p /opt/elasticsearch/data /opt/elasticsearch/logs && \
    tar xvfz /home/ranger/dist/ranger-${ELASTICSEARCH_PLUGIN_VERSION}-elasticsearch-plugin.tar.gz --directory=/opt/ranger && \
    ln -s /opt/ranger/ranger-${ELASTICSEARCH_PLUGIN_VERSION}-elasticsearch-plugin /opt/ranger/ranger-elasticsearch-plugin && \
    rm -f /home/ranger/dist/ranger-${ELASTICSEARCH_PLUGIN_VERSION}-elasticsearch-plugin.tar.gz && \
    rm -f /opt/ranger/ranger-elasticsearch-plugin/install.properties && \
    chown -R elasticsearch:hadoop /opt/elasticsearch* && \
    chmod 744 ${RANGER_SCRIPTS}/ranger-elasticsearch-setup.sh \
              ${RANGER_SCRIPTS}/ranger-elasticsearch-post-setup.sh \
              ${RANGER_SCRIPTS}/ranger-elasticsearch.sh

ENV ELASTICSEARCH_HOME=/opt/elasticsearch
ENV PATH=/usr/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/elasticsearch/bin

ENTRYPOINT [ "/home/ranger/scripts/ranger-elasticsearch.sh" ]
