# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG RANGER_BASE_IMAGE=apache/ranger-base
ARG RANGER_BASE_VERSION=20260123-2-17

# extract admin distribution in a separate stage, so that the tarball does not become a layer of the final image;
# identical files (jars repeated in ews/lib, WEB-INF/lib, cred/lib and plugin dirs) are replaced with hardlinks
FROM ${RANGER_BASE_IMAGE}:${RANGER_BASE_VERSION} AS ranger-admin-dist

ARG RANGER_VERSION

COPY ./dist/ranger-${RANGER_VERSION}-admin.tar.gz /tmp/

RUN    tar xfz /tmp/ranger-${RANGER_VERSION}-admin.tar.gz --directory=/tmp \
    && rm -f /tmp/ranger-${RANGER_VERSION}-admin/install.properties \
    && mkdir -p /tmp/ranger-${RANGER_VERSION}-admin/configs \
    && ln -s ews/webapp/WEB-INF/classes/conf /tmp/ranger-${RANGER_VERSION}-admin/conf \
    && hardlink -c /tmp/ranger-${RANGER_VERSION}-admin

FROM ${RANGER_BASE_IMAGE}:${RANGER_BASE_VERSION}

ARG RANGER_VERSION

RUN pip install --no-cache-dir pyyaml

COPY --from=ranger-admin-dist --chown=ranger:ranger /tmp/ranger-${RANGER_VERSION}-admin ${RANGER_HOME}/ranger-${RANGER_VERSION}-admin
COPY ./downloads/postgresql-42.2.16.jre7.jar          /usr/share/java/postgresql.jar
COPY ./downloads/mysql-connector-java-8.0.28.jar      /usr/share/java/mysql-connector.jar
COPY ./downloads/ojdbc8.jar                           /usr/share/java/oracle.jar
COPY --chown=ranger:ranger ./scripts/admin/ranger.sh                 ${RANGER_SCRIPTS}/
COPY --chown=ranger:ranger ./scripts/admin/dba.py                    ${RANGER_SCRIPTS}/
COPY --chown=ranger:ranger ./scripts/admin/create-ranger-services.py ${RANGER_SCRIPTS}/

RUN    ln -s ${RANGER_HOME}/ranger-${RANGER_VERSION}-admin ${RANGER_HOME}/admin \
    && mkdir -p /etc/ranger/admin /var/run/ranger /var/log/ranger \
    && chown ranger:ranger /etc/ranger/admin /var/run/ranger /var/log/ranger \
    && chmod 755 ${RANGER_SCRIPTS}/ranger.sh

ENV RANGER_VERSION=${RANGER_VERSION}
ENV RANGER_CONF_DIR=${RANGER_HOME}/admin/ews/webapp/WEB-INF/classes/conf
ENV RANGER_ADMIN_LOG_DIR=/var/log/ranger
ENV RANGER_PID_DIR_PATH=/var/run/ranger

USER ranger

ENTRYPOINT [ "/home/ranger/scripts/ranger.sh" ]
