# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG SOLR_VERSION
FROM solr:${SOLR_VERSION}

VOLUME /etc/keytabs

# Copy audit config set
USER 0

RUN apt update && DEBIAN_FRONTEND="noninteractive" apt-get install -y krb5-user

RUN mkdir -p /opt/solr/server/solr/configsets/ranger_audits/conf /home/ranger/scripts

COPY ./scripts/solr/solr-ranger_audits/* /opt/solr/server/solr/configsets/ranger_audits/conf/
COPY ./scripts/solr/solr-jaas.conf       /opt/solr/server/etc/jaas.conf
COPY ./scripts/solr/solr-security.json   /var/solr/data/security.json
COPY ./scripts/solr/ranger-solr.sh       /home/ranger/scripts/
COPY ./scripts/wait_for_keytab.sh        /home/ranger/scripts/
COPY ./scripts/wait_for_testusers_keytab.sh   /home/ranger/scripts/
COPY ./scripts/kdc/krb5.conf             /etc/krb5.conf

RUN chown -R solr:solr /opt/solr/server/solr/configsets/ranger_audits/
RUN chmod +x /home/ranger/scripts/ranger-solr.sh /home/ranger/scripts/wait_for_keytab.sh /home/ranger/scripts/wait_for_testusers_keytab.sh

ENTRYPOINT [ "/home/ranger/scripts/ranger-solr.sh" ]
CMD ["solr-foreground"]
