# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Only the ARGs needed for this build stage

ARG RANGER_BASE_IMAGE
ARG RANGER_BASE_VERSION
FROM ${RANGER_BASE_IMAGE}:${RANGER_BASE_VERSION}

ARG HIVE_VERSION
ARG HIVE_HADOOP_VERSION
ARG HIVE_PLUGIN_VERSION
ARG TEZ_VERSION
ARG RANGER_DB_TYPE


COPY ./dist/version                                          /home/ranger/dist/
COPY ./dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz /home/ranger/dist/
COPY ./downloads/apache-hive-${HIVE_VERSION}-bin.tar.gz      /home/ranger/dist/
COPY ./downloads/hadoop-${HIVE_HADOOP_VERSION}.tar.gz        /home/ranger/dist/
COPY ./downloads/apache-tez-${TEZ_VERSION}-bin.tar.gz        /home/ranger/dist/
COPY ./downloads/postgresql-42.2.16.jre7.jar                 /home/ranger/dist/
COPY ./downloads/mysql-connector-java-8.0.28.jar             /home/ranger/dist/
COPY ./downloads/ojdbc8.jar                                  /home/ranger/dist/

COPY ./scripts/hive/ranger-hive-setup.sh                  ${RANGER_SCRIPTS}/
COPY ./scripts/hive/ranger-hive.sh                        ${RANGER_SCRIPTS}/
COPY ./scripts/hive/ranger-hive-plugin-install.properties ${RANGER_SCRIPTS}/
COPY ./scripts/hive/hive-site-${RANGER_DB_TYPE}.xml       ${RANGER_SCRIPTS}/hive-site.xml
COPY ./scripts/hadoop/core-site.xml                       ${RANGER_SCRIPTS}/
COPY ./scripts/kdc/create_principal_and_keytab.sh         ${RANGER_SCRIPTS}/
COPY ./scripts/kdc/krb5.conf                              /etc/krb5.conf

RUN cd /opt && tar xzf /home/ranger/dist/apache-hive-${HIVE_VERSION}-bin.tar.gz && \
    ln -s /opt/apache-hive-${HIVE_VERSION}-bin /opt/hive && \
    rm -f /home/ranger/dist/apache-hive-${HIVE_VERSION}-bin.tar.gz && \
    mv /home/ranger/dist/postgresql-42.2.16.jre7.jar /opt/hive/lib/ && \
    mv /home/ranger/dist/mysql-connector-java-8.0.28.jar /opt/hive/lib/ && \
    mv /home/ranger/dist/ojdbc8.jar /opt/hive/lib/ && \
    tar xvfz /home/ranger/dist/hadoop-${HIVE_HADOOP_VERSION}.tar.gz --directory=/opt/ && \
    ln -s /opt/hadoop-${HIVE_HADOOP_VERSION} /opt/hadoop && \
    rm -f /home/ranger/dist/hadoop-${HIVE_HADOOP_VERSION}.tar.gz && \
    tar xvfz /home/ranger/dist/apache-tez-${TEZ_VERSION}-bin.tar.gz --directory=/opt/ && \
    ln -s /opt/apache-tez-${TEZ_VERSION}-bin /opt/tez && \
    rm -f /home/ranger/dist/apache-tez-${TEZ_VERSION}-bin.tar.gz && \
    tar xvfz /home/ranger/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz --directory=/opt/ranger && \
    ln -s /opt/ranger/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin /opt/ranger/ranger-hive-plugin && \
    rm -f /home/ranger/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz && \
    cp -f ${RANGER_SCRIPTS}/ranger-hive-plugin-install.properties /opt/ranger/ranger-hive-plugin/install.properties && \
    chmod 755 ${RANGER_SCRIPTS}/create_principal_and_keytab.sh && \
    chmod 744 ${RANGER_SCRIPTS}/ranger-hive-setup.sh ${RANGER_SCRIPTS}/ranger-hive.sh

ENV HIVE_HOME=/opt/hive
ENV HADOOP_HOME=/opt/hadoop
ENV TEZ_HOME=/opt/tez
ENV TEZ_CONF_DIR=/opt/tez/conf
ENV PATH=/usr/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hive/bin:/opt/hadoop/bin:/opt/tez/bin

ENTRYPOINT [ "/home/ranger/scripts/ranger-hive.sh" ]
