version: '3'
services:
  ranger-db:
    build:
      context: .
      dockerfile: Dockerfile.ranger-mysql
    image: ranger-mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: ranger-mysql
    hostname: ranger-db.example.com
    networks:
      - ranger
    healthcheck:
      # Double dollar($$) is required to expand the env variable
      test: "mysql -u root -p$$MYSQL_ROOT_PASSWORD ranger -e 'select 1' > /dev/null"
      interval: 10s
      timeout: 2s
      retries: 30

networks:
  ranger:
    name: rangernw
