# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG SQLSERVER_VERSION

#FROM mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION}

FROM mcr.microsoft.com/azure-sql-edge:latest

USER 0

RUN ACCEPT_EULA=Y apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        apt-transport-https \
        gnupg \
        unixodbc-dev

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-tools.list

RUN ACCEPT_EULA=Y apt-get update && \
    ACCEPT_EULA=Y apt-get install -y --no-install-recommends mssql-tools unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN  mkdir -p /docker-entrypoint-initdb.d
COPY config/init_mssql.sh /docker-entrypoint-initdb.d/
RUN chown -R mssql /docker-entrypoint-initdb.d/
ENV MSSQL_PASSWORD=rangerR0cks!
USER mssql
