# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG RANGER_BASE_IMAGE
ARG RANGER_BASE_VERSION
FROM ${RANGER_BASE_IMAGE}:${RANGER_BASE_VERSION}

ARG HBASE_VERSION
ARG HBASE_PLUGIN_VERSION


COPY ./dist/version                                             /home/ranger/dist/
COPY ./dist/ranger-${HBASE_PLUGIN_VERSION}-hbase-plugin.tar.gz  /home/ranger/dist/
COPY ./downloads/hbase-${HBASE_VERSION}-bin.tar.gz              /home/ranger/dist/

COPY ./scripts/hbase/ranger-hbase-setup.sh                  ${RANGER_SCRIPTS}/
COPY ./scripts/hbase/ranger-hbase.sh                        ${RANGER_SCRIPTS}/
COPY ./scripts/hbase/ranger-hbase-plugin-install.properties ${RANGER_SCRIPTS}/
COPY ./scripts/hbase/hbase-site.xml                         ${RANGER_SCRIPTS}/
COPY ./scripts/hadoop/core-site.xml                         ${RANGER_SCRIPTS}/
COPY ./scripts/kdc/create_principal_and_keytab.sh           ${RANGER_SCRIPTS}/
COPY ./scripts/kdc/krb5.conf                                /etc/krb5.conf

RUN tar xvfz /home/ranger/dist/hbase-${HBASE_VERSION}-bin.tar.gz --directory=/opt/ && \
    ln -s /opt/hbase-${HBASE_VERSION} /opt/hbase && \
    rm -f /home/ranger/dist/hbase-${HBASE_VERSION}-bin.tar.gz && \
    tar xvfz /home/ranger/dist/ranger-${HBASE_PLUGIN_VERSION}-hbase-plugin.tar.gz --directory=/opt/ranger && \
    ln -s /opt/ranger/ranger-${HBASE_PLUGIN_VERSION}-hbase-plugin /opt/ranger/ranger-hbase-plugin && \
    rm -f /home/ranger/dist/ranger-${HBASE_PLUGIN_VERSION}-hbase-plugin.tar.gz && \
    cp -f ${RANGER_SCRIPTS}/ranger-hbase-plugin-install.properties /opt/ranger/ranger-hbase-plugin/install.properties && \
    chmod 755 ${RANGER_SCRIPTS}/create_principal_and_keytab.sh && \
    chmod 744 ${RANGER_SCRIPTS}/ranger-hbase-setup.sh ${RANGER_SCRIPTS}/ranger-hbase.sh

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-server && \
    mkdir -p /var/run/sshd && \
    rm -rf /var/lib/apt/lists/*

ENV HBASE_HOME=/opt/hbase
ENV PATH=/usr/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/hbase/bin

ENTRYPOINT [ "/home/ranger/scripts/ranger-hbase.sh" ]
