# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG SQLSERVER_VERSION

FROM mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION}

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=rangerR0cks!

EXPOSE 1433

USER root

RUN  mkdir -p /docker-entrypoint-initdb.d
COPY config/init_mssql.sh /docker-entrypoint-initdb.d/
RUN  chown -R mssql /docker-entrypoint-initdb.d/
RUN  chmod +x /docker-entrypoint-initdb.d/init_mssql.sh

USER mssql

ENTRYPOINT ["/docker-entrypoint-initdb.d/init_mssql.sh"]
