/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.plugin.service;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
* @generated by Cursor
* @description <Unit Test for RangerDefaultService class>
*/
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestRangerDefaultService {
    @Test
    public void test1_validateConfigThrows() {
        RangerDefaultService svc = new RangerDefaultService();
        Exception ex = assertThrows(Exception.class, svc::validateConfig);
        assertEquals(RangerDefaultService.ERROR_MSG_VALIDATE_CONFIG_NOT_IMPLEMENTED, ex.getMessage());
    }

    @Test
    public void test2_lookupResourceReturnsEmptyList() throws Exception {
        RangerDefaultService svc = new RangerDefaultService();
        List<String> res = svc.lookupResource(new ResourceLookupContext());
        assertEquals(0, res.size());
    }
}
