/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.ranger.rest;

import org.apache.ranger.biz.AssetMgr;
import org.apache.ranger.biz.GdsDBStore;
import org.apache.ranger.biz.RangerBizUtil;
import org.apache.ranger.biz.ServiceDBStore;
import org.apache.ranger.common.RESTErrorUtil;
import org.apache.ranger.common.RangerSearchUtil;
import org.apache.ranger.common.ServiceUtil;
import org.apache.ranger.plugin.model.RangerGds;
import org.apache.ranger.plugin.model.RangerGrant;
import org.apache.ranger.plugin.model.RangerPolicy;
import org.apache.ranger.plugin.model.RangerPolicyHeader;
import org.apache.ranger.plugin.model.RangerPrincipal;
import org.apache.ranger.plugin.model.RangerValiditySchedule;
import org.apache.ranger.plugin.store.PList;
import org.apache.ranger.plugin.util.SearchFilter;
import org.apache.ranger.plugin.util.ServiceGdsInfo;
import org.apache.ranger.service.RangerGdsDataShareInDatasetService;
import org.apache.ranger.service.RangerGdsDataShareService;
import org.apache.ranger.service.RangerGdsDatasetInProjectService;
import org.apache.ranger.service.RangerGdsDatasetService;
import org.apache.ranger.service.RangerGdsProjectService;
import org.apache.ranger.service.RangerGdsSharedResourceService;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.WebApplicationException;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

import static org.apache.ranger.plugin.store.EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_HIVE_NAME;
import static org.apache.ranger.plugin.store.EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_TAG_NAME;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
* @generated by Cursor
* @description <Unit Test for TestGdsREST class>
*/
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestGdsREST {
    public static final String             SERVICE_PREFIX = "cm_";
    public static final String             SERVICE_DEF_HIVE = EMBEDDED_SERVICEDEF_HIVE_NAME;
    public static final String             SERVICE_DEF_TAG = EMBEDDED_SERVICEDEF_TAG_NAME;
    public static final String             SERVICE_HIVE   = SERVICE_PREFIX + SERVICE_DEF_HIVE;
    private final       HttpServletRequest request        = Mockito.mock(HttpServletRequest.class);
    private final       Random             random         = new Random();
    @InjectMocks
    private GdsREST gdsREST;
    @InjectMocks
    GdsDBStore       gdsDBStore;
    @Mock
    ServiceREST      serviceREST;
    @Mock
    GdsDBStore       gdsStore;
    @Mock
    RESTErrorUtil    restErrorUtil;
    @Mock
    RangerSearchUtil searchUtil;
    @Mock
    RangerBizUtil bizUtil;
    @Mock
    ServiceUtil serviceUtil;
    @Mock
    ServiceDBStore serviceDBStore;
    @Mock
    AssetMgr assetMgr;
    @Mock
    RangerGdsDatasetService datasetService;
    @Mock
    RangerGdsProjectService projectService;
    @Mock
    RangerGdsDataShareService dataShareService;
    @Mock
    RangerGdsSharedResourceService sharedResourceService;
    @Mock
    RangerGdsDataShareInDatasetService dshidService;
    @Mock
    RangerGdsDatasetInProjectService dipService;

    @Test
    public void testCreateDataset() {
        RangerGds.RangerDataset dataset = createRangerDataSet();
        RangerGds.RangerDataset expected = createRangerDataSet();
        expected.setId(1L);

        when(gdsStore.createDataset(dataset)).thenReturn(expected);

        RangerGds.RangerDataset result = gdsREST.createDataset(dataset);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).createDataset(dataset);
    }

    @Test
    public void testCreateDatasetException() {
        RangerGds.RangerDataset dataset = createRangerDataSet();

        when(gdsStore.createDataset(dataset)).thenThrow(new RuntimeException("Database error"));
        when(restErrorUtil.createRESTException(anyString())).thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.createDataset(dataset));
    }

    @Test
    public void testAddDataSharesInDataset() throws Exception {
        Long datasetId = 1L;
        List<RangerGds.RangerDataShareInDataset> dataSharesInDataset = Arrays.asList(createDataShareInDataset(datasetId));
        List<RangerGds.RangerDataShareInDataset> expected = Arrays.asList(createDataShareInDataset(datasetId));

        when(gdsStore.addDataSharesInDataset(dataSharesInDataset)).thenReturn(expected);

        List<RangerGds.RangerDataShareInDataset> result = gdsREST.addDataSharesInDataset(datasetId, dataSharesInDataset);

        assertNotNull(result);
        assertEquals(expected.size(), result.size());
        verify(gdsStore).addDataSharesInDataset(dataSharesInDataset);
    }

    @Test
    public void testAddDataSharesInDatasetInvalidDatasetId() {
        Long datasetId = 1L;
        RangerGds.RangerDataShareInDataset invalidDataShare = createDataShareInDataset(2L);
        List<RangerGds.RangerDataShareInDataset> dataSharesInDataset = Arrays.asList(invalidDataShare);

        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_BAD_REQUEST), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class,
                () -> gdsREST.addDataSharesInDataset(datasetId, dataSharesInDataset));
    }

    @Test
    public void testUpdateDataset() throws Exception {
        Long datasetId = 1L;
        RangerGds.RangerDataset dataset = createRangerDataSet();
        RangerGds.RangerDataset expected = createRangerDataSet();
        expected.setId(datasetId);

        when(gdsStore.updateDataset(any(RangerGds.RangerDataset.class))).thenReturn(expected);

        RangerGds.RangerDataset result = gdsREST.updateDataset(datasetId, dataset);

        assertNotNull(result);
        assertEquals(datasetId, result.getId());
        verify(gdsStore).updateDataset(any(RangerGds.RangerDataset.class));
    }

    @Test
    public void testDeleteDataset() throws Exception {
        Long datasetId = 1L;

        doNothing().when(gdsStore).deleteDataset(datasetId, false);

        gdsREST.deleteDataset(datasetId, request);

        verify(gdsStore).deleteDataset(datasetId, false);
    }

    @Test
    public void testDeleteDatasetForceDelete() throws Exception {
        Long datasetId = 1L;

        when(request.getParameter("forceDelete")).thenReturn("true");
        doNothing().when(gdsStore).deleteDataset(datasetId, true);

        gdsREST.deleteDataset(datasetId, request);

        verify(gdsStore).deleteDataset(datasetId, true);
    }

    @Test
    public void testGetDataset() throws Exception {
        Long datasetId = 1L;
        RangerGds.RangerDataset expected = createRangerDataSet();
        expected.setId(datasetId);

        when(gdsStore.getDataset(datasetId)).thenReturn(expected);

        RangerGds.RangerDataset result = gdsREST.getDataset(datasetId);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getDataset(datasetId);
    }

    @Test
    public void testGetDatasetNotFound() throws Exception {
        Long datasetId = 1L;

        when(gdsStore.getDataset(datasetId)).thenReturn(null);
        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_NOT_FOUND), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.getDataset(datasetId));
    }

    @Test
    public void testSearchDatasets() {
        PList<RangerGds.RangerDataset> expected = new PList<>();
        expected.setList(Arrays.asList(createRangerDataSet()));
        SearchFilter filter = new SearchFilter();

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.searchDatasets(filter)).thenReturn(expected);

        PList<RangerGds.RangerDataset> result = gdsREST.searchDatasets(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).searchDatasets(filter);
    }

    @Test
    public void testListDatasetNames() {
        PList<String> expected = new PList<>();
        expected.setList(Arrays.asList("dataset1", "dataset2"));
        SearchFilter filter = new SearchFilter();

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.getDatasetNames(filter)).thenReturn(expected);

        PList<String> result = gdsREST.listDatasetNames(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).getDatasetNames(filter);
    }

    @Test
    public void testGetDatasetSummary() throws Exception {
        PList<RangerGds.DatasetSummary> expected = new PList<>();
        expected.setList(Arrays.asList(new RangerGds.DatasetSummary()));
        SearchFilter filter = new SearchFilter();

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.getDatasetSummary(filter)).thenReturn(expected);

        PList<RangerGds.DatasetSummary> result = gdsREST.getDatasetSummary(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).getDatasetSummary(filter);
    }

    @Test
    public void testGetEnhancedDatasetSummary() throws Exception {
        SearchFilter filter = new SearchFilter();
        RangerGds.DatasetsSummary expected = new RangerGds.DatasetsSummary();

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.getEnhancedDatasetSummary(filter)).thenReturn(expected);

        RangerGds.DatasetsSummary result = gdsREST.getEnhancedDatasetSummary(request);

        assertNotNull(result);
        verify(gdsStore).getEnhancedDatasetSummary(filter);
    }

    @Test
    public void testAddDatasetPolicy() throws Exception {
        Long datasetId = 1L;
        RangerPolicy policy = createPolicy();
        RangerPolicy expected = createPolicy();
        expected.setId(1L);

        when(gdsStore.addDatasetPolicy(datasetId, policy)).thenReturn(expected);

        RangerPolicy result = gdsREST.addDatasetPolicy(datasetId, policy);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).addDatasetPolicy(datasetId, policy);
    }

    @Test
    public void testUpdateDatasetPolicy() throws Exception {
        Long datasetId = 1L;
        Long policyId = 2L;
        RangerPolicy policy = createPolicy();
        RangerPolicy expected = createPolicy();
        expected.setId(policyId);

        when(gdsStore.updateDatasetPolicy(eq(datasetId), any(RangerPolicy.class))).thenReturn(expected);

        RangerPolicy result = gdsREST.updateDatasetPolicy(datasetId, policyId, policy);

        assertNotNull(result);
        assertEquals(policyId, result.getId());
        verify(gdsStore).updateDatasetPolicy(eq(datasetId), any(RangerPolicy.class));
    }

    @Test
    public void testDeleteDatasetPolicy() throws Exception {
        Long datasetId = 1L;
        Long policyId = 2L;

        doNothing().when(gdsStore).deleteDatasetPolicy(datasetId, policyId);

        gdsREST.deleteDatasetPolicy(datasetId, policyId);

        verify(gdsStore).deleteDatasetPolicy(datasetId, policyId);
    }

    @Test
    public void testGetDatasetPolicy() throws Exception {
        Long datasetId = 1L;
        Long policyId = 2L;
        RangerPolicy expected = createPolicy();
        expected.setId(policyId);

        when(gdsStore.getDatasetPolicy(datasetId, policyId)).thenReturn(expected);

        RangerPolicy result = gdsREST.getDatasetPolicy(datasetId, policyId);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getDatasetPolicy(datasetId, policyId);
    }

    @Test
    public void testGetDatasetPolicies() throws Exception {
        Long datasetId = 1L;
        List<RangerPolicy> expected = Arrays.asList(createPolicy(), createPolicy());

        when(gdsStore.getDatasetPolicies(datasetId)).thenReturn(expected);

        List<RangerPolicy> result = gdsREST.getDatasetPolicies(datasetId, request);

        assertNotNull(result);
        assertEquals(expected.size(), result.size());
        verify(gdsStore).getDatasetPolicies(datasetId);
    }

    @Test
    public void testCreateProject() {
        RangerGds.RangerProject project = createProject();
        RangerGds.RangerProject expected = createProject();
        expected.setId(1L);

        when(gdsStore.createProject(project)).thenReturn(expected);

        RangerGds.RangerProject result = gdsREST.createProject(project);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).createProject(project);
    }

    @Test
    public void testUpdateProject() throws Exception {
        Long projectId = 1L;
        RangerGds.RangerProject project = createProject();
        RangerGds.RangerProject expected = createProject();
        expected.setId(projectId);

        when(gdsStore.updateProject(any(RangerGds.RangerProject.class))).thenReturn(expected);

        RangerGds.RangerProject result = gdsREST.updateProject(projectId, project);

        assertNotNull(result);
        assertEquals(projectId, result.getId());
        verify(gdsStore).updateProject(any(RangerGds.RangerProject.class));
    }

    @Test
    public void testDeleteProject() throws Exception {
        Long projectId = 1L;

        doNothing().when(gdsStore).deleteProject(projectId, false);

        gdsREST.deleteProject(projectId, request);

        verify(gdsStore).deleteProject(projectId, false);
    }

    @Test
    public void testGetProject() throws Exception {
        Long projectId = 1L;
        RangerGds.RangerProject expected = createProject();
        expected.setId(projectId);

        when(gdsStore.getProject(projectId)).thenReturn(expected);

        RangerGds.RangerProject result = gdsREST.getProject(projectId);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getProject(projectId);
    }

    @Test
    public void testGetProjectNotFound() throws Exception {
        Long projectId = 1L;

        when(gdsStore.getProject(projectId)).thenReturn(null);
        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_NOT_FOUND), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.getProject(projectId));
    }

    @Test
    public void testSearchProjects() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.RangerProject> expected = new PList<>();
        expected.setList(Arrays.asList(createProject()));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.searchProjects(filter)).thenReturn(expected);

        PList<RangerGds.RangerProject> result = gdsREST.searchProjects(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).searchProjects(filter);
    }

    @Test
    public void testListProjectNames() {
        SearchFilter filter = new SearchFilter();
        PList<String> expected = new PList<>();
        expected.setList(Arrays.asList("project1", "project2"));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.getProjectNames(filter)).thenReturn(expected);

        PList<String> result = gdsREST.listProjectNames(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).getProjectNames(filter);
    }

    @Test
    public void testAddProjectPolicy() throws Exception {
        Long projectId = 1L;
        RangerPolicy policy = createPolicy();
        RangerPolicy expected = createPolicy();
        expected.setId(1L);

        when(gdsStore.addProjectPolicy(projectId, policy)).thenReturn(expected);

        RangerPolicy result = gdsREST.addProjectPolicy(projectId, policy);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).addProjectPolicy(projectId, policy);
    }

    @Test
    public void testUpdateProjectPolicy() throws Exception {
        Long projectId = 1L;
        Long policyId = 2L;
        RangerPolicy policy = createPolicy();
        RangerPolicy expected = createPolicy();
        expected.setId(policyId);

        when(gdsStore.updateProjectPolicy(eq(projectId), any(RangerPolicy.class))).thenReturn(expected);

        RangerPolicy result = gdsREST.updateProjectPolicy(projectId, policyId, policy);

        assertNotNull(result);
        assertEquals(policyId, result.getId());
        verify(gdsStore).updateProjectPolicy(eq(projectId), any(RangerPolicy.class));
    }

    @Test
    public void testDeleteProjectPolicy() throws Exception {
        Long projectId = 1L;
        Long policyId = 2L;

        doNothing().when(gdsStore).deleteProjectPolicy(projectId, policyId);

        gdsREST.deleteProjectPolicy(projectId, policyId);

        verify(gdsStore).deleteProjectPolicy(projectId, policyId);
    }

    @Test
    public void testGetProjectPolicy() throws Exception {
        Long projectId = 1L;
        Long policyId = 2L;
        RangerPolicy expected = createPolicy();
        expected.setId(policyId);

        when(gdsStore.getProjectPolicy(projectId, policyId)).thenReturn(expected);

        RangerPolicy result = gdsREST.getProjectPolicy(projectId, policyId);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getProjectPolicy(projectId, policyId);
    }

    @Test
    public void testGetProjectPolicies() throws Exception {
        Long projectId = 1L;
        List<RangerPolicy> expected = Arrays.asList(createPolicy(), createPolicy());

        when(gdsStore.getProjectPolicies(projectId)).thenReturn(expected);

        List<RangerPolicy> result = gdsREST.getProjectPolicies(projectId, request);

        assertNotNull(result);
        assertEquals(expected.size(), result.size());
        verify(gdsStore).getProjectPolicies(projectId);
    }

    @Test
    public void testCreateDataShare() {
        RangerGds.RangerDataShare dataShare = createDataShare();
        RangerGds.RangerDataShare expected = createDataShare();
        expected.setId(1L);

        when(gdsStore.createDataShare(dataShare)).thenReturn(expected);

        RangerGds.RangerDataShare result = gdsREST.createDataShare(dataShare);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).createDataShare(dataShare);
    }

    @Test
    public void testUpdateDataShare() {
        Long dataShareId = 1L;
        RangerGds.RangerDataShare dataShare = createDataShare();
        RangerGds.RangerDataShare expected = createDataShare();
        expected.setId(dataShareId);

        when(gdsStore.updateDataShare(any(RangerGds.RangerDataShare.class))).thenReturn(expected);

        RangerGds.RangerDataShare result = gdsREST.updateDataShare(dataShareId, dataShare);

        assertNotNull(result);
        assertEquals(dataShareId, result.getId());
        verify(gdsStore).updateDataShare(any(RangerGds.RangerDataShare.class));
    }

    @Test
    public void testDeleteDataShare() {
        Long dataShareId = 1L;

        when(request.getParameter("forceDelete")).thenReturn("false");
        doNothing().when(gdsStore).deleteDataShare(dataShareId, false);

        gdsREST.deleteDataShare(dataShareId, request);

        verify(gdsStore).deleteDataShare(dataShareId, false);
    }

    @Test
    public void testDeleteDataShareForceDelete() {
        Long dataShareId = 1L;

        when(request.getParameter("forceDelete")).thenReturn("true");
        doNothing().when(gdsStore).deleteDataShare(dataShareId, true);

        gdsREST.deleteDataShare(dataShareId, request);

        verify(gdsStore).deleteDataShare(dataShareId, true);
    }

    @Test
    public void testGetDataShare() throws Exception {
        Long dataShareId = 1L;
        RangerGds.RangerDataShare expected = createDataShare();
        expected.setId(dataShareId);

        when(gdsStore.getDataShare(dataShareId)).thenReturn(expected);

        RangerGds.RangerDataShare result = gdsREST.getDataShare(dataShareId);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getDataShare(dataShareId);
    }

    @Test
    public void testGetDataShareNotFound() throws Exception {
        Long dataShareId = 1L;

        when(gdsStore.getDataShare(dataShareId)).thenReturn(null);
        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_NOT_FOUND), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.getDataShare(dataShareId));
    }

    @Test
    public void testSearchDataShares() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.RangerDataShare> expected = new PList<>();
        expected.setList(Arrays.asList(createDataShare()));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.searchDataShares(filter)).thenReturn(expected);

        PList<RangerGds.RangerDataShare> result = gdsREST.searchDataShares(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).searchDataShares(filter);
    }

    @Test
    public void testGetDataShareSummary() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.DataShareSummary> expected = new PList<>();
        expected.setList(Arrays.asList(new RangerGds.DataShareSummary()));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.getDataShareSummary(filter)).thenReturn(expected);

        PList<RangerGds.DataShareSummary> result = gdsREST.getDataShareSummary(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).getDataShareSummary(filter);
    }

    @Test
    public void testAddSharedResources() {
        List<RangerGds.RangerSharedResource> resources = Arrays.asList(createSharedResource(), createSharedResource());
        List<RangerGds.RangerSharedResource> expected = Arrays.asList(createSharedResource(), createSharedResource());

        when(gdsStore.addSharedResources(resources)).thenReturn(expected);

        List<RangerGds.RangerSharedResource> result = gdsREST.addSharedResources(resources);

        assertNotNull(result);
        assertEquals(expected.size(), result.size());
        verify(gdsStore).addSharedResources(resources);
    }

    @Test
    public void testAddSharedResourcesBatchSizeExceeded() throws Exception {
        List<RangerGds.RangerSharedResource> resources = new ArrayList<>();
        for (int i = 0; i < 101; i++) {
            resources.add(createSharedResource());
        }
        when(restErrorUtil.createRESTException(anyString())).thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.addSharedResources(resources));
    }

    @Test
    public void testUpdateSharedResource() {
        Long resourceId = 1L;
        RangerGds.RangerSharedResource resource = createSharedResource();
        RangerGds.RangerSharedResource expected = createSharedResource();
        expected.setId(resourceId);

        when(gdsStore.updateSharedResource(any(RangerGds.RangerSharedResource.class))).thenReturn(expected);

        RangerGds.RangerSharedResource result = gdsREST.updateSharedResource(resourceId, resource);

        assertNotNull(result);
        assertEquals(resourceId, result.getId());
        verify(gdsStore).updateSharedResource(any(RangerGds.RangerSharedResource.class));
    }

    @Test
    public void testRemoveSharedResource() {
        Long resourceId = 1L;

        doNothing().when(gdsStore).removeSharedResources(Arrays.asList(resourceId));

        gdsREST.removeSharedResource(resourceId);

        verify(gdsStore).removeSharedResources(Arrays.asList(resourceId));
    }

    @Test
    public void testRemoveSharedResources() {
        List<Long> resourceIds = Arrays.asList(1L, 2L, 3L);

        doNothing().when(gdsStore).removeSharedResources(resourceIds);

        gdsREST.removeSharedResources(resourceIds);

        verify(gdsStore).removeSharedResources(resourceIds);
    }

    @Test
    public void testRemoveSharedResourcesBatchSizeExceeded() {
        List<Long> resourceIds = new ArrayList<>();
        for (long i = 0; i < 101; i++) {
            resourceIds.add(i);
        }
        Mockito.when(restErrorUtil.createRESTException(Mockito.anyString())).thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.removeSharedResources(resourceIds));
    }

    @Test
    public void testGetSharedResource() {
        Long resourceId = 1L;
        RangerGds.RangerSharedResource expected = createSharedResource();
        expected.setId(resourceId);

        when(gdsStore.getSharedResource(resourceId)).thenReturn(expected);

        RangerGds.RangerSharedResource result = gdsREST.getSharedResource(resourceId);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getSharedResource(resourceId);
    }

    @Test
    public void testGetSharedResourceNotFound() {
        Long resourceId = 1L;

        when(gdsStore.getSharedResource(resourceId)).thenReturn(null);
        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_NOT_FOUND), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.getSharedResource(resourceId));
    }

    @Test
    public void testSearchSharedResources() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.RangerSharedResource> expected = new PList<>();
        expected.setList(Arrays.asList(createSharedResource()));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.searchSharedResources(filter)).thenReturn(expected);

        PList<RangerGds.RangerSharedResource> result = gdsREST.searchSharedResources(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).searchSharedResources(filter);
    }

    @Test
    public void testAddDataShareInDataset() throws Exception {
        RangerGds.RangerDataShareInDataset dataShareInDataset = createDataShareInDataset(1L);
        RangerGds.RangerDataShareInDataset expected = createDataShareInDataset(1L);
        expected.setId(1L);

        when(gdsStore.addDataShareInDataset(dataShareInDataset)).thenReturn(expected);

        RangerGds.RangerDataShareInDataset result = gdsREST.addDataShareInDataset(dataShareInDataset);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).addDataShareInDataset(dataShareInDataset);
    }

    @Test
    public void testUpdateDataShareInDataset() {
        Long id = 1L;
        RangerGds.RangerDataShareInDataset dataShareInDataset = createDataShareInDataset(1L);
        RangerGds.RangerDataShareInDataset expected = createDataShareInDataset(1L);
        expected.setId(id);

        when(gdsStore.updateDataShareInDataset(any(RangerGds.RangerDataShareInDataset.class))).thenReturn(expected);

        RangerGds.RangerDataShareInDataset result = gdsREST.updateDataShareInDataset(id, dataShareInDataset);

        assertNotNull(result);
        assertEquals(id, result.getId());
        verify(gdsStore).updateDataShareInDataset(any(RangerGds.RangerDataShareInDataset.class));
    }

    @Test
    public void testRemoveDataShareInDataset() {
        Long id = 1L;

        doNothing().when(gdsStore).removeDataShareInDataset(id);

        gdsREST.removeDataShareInDataset(id);

        verify(gdsStore).removeDataShareInDataset(id);
    }

    @Test
    public void testGetDataShareInDataset() {
        Long id = 1L;
        RangerGds.RangerDataShareInDataset expected = createDataShareInDataset(1L);
        expected.setId(id);

        when(gdsStore.getDataShareInDataset(id)).thenReturn(expected);

        RangerGds.RangerDataShareInDataset result = gdsREST.getDataShareInDataset(id);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getDataShareInDataset(id);
    }

    @Test
    public void testSearchDataShareInDatasets() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.RangerDataShareInDataset> expected = new PList<>();
        expected.setList(Arrays.asList(createDataShareInDataset(1L)));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.searchDataShareInDatasets(filter)).thenReturn(expected);

        PList<RangerGds.RangerDataShareInDataset> result = gdsREST.searchDataShareInDatasets(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).searchDataShareInDatasets(filter);
    }

    @Test
    public void testGetDshInDsSummary() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.DataShareInDatasetSummary> expected = new PList<>();
        expected.setList(Arrays.asList(new RangerGds.DataShareInDatasetSummary()));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.getDshInDsSummary(filter)).thenReturn(expected);

        PList<RangerGds.DataShareInDatasetSummary> result = gdsREST.getDshInDsSummary(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).getDshInDsSummary(filter);
    }

    @Test
    public void testAddDatasetInProject() throws Exception {
        RangerGds.RangerDatasetInProject datasetInProject = createDatasetInProject();
        RangerGds.RangerDatasetInProject expected = createDatasetInProject();
        expected.setId(1L);

        when(gdsStore.addDatasetInProject(datasetInProject)).thenReturn(expected);

        RangerGds.RangerDatasetInProject result = gdsREST.addDatasetInProject(datasetInProject);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).addDatasetInProject(datasetInProject);
    }

    @Test
    public void testUpdateDatasetInProject() {
        Long id = 1L;
        RangerGds.RangerDatasetInProject datasetInProject = createDatasetInProject();
        RangerGds.RangerDatasetInProject expected = createDatasetInProject();
        expected.setId(id);

        when(gdsStore.updateDatasetInProject(any(RangerGds.RangerDatasetInProject.class))).thenReturn(expected);

        RangerGds.RangerDatasetInProject result = gdsREST.updateDatasetInProject(id, datasetInProject);

        assertNotNull(result);
        assertEquals(id, result.getId());
        verify(gdsStore).updateDatasetInProject(any(RangerGds.RangerDatasetInProject.class));
    }

    @Test
    public void testRemoveDatasetInProject() {
        Long id = 1L;

        doNothing().when(gdsStore).removeDatasetInProject(id);

        gdsREST.removeDatasetInProject(id);

        verify(gdsStore).removeDatasetInProject(id);
    }

    @Test
    public void testGetDatasetInProject() {
        Long id = 1L;
        RangerGds.RangerDatasetInProject expected = createDatasetInProject();
        expected.setId(id);

        when(gdsStore.getDatasetInProject(id)).thenReturn(expected);

        RangerGds.RangerDatasetInProject result = gdsREST.getDatasetInProject(id);

        assertNotNull(result);
        assertEquals(expected.getId(), result.getId());
        verify(gdsStore).getDatasetInProject(id);
    }

    @Test
    public void testSearchDatasetInProjects() {
        SearchFilter filter = new SearchFilter();
        PList<RangerGds.RangerDatasetInProject> expected = new PList<>();
        expected.setList(Arrays.asList(createDatasetInProject()));

        when(searchUtil.getSearchFilter(request, datasetService.sortFields)).thenReturn(filter);
        when(gdsStore.searchDatasetInProjects(filter)).thenReturn(expected);

        PList<RangerGds.RangerDatasetInProject> result = gdsREST.searchDatasetInProjects(request);

        assertNotNull(result);
        assertEquals(expected.getList().size(), result.getList().size());
        verify(gdsStore).searchDatasetInProjects(filter);
    }

    @Test
    public void testGetServiceGdsInfoIfUpdated() throws Exception {
        String serviceName = "testService";
        Long lastKnownVersion = 1L;
        Long lastActivationTime = 0L;
        String pluginId = "plugin1";
        String clusterName = "cluster1";
        String pluginCapabilities = "capabilities";

        ServiceGdsInfo expected = new ServiceGdsInfo();
        expected.setGdsVersion(2L);

        doNothing().when(bizUtil).failUnauthenticatedDownloadIfNotAllowed();
        when(serviceUtil.isValidateHttpsAuthentication(serviceName, request)).thenReturn(true);
        when(gdsStore.getGdsInfoIfUpdated(serviceName, lastKnownVersion)).thenReturn(expected);

        ServiceGdsInfo result = gdsREST.getServiceGdsInfoIfUpdated(serviceName, lastKnownVersion,
                lastActivationTime, pluginId, clusterName, pluginCapabilities, request);

        assertNotNull(result);
        assertEquals(expected.getGdsVersion(), result.getGdsVersion());
        verify(gdsStore).getGdsInfoIfUpdated(serviceName, lastKnownVersion);
    }

    @Test
    public void testGetServiceGdsInfoIfUpdatedNotModified() throws Exception {
        String serviceName = "testService";
        Long lastKnownVersion = 1L;

        doNothing().when(bizUtil).failUnauthenticatedDownloadIfNotAllowed();
        when(serviceUtil.isValidateHttpsAuthentication(serviceName, request)).thenReturn(true);
        when(gdsStore.getGdsInfoIfUpdated(serviceName, lastKnownVersion)).thenReturn(null);
        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_NOT_MODIFIED), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class,
                () -> gdsREST.getServiceGdsInfoIfUpdated(serviceName, lastKnownVersion, 0L, "pluginId", "clusterName", "capabilities", request));
    }

    @Test
    public void testGetSecureServiceGdsInfoIfUpdated() throws Exception {
        String serviceName = "testService";
        Long lastKnownVersion = 1L;
        Long lastActivationTime = 0L;
        String pluginId = "plugin1";
        String clusterName = "cluster1";
        String pluginCapabilities = "capabilities";

        ServiceGdsInfo expected = new ServiceGdsInfo();
        expected.setGdsVersion(2L);

        doNothing().when(bizUtil).failUnauthenticatedDownloadIfNotAllowed();
        when(serviceUtil.isValidateHttpsAuthentication(serviceName, request)).thenReturn(true);
        when(gdsStore.getGdsInfoIfUpdated(serviceName, lastKnownVersion)).thenReturn(expected);

        ServiceGdsInfo result = gdsREST.getSecureServiceGdsInfoIfUpdated(serviceName, lastKnownVersion,
                lastActivationTime, pluginId, clusterName, pluginCapabilities, request);

        assertNotNull(result);
        assertEquals(expected.getGdsVersion(), result.getGdsVersion());
        verify(gdsStore).getGdsInfoIfUpdated(serviceName, lastKnownVersion);
    }

    @Test
    public void testGetDataSetGrants() throws Exception {
        Long datasetId = 1L;
        List<RangerPolicy> policies = Arrays.asList(createPolicyForDataSet(createRangerDataSet()));
        List<RangerGrant> expected = createAndGetSampleGrantData();

        when(gdsStore.getDatasetPolicies(datasetId)).thenReturn(policies);

        List<RangerGrant> result = gdsREST.getDataSetGrants(datasetId, request);

        assertNotNull(result);
        verify(gdsStore).getDatasetPolicies(datasetId);
    }

    @Test
    public void testGetDataSetGrantsNoPolicies() throws Exception {
        Long datasetId = 1L;

        when(gdsStore.getDatasetPolicies(datasetId)).thenReturn(Collections.emptyList());

        List<RangerGrant> result = gdsREST.getDataSetGrants(datasetId, request);

        assertNotNull(result);
        assertTrue(result.isEmpty());
        verify(gdsStore).getDatasetPolicies(datasetId);
    }

    @Test
    public void testUpdateDataSetGrants() throws Exception {
        Long datasetId = 1L;
        List<RangerGrant> rangerGrants = createAndGetSampleGrantData();
        RangerPolicy policy = createPolicyForDataSet(createRangerDataSet());
        RangerPolicy updatedPolicy = createPolicyForDataSet(createRangerDataSet());
        updatedPolicy.setId(1L);

        when(gdsStore.getDatasetPolicies(datasetId)).thenReturn(Arrays.asList(policy));
        when(gdsStore.updateDatasetPolicy(eq(datasetId), any(RangerPolicy.class))).thenReturn(updatedPolicy);

        RangerPolicyHeader result = gdsREST.updateDataSetGrants(datasetId, rangerGrants);

        assertNotNull(result);
        assertEquals(updatedPolicy.getId(), result.getId());
        verify(gdsStore).getDatasetPolicies(datasetId);
        verify(gdsStore).updateDatasetPolicy(eq(datasetId), any(RangerPolicy.class));
    }

    @Test
    public void testUpdateDataSetGrantsNoPolicyExists() throws Exception {
        Long datasetId = 1L;
        List<RangerGrant> rangerGrants = createAndGetSampleGrantData();
        RangerPolicy newPolicy = new RangerPolicy();
        newPolicy.setId(1L);
        RangerPolicy updatedPolicy = createPolicyForDataSet(createRangerDataSet());
        updatedPolicy.setId(1L);

        when(gdsStore.getDatasetPolicies(datasetId)).thenReturn(Collections.emptyList());
        when(gdsStore.addDatasetPolicy(eq(datasetId), any(RangerPolicy.class))).thenReturn(newPolicy);
        when(gdsStore.updateDatasetPolicy(eq(datasetId), any(RangerPolicy.class))).thenReturn(updatedPolicy);

        RangerPolicyHeader result = gdsREST.updateDataSetGrants(datasetId, rangerGrants);

        assertNotNull(result);
        assertEquals(updatedPolicy.getId(), result.getId());
        verify(gdsStore).getDatasetPolicies(datasetId);
        verify(gdsStore).addDatasetPolicy(eq(datasetId), any(RangerPolicy.class));
        verify(gdsStore).updateDatasetPolicy(eq(datasetId), any(RangerPolicy.class));
    }

    // TODO: Commenting out tests for non-existent FGAC methods until they are implemented in GdsREST
    /*
    @Test
    public void testGetFgacStatusForDataShareById() throws Exception {
        Long dataShareId = 1L;
        RangerGds.RangerDataShare dataShare = createDataShare();
        dataShare.setService(SERVICE_HIVE);

        SearchFilter filter = new SearchFilter();
        PList<RangerGds.RangerSharedResource> sharedResources = new PList<>();
        sharedResources.setList(Arrays.asList(createSharedResource()));

        when(gdsStore.getDataShare(dataShareId)).thenReturn(dataShare);
        when(searchUtil.getSearchFilter(request, sharedResourceService.sortFields)).thenReturn(filter);
        when(gdsStore.searchSharedResources(filter)).thenReturn(sharedResources);

        GdsREST spyGdsREST = Mockito.spy(gdsREST);
        when(spyGdsREST.evaluateSharedResourceForMatchingFgacPolicies(any(RangerGds.RangerSharedResource.class), anyString(), anyString())).thenReturn(new HashSet<>());

        Map<Long, Set<Long>> result = spyGdsREST.getFgacStatusForDataShareById(dataShareId, request);

        assertNotNull(result);
        verify(gdsStore).getDataShare(dataShareId);
        verify(gdsStore).searchSharedResources(filter);
    }

    @Test
    public void testGetFgacStatusForDataShareByIdMissingId() {
        when(restErrorUtil.createRESTException(eq(HttpServletResponse.SC_BAD_REQUEST), anyString(), eq(false)))
                .thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> gdsREST.getFgacStatusForDataShareById(null, request));
    }

    @Test
    public void testGetFgacStatusForSharedResourceById() {
        Long resourceId = 1L;
        String serviceDefName = SERVICE_DEF_HIVE;
        String serviceName = SERVICE_HIVE;
        RangerGds.RangerSharedResource resource = createSharedResource();

        when(gdsStore.getSharedResource(resourceId)).thenReturn(resource);
        when(serviceREST.getPoliciesForResource(anyString(), anyString(), anyMap())).thenReturn(Collections.emptyList());

        Set<Long> result = gdsREST.getFgacStatusForSharedResourceById(resourceId, serviceDefName, serviceName);

        assertNotNull(result);
        verify(gdsStore).getSharedResource(resourceId);
    }

    @Test
    public void testGetFgacStatusForSharedResource() {
        RangerGds.RangerSharedResource resource = createSharedResource();
        String serviceDefName = SERVICE_DEF_HIVE;
        String serviceName = SERVICE_HIVE;

        when(serviceREST.getPoliciesForResource(anyString(), anyString(), anyMap())).thenReturn(Collections.emptyList());

        Set<Long> result = gdsREST.getFgacStatusForSharedResource(serviceDefName, serviceName, resource);

        assertNotNull(result);
    }

    @Test
    public void testEvaluateSharedResourceForMatchingFgacPolicies() {
        RangerGds.RangerSharedResource resource = createSharedResource();
        String serviceDefName = SERVICE_DEF_HIVE;
        String serviceName = SERVICE_HIVE;

        when(serviceREST.getPoliciesForResource(anyString(), anyString(), anyMap())).thenReturn(Collections.emptyList());

        Set<Long> result = gdsREST.evaluateSharedResourceForMatchingFgacPolicies(resource, serviceDefName, serviceName);

        assertNotNull(result);
    }
    */

    @Test
    public void testAddDataSetGrants() throws Exception {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);

        List<RangerPolicy.RangerPolicyItem> policyItems  = new ArrayList<>(policy.getPolicyItems());
        List<RangerGrant>                   rangerGrants = createAndGetSampleGrantData();

        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);

        List<RangerPolicy.RangerPolicyItem> updatedPolicyItems = policy.getPolicyItems();

        assertNotEquals(policyItems, updatedPolicyItems);

        assertEquals(policyItems.size() + rangerGrants.size(), updatedPolicyItems.size());

        List<RangerPolicy.RangerPolicyItem> filteredPolicyItems = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));
        assertEquals(filteredPolicyItems, updatedPolicyItems);
    }

    @Test
    public void testUpdatePolicyWithModifiedGrants() throws Exception {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);

        List<RangerGrant> rangerGrants = createAndGetSampleGrantData();
        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);

        String[] requestedPrincipals = {"group:hdfs"};
        when(searchUtil.getParamMultiValues(request, "principal")).thenReturn(requestedPrincipals);

        List<RangerPolicy.RangerPolicyItem> hdfsPolicyItems = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));

        RangerGrant grant3 = new RangerGrant(new RangerPrincipal(RangerPrincipal.PrincipalType.GROUP, "hdfs"), Collections.singletonList("_READ"), Collections.emptyList());
        policy = gdsREST.updatePolicyWithModifiedGrants(policy, Collections.singletonList(grant3));

        List<RangerPolicy.RangerPolicyItem> updatedHdfsPolicyItems = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));

        assertNotNull(updatedHdfsPolicyItems);
        assertEquals(hdfsPolicyItems.size(), updatedHdfsPolicyItems.size());
        assertNotEquals(hdfsPolicyItems, updatedHdfsPolicyItems);
    }

    @Test
    public void testRemoveDataSetGrants() throws Exception {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);
        List<RangerGrant>       rangerGrants  = createAndGetSampleGrantData();

        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);
        List<RangerPolicy.RangerPolicyItem> newPolicyItems = policy.getPolicyItems();

        String[] requestedPrincipals = {"group:hdfs"};
        when(searchUtil.getParamMultiValues(request, "principal")).thenReturn(requestedPrincipals);

        List<RangerPolicy.RangerPolicyItem> existingHdfsPolicyItems = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));

        RangerGrant grant4 = new RangerGrant(new RangerPrincipal(RangerPrincipal.PrincipalType.GROUP, "hdfs"), Collections.emptyList(), Collections.emptyList());
        policy = gdsREST.updatePolicyWithModifiedGrants(policy, Collections.singletonList(grant4));

        List<RangerPolicy.RangerPolicyItem> updatedHdfsPolicyItems = gdsREST.filterPolicyItemsByRequest(policy, request);

        assertNotEquals(existingHdfsPolicyItems, updatedHdfsPolicyItems);
        assertTrue(updatedHdfsPolicyItems.isEmpty(), "Grants for " + Arrays.toString(requestedPrincipals) + " should be empty");
    }

    @Test
    public void testGetAllDataSetGrants() {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);
        List<RangerGrant>       rangerGrants  = createAndGetSampleGrantData();

        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);

        List<RangerPolicy.RangerPolicyItem> policyItems         = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));
        List<RangerGrant>                   policyItemsAsGrants = gdsREST.transformPolicyItemsToGrants(policyItems);

        assertEquals(rangerGrants, policyItemsAsGrants);
    }

    @Test
    public void testGetDataSetGrantsByPrincipal() throws Exception {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);
        List<RangerGrant>       rangerGrants  = createAndGetSampleGrantData();

        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);

        String[] existingRequestedPrincipals = {"user:hive"};
        when(searchUtil.getParamMultiValues(request, "principal")).thenReturn(existingRequestedPrincipals);

        List<RangerPolicy.RangerPolicyItem> filteredPolicyItemsByPrincipal = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));

        assertEquals(1, filteredPolicyItemsByPrincipal.size());
        assertTrue(filteredPolicyItemsByPrincipal.get(0).getUsers().contains("hive"));

        String[] nonexistentRequestedPrincipals = {"user:hadoop"};
        when(searchUtil.getParamMultiValues(request, "principal")).thenReturn(nonexistentRequestedPrincipals);

        filteredPolicyItemsByPrincipal = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));
        assertEquals(0, filteredPolicyItemsByPrincipal.size(), "Grants for Principals: " + Arrays.toString(nonexistentRequestedPrincipals) + " should be empty");
    }

    @Test
    public void testGetDataSetGrantsByAccessType() throws Exception {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);
        List<RangerGrant>       rangerGrants  = createAndGetSampleGrantData();

        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);

        String[] requestedAccessTypes = {"_MANAGE"};
        when(searchUtil.getParamMultiValues(request, "principal")).thenReturn(new String[0]);
        when(searchUtil.getParamMultiValues(request, "accessType")).thenReturn(requestedAccessTypes);

        List<RangerPolicy.RangerPolicyItem> policyItemsByAccessType = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));

        assertEquals(1, policyItemsByAccessType.size());
        assertTrue(policyItemsByAccessType.get(0).getAccesses().stream().anyMatch(x -> Arrays.asList(requestedAccessTypes).contains(x.getType())));

        String[] nonexistentRequestedAccessTypes = {"_DELETE"};
        when(searchUtil.getParamMultiValues(request, "accessType")).thenReturn(nonexistentRequestedAccessTypes);

        List<RangerPolicy.RangerPolicyItem> updatedPolicyItemsByAccessType = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));
        assertTrue(updatedPolicyItemsByAccessType.isEmpty(), "Grants for AccessTypes: " + Arrays.toString(nonexistentRequestedAccessTypes) + " should be empty");
    }

    @Test
    public void testGetDataSetGrantsByPrincipalAndAccessType() throws Exception {
        RangerGds.RangerDataset rangerDataset = createRangerDataSet();
        RangerPolicy            policy        = createPolicyForDataSet(rangerDataset);
        List<RangerGrant>       rangerGrants  = createAndGetSampleGrantData();

        policy = gdsREST.updatePolicyWithModifiedGrants(policy, rangerGrants);

        String[] requestedPrincipals  = {"user:hive"};
        String[] requestedAccessTypes = {"_READ"};

        when(searchUtil.getParamMultiValues(request, "principal")).thenReturn(requestedPrincipals);
        when(searchUtil.getParamMultiValues(request, "accessType")).thenReturn(requestedAccessTypes);

        List<RangerPolicy.RangerPolicyItem> filteredPolicyItems = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));

        assertEquals(1, filteredPolicyItems.size(), "Grants for Principals: " + Arrays.toString(requestedPrincipals) + " and AccessTypes: " + Arrays.toString(requestedAccessTypes) + " should exist");
        assertTrue(filteredPolicyItems.get(0).getUsers().contains("hive"), "Grants for Principals: " + Arrays.toString(requestedPrincipals) + "should exist");
        assertTrue(filteredPolicyItems.get(0).getAccesses().stream().anyMatch(x -> Arrays.asList(requestedAccessTypes).contains(x.getType())), "Grants for AccessTypes: " + Arrays.toString(requestedAccessTypes) + "should exist");

        String[] nonexistentRequestedAccessTypes = {"_DELETE"};
        when(searchUtil.getParamMultiValues(request, "accessType")).thenReturn(nonexistentRequestedAccessTypes);

        List<RangerPolicy.RangerPolicyItem> updatedPolicyItemsByAccessType = new ArrayList<>(gdsREST.filterPolicyItemsByRequest(policy, request));
        assertTrue(updatedPolicyItemsByAccessType.isEmpty(), "Grants for Principals: " + Arrays.toString(requestedPrincipals) + " and AccessTypes: " + Arrays.toString(nonexistentRequestedAccessTypes) + " should be empty");
    }

    @Test
    public void testSearchDataSetsByValidityPeriod() {
        List<RangerGds.RangerDataset> rangerDatasets = new ArrayList<>();

        RangerGds.RangerDataset rangerDataset1 = createRangerDataSet();
        updateDatasetValiditySchedule(rangerDataset1, -5, -1);

        RangerGds.RangerDataset rangerDataset2 = createRangerDataSet();
        updateDatasetValiditySchedule(rangerDataset2, -5, 5);

        RangerGds.RangerDataset rangerDataset3 = createRangerDataSet();
        updateDatasetValiditySchedule(rangerDataset3, -10, 2);

        RangerGds.RangerDataset rangerDataset4 = createRangerDataSet();
        updateDatasetValiditySchedule(rangerDataset4, -2, 15);

        RangerGds.RangerDataset rangerDataset5 = createRangerDataSet();
        updateDatasetValiditySchedule(rangerDataset5, 5, 15);

        RangerGds.RangerDataset rangerDataset6 = createRangerDataSet();
        updateDatasetValiditySchedule(rangerDataset6, -15, -5);

        rangerDatasets.addAll(Arrays.asList(rangerDataset1, rangerDataset2, rangerDataset3, rangerDataset4, rangerDataset5, rangerDataset6));
        List<RangerGds.RangerDataset> actualDatasets = new ArrayList<>(rangerDatasets);

        SearchFilter filter = new SearchFilter();
        filter.setParam(SearchFilter.VALIDITY_TIME_ZONE, SearchFilter.DEFAULT_TIME_ZONE);

        //ValiditySchedule Filter criteria-1
        String startTime = getFormattedDateString(-10);
        String endTime   = getFormattedDateString(-2);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_START, startTime);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_END, endTime);

        List<RangerGds.RangerDataset> expectedDatasets = Collections.singletonList(rangerDataset6);

        gdsDBStore.filterDatasetsByValidityExpiration(filter, actualDatasets);

        assertEquals(expectedDatasets.size(), actualDatasets.size(), "Datasets expiry count mismatch between " + startTime + " and " + endTime);

        assertTrue(actualDatasets.containsAll(expectedDatasets), "Mismatch in datasets returned for expiry between " + startTime + " and " + endTime);

        //ValiditySchedule Filter criteria-2
        actualDatasets.clear();
        actualDatasets.addAll(rangerDatasets);

        startTime = getFormattedDateString(-4);
        endTime   = getFormattedDateString(20);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_START, startTime);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_END, endTime);

        expectedDatasets = Arrays.asList(rangerDataset1, rangerDataset2, rangerDataset3, rangerDataset4, rangerDataset5);

        gdsDBStore.filterDatasetsByValidityExpiration(filter, actualDatasets);

        assertEquals(expectedDatasets.size(), actualDatasets.size(), "Datasets expiry count mismatch between " + startTime + " and " + endTime);

        assertTrue(actualDatasets.containsAll(expectedDatasets), "Mismatch in datasets returned for expiry between " + startTime + " and " + endTime);

        //ValiditySchedule Filter criteria-3
        actualDatasets.clear();
        actualDatasets.addAll(rangerDatasets);

        startTime = getFormattedDateString(-15);
        endTime   = getFormattedDateString(0);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_START, startTime);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_END, endTime);

        expectedDatasets = Arrays.asList(rangerDataset1, rangerDataset6);

        gdsDBStore.filterDatasetsByValidityExpiration(filter, actualDatasets);

        assertEquals(expectedDatasets.size(), actualDatasets.size(), "Datasets expiry count mismatch between " + startTime + " and " + endTime);

        assertTrue(actualDatasets.containsAll(expectedDatasets), "Mismatch in datasets returned for expiry between " + startTime + " and " + endTime);

        //ValiditySchedule Filter criteria-4 with invalid date
        actualDatasets.clear();
        actualDatasets.addAll(rangerDatasets);

        startTime = getInvalidDateString(-5);
        endTime   = getFormattedDateString(16);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_START, startTime);
        filter.setParam(SearchFilter.VALIDITY_EXPIRY_END, endTime);

        Mockito.when(restErrorUtil.createRESTException(Mockito.anyString())).thenReturn(new WebApplicationException());

        assertThrows(WebApplicationException.class, () -> {
            gdsDBStore.filterDatasetsByValidityExpiration(filter, actualDatasets);
        });

        //ValiditySchedule Filter criteria-5 without start and end time
        actualDatasets.clear();
        actualDatasets.addAll(rangerDatasets);

        filter.removeParam(SearchFilter.VALIDITY_EXPIRY_START);
        filter.removeParam(SearchFilter.VALIDITY_EXPIRY_END);

        expectedDatasets = rangerDatasets;

        gdsDBStore.filterDatasetsByValidityExpiration(filter, actualDatasets);

        assertEquals(expectedDatasets.size(), actualDatasets.size(), "Datasets expiry count mismatch with empty start and end time");

        assertTrue(actualDatasets.containsAll(expectedDatasets), "Mismatch in datasets returned with empty expiry time range");
    }

    // TODO: Commenting out tests for non-existent FGAC methods until they are implemented in GdsREST
    /*
    @Test
    public void testFGACPoliciesWithMatchedResourceAndTagPolicies() {
        validateFGACPolicies(true, true);
    }

    @Test
    public void testFGACPoliciesWithMatchedTagPolicyOnly() {
        validateFGACPolicies(false, true);
    }

    @Test
    public void testFGACPoliciesWithNoMatchedPolicy() {
        validateFGACPolicies(false, false);
    }

    public void validateFGACPolicies(boolean hasResourcePolicy, boolean hasTagPolicy) {
        List<RangerPolicy> allPolicies = generateHivePolicies();

        RangerPolicy policyToVerify = selectOrCreatePolicy(hasResourcePolicy, allPolicies);

        RangerGds.RangerSharedResource sharedResource = createSharedResource(policyToVerify.getResources());

        if (hasTagPolicy) {
            allPolicies.addAll(generateTagPolicies());
        }

        List<RangerPolicy> matchedPolicies = filterPoliciesForResource(allPolicies, policyToVerify);

        when(serviceREST.getPoliciesForResource(anyString(), anyString(), anyMap())).thenReturn(matchedPolicies);

        Set<Long> expectedPolicyIds = extractFGACPolicyIds(matchedPolicies);
        Set<Long> actualPolicyIds   = gdsREST.evaluateSharedResourceForMatchingFgacPolicies(sharedResource, SERVICE_DEF_HIVE, SERVICE_HIVE);

        assertEquals(expectedPolicyIds.size(), actualPolicyIds.size(), "Mismatch in number of matched FGAC policies");
        assertEquals(expectedPolicyIds, actualPolicyIds, "FGAC policy IDs mismatch");
    }
    */

    private RangerGds.RangerDataset createRangerDataSet() {
        long                    id      = new Random().nextInt(100);
        RangerGds.RangerDataset dataset = new RangerGds.RangerDataset();
        dataset.setId(id);
        dataset.setName("dataset-" + id);
        dataset.setGuid(UUID.randomUUID().toString());

        return dataset;
    }

    private RangerGds.RangerProject createProject() {
        long                    id      = random.nextInt(100);
        RangerGds.RangerProject project = new RangerGds.RangerProject();
        project.setId(id);
        project.setName("project-" + id);
        project.setGuid(UUID.randomUUID().toString());

        return project;
    }

    private RangerGds.RangerDataShare createDataShare() {
        long                      id        = random.nextInt(100);
        RangerGds.RangerDataShare dataShare = new RangerGds.RangerDataShare();
        dataShare.setId(id);
        dataShare.setName("dataShare-" + id);
        dataShare.setGuid(UUID.randomUUID().toString());
        dataShare.setService(SERVICE_HIVE);

        return dataShare;
    }

    private RangerGds.RangerSharedResource createSharedResource() {
        long                           id             = random.nextInt(100);
        RangerGds.RangerSharedResource sharedResource = new RangerGds.RangerSharedResource();
        sharedResource.setId(id);
        sharedResource.setName("resource-" + id);
        sharedResource.setGuid(UUID.randomUUID().toString());
        sharedResource.setResource(createRandomResources(SERVICE_DEF_HIVE, "test"));

        return sharedResource;
    }

    private RangerGds.RangerDataShareInDataset createDataShareInDataset(Long datasetId) {
        RangerGds.RangerDataShareInDataset dataShareInDataset = new RangerGds.RangerDataShareInDataset();
        dataShareInDataset.setDatasetId(datasetId);
        dataShareInDataset.setDataShareId(1L);
        dataShareInDataset.setStatus(RangerGds.GdsShareStatus.ACTIVE);

        return dataShareInDataset;
    }

    private RangerGds.RangerDatasetInProject createDatasetInProject() {
        RangerGds.RangerDatasetInProject datasetInProject = new RangerGds.RangerDatasetInProject();
        datasetInProject.setDatasetId(1L);
        datasetInProject.setProjectId(1L);
        datasetInProject.setStatus(RangerGds.GdsShareStatus.ACTIVE);

        return datasetInProject;
    }

    private RangerPolicy createPolicy() {
        RangerPolicy policy = new RangerPolicy();
        policy.setId((long) random.nextInt(100));
        policy.setName("policy-" + policy.getId());
        policy.setServiceType("gds");
        policy.setService("_gds");

        return policy;
    }

    private RangerGds.RangerDataset updateDatasetValiditySchedule(RangerGds.RangerDataset dataset, int pastDaysToStart, int futureDaysToEnd) {
        String                 start            = getFormattedDateString(pastDaysToStart);
        String                 end              = getFormattedDateString(futureDaysToEnd);
        String                 timezone         = SearchFilter.DEFAULT_TIME_ZONE;
        RangerValiditySchedule validitySchedule = new RangerValiditySchedule(start, end, timezone, null);
        dataset.setValiditySchedule(validitySchedule);

        return dataset;
    }

    private String getFormattedDateString(int days) {
        return getDateString(days, RangerValiditySchedule.VALIDITY_SCHEDULE_DATE_STRING_SPECIFICATION);
    }

    private String getInvalidDateString(int days) {
        return getDateString(days, "yyyy/MM/dd");
    }

    private String getDateString(int days, String pattern) {
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern(pattern);
        LocalDateTime     current       = LocalDateTime.now();

        return current.plusDays(days).format(dateFormatter);
    }

    private RangerPolicy createPolicyForDataSet(RangerGds.RangerDataset dataset) {
        RangerPolicy policy = new RangerPolicy();
        policy.setName("DATASET: " + dataset.getName() + "@" + System.currentTimeMillis());
        policy.setDescription("Policy for dataset: " + dataset.getName());
        policy.setServiceType("gds");
        policy.setService("_gds");
        policy.setZoneName(null);
        policy.setResources(Collections.singletonMap("dataset-id", new RangerPolicy.RangerPolicyResource(dataset.getId().toString())));
        policy.setPolicyType(RangerPolicy.POLICY_TYPE_ACCESS);
        policy.setPolicyPriority(RangerPolicy.POLICY_PRIORITY_NORMAL);
        policy.setAllowExceptions(Collections.emptyList());
        policy.setDenyPolicyItems(Collections.emptyList());
        policy.setDenyExceptions(Collections.emptyList());
        policy.setDataMaskPolicyItems(Collections.emptyList());
        policy.setRowFilterPolicyItems(Collections.emptyList());
        policy.setIsDenyAllElse(Boolean.FALSE);

        return policy;
    }

    private List<RangerGrant> createAndGetSampleGrantData() {
        List<RangerGrant.Condition> conditions = new ArrayList<>();

        RangerGrant.Condition condition1 = new RangerGrant.Condition(null, null);
        condition1.setType("expression");
        condition1.setValues(Arrays.asList("IS_ACCESSED_BEFORE('2024/12/12')", "_STATE == 'CA'"));
        conditions.add(condition1);

        RangerGrant.Condition condition2 = new RangerGrant.Condition(null, null);
        condition2.setType("validitySchedule");
        condition2.setValues(Collections.singletonList("{\"startTime\":\"1970/01/01 00:00:00\",\"endTime\":\"2025/03/08 00:35:28\",\"timeZone\":\"UTC\"}"));
        conditions.add(condition2);

        RangerGrant grant1 = new RangerGrant(new RangerPrincipal(RangerPrincipal.PrincipalType.USER, "hive"), Collections.singletonList("_READ"), conditions);
        RangerGrant grant2 = new RangerGrant(new RangerPrincipal(RangerPrincipal.PrincipalType.GROUP, "hdfs"), Collections.singletonList("_MANAGE"), Collections.emptyList());

        return Arrays.asList(grant1, grant2);
    }

    // Generate a random number(between 5 and 10) of hive policies
    private List<RangerPolicy> generateHivePolicies() {
        return generatePolicies(SERVICE_DEF_HIVE, new int[] {RangerPolicy.POLICY_TYPE_ACCESS, RangerPolicy.POLICY_TYPE_DATAMASK, RangerPolicy.POLICY_TYPE_ROWFILTER}, 5, 10);
    }

    // Generate a random number(between 0 and 3) of tag policies
    private List<RangerPolicy> generateTagPolicies() {
        return generatePolicies(SERVICE_DEF_TAG, new int[] {RangerPolicy.POLICY_TYPE_ACCESS, RangerPolicy.POLICY_TYPE_DATAMASK}, 0, 3);
    }

    private List<RangerPolicy> generatePolicies(String serviceType, int[] policyTypes, int min, int max) {
        List<RangerPolicy> policies    = new ArrayList<>();
        int                policyCount = random.nextInt(max - min + 1) + min;

        for (int i = 0; i < policyCount; i++) {
            int randomPolicyType = policyTypes[random.nextInt(policyTypes.length)];

            Map<String, RangerPolicy.RangerPolicyResource> resources                        = createRandomResources(serviceType, "test");
            int                                            policyInstancesWithSameResources = serviceType.equals(SERVICE_DEF_TAG) ? 1 : (random.nextInt(3) + 1);

            for (int j = 0; j < policyInstancesWithSameResources; j++) {
                policies.add(createPolicy(serviceType, randomPolicyType, resources));
            }
        }
        return policies;
    }

    private RangerPolicy selectOrCreatePolicy(boolean exists, List<RangerPolicy> policies) {
        return exists ? policies.get(random.nextInt(policies.size())) : createPolicy(SERVICE_DEF_HIVE, RangerPolicy.POLICY_TYPE_DATAMASK, createRandomResources(SERVICE_DEF_HIVE, "abc"));
    }

    private Map<String, RangerPolicy.RangerPolicyResource> createRandomResources(String service, String prefix) {
        Map<String, RangerPolicy.RangerPolicyResource> resources = new HashMap<>();
        int                                            id        = random.nextInt(50);

        if (SERVICE_DEF_HIVE.equals(service)) {
            resources.put("database", new RangerPolicy.RangerPolicyResource(prefix + "_db_" + id, false, false));
            resources.put("table", new RangerPolicy.RangerPolicyResource(prefix + "_tb_" + id, false, false));
            resources.put("column", new RangerPolicy.RangerPolicyResource(prefix + "_col_" + id, false, false));
        } else {
            resources.put("tag", new RangerPolicy.RangerPolicyResource(prefix + "_tag_" + id, false, false));
        }
        return resources;
    }

    private RangerPolicy createPolicy(String serviceType, int policyType, Map<String, RangerPolicy.RangerPolicyResource> resources) {
        long         id     = random.nextInt(100);
        RangerPolicy policy = new RangerPolicy();
        policy.setId(id);
        policy.setServiceType(serviceType);
        policy.setPolicyType(policyType);
        policy.setResources(resources);
        return policy;
    }

    private RangerGds.RangerSharedResource createSharedResource(Map<String, RangerPolicy.RangerPolicyResource> resources) {
        long                           id             = random.nextInt(100);
        RangerGds.RangerSharedResource sharedResource = new RangerGds.RangerSharedResource();
        sharedResource.setId(id);
        sharedResource.setName("test_resource_" + id);
        sharedResource.setGuid(UUID.randomUUID().toString());
        sharedResource.setResource(resources);
        return sharedResource;
    }

    private List<RangerPolicy> filterPoliciesForResource(List<RangerPolicy> allPolicies, RangerPolicy policy) {
        return allPolicies.stream().filter(x -> SERVICE_DEF_TAG.equals(x.getServiceType()) || x.getResources().equals(policy.getResources())).collect(Collectors.toList());
    }

    private Set<Long> extractFGACPolicyIds(List<RangerPolicy> policies) {
        return policies.stream().filter(x -> SERVICE_DEF_TAG.equals(x.getServiceType()) || x.getPolicyType() != RangerPolicy.POLICY_TYPE_ACCESS).map(RangerPolicy::getId).collect(Collectors.toSet());
    }
}
