/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.ranger.security.web.filter;

import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.jwk.JWKSet;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.jwk.gen.RSAKeyGenerator;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;
import com.sun.net.httpserver.HttpServer;
import org.apache.hadoop.conf.Configuration;
import org.apache.ranger.authz.handler.RangerAuth;
import org.apache.ranger.common.PropertiesUtil;
import org.apache.ranger.entity.XXAuthSession;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;

import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;

import java.io.IOException;
import java.io.OutputStream;
import java.lang.reflect.Method;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Collection;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.lenient;

/**
 * @generated by Cursor
 * @description <Unit Test for TestRangerJwtAuthFilter class>
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestRangerJwtAuthFilter {
    private static final String ISSUER   = "https://idp.example.com/realms/ranger";
    private static final String AUDIENCE = "ranger-admin";

    @AfterEach
    public void cleanup() {
        SecurityContextHolder.clearContext();
    }

    /* the path Ranger Admin uses: ranger.sso.* properties, JWKS endpoint, RangerJwtAuthFilter.doFilter() */
    @Test
    void testDoFilter_authenticatesBearerTokenAgainstJwks() throws Exception {
        RSAKey     key    = new RSAKeyGenerator(2048).keyID("kid-1").generate();
        HttpServer jwks   = serveJwks(key);
        FilterChain chain = Mockito.mock(FilterChain.class);

        try {
            PropertiesUtil.getPropertiesMap().put(RangerSSOAuthenticationFilter.JWT_AUTH_PROVIDER_URL, "http://127.0.0.1:" + jwks.getAddress().getPort() + "/jwks");
            PropertiesUtil.getPropertiesMap().put(RangerSSOAuthenticationFilter.JWT_AUDIENCES, AUDIENCE);
            PropertiesUtil.getPropertiesMap().put(RangerSSOAuthenticationFilter.JWT_ISSUER, ISSUER);

            RangerJwtAuthFilter filter = new RangerJwtAuthFilter();

            filter.initialize();

            filter.doFilter(requestWithBearer(sign(key, claims().build())), Mockito.mock(ServletResponse.class), chain);

            Authentication auth = SecurityContextHolder.getContext().getAuthentication();

            assertTrue(auth instanceof RangerAuthenticationToken);
            assertEquals(XXAuthSession.AUTH_TYPE_JWT, ((RangerAuthenticationToken) auth).getAuthType());
            assertEquals("alice", ((User) auth.getPrincipal()).getUsername());

            for (JWTClaimsSet bad : new JWTClaimsSet[] {claims().audience("other-service").build(), claims().issuer("https://idp.example.com/realms/other").build(), claims().expirationTime(null).build(), claims().subject(null).build()}) {
                SecurityContextHolder.clearContext();

                filter.doFilter(requestWithBearer(sign(key, bad)), Mockito.mock(ServletResponse.class), chain);

                assertNull(SecurityContextHolder.getContext().getAuthentication(), bad.toString());
            }

            SecurityContextHolder.clearContext();

            filter.doFilter(requestWithBearer(sign(new RSAKeyGenerator(2048).keyID("kid-1").generate(), claims().build())), Mockito.mock(ServletResponse.class), chain);

            assertNull(SecurityContextHolder.getContext().getAuthentication(), "token signed by a key that is not in the JWKS");
        } finally {
            jwks.stop(0);
            clearJwtProperties();
        }
    }

    @Test
    void testInitialize_withoutProviderUrl_rejectsEveryToken() throws Exception {
        RSAKey key = new RSAKeyGenerator(2048).keyID("kid-1").generate();

        try {
            PropertiesUtil.getPropertiesMap().remove(RangerSSOAuthenticationFilter.JWT_AUTH_PROVIDER_URL);
            PropertiesUtil.getPropertiesMap().put(RangerSSOAuthenticationFilter.JWT_AUDIENCES, AUDIENCE);
            PropertiesUtil.getPropertiesMap().put(RangerSSOAuthenticationFilter.JWT_ISSUER, ISSUER);

            RangerJwtAuthFilter filter = new RangerJwtAuthFilter();

            assertDoesNotThrow(() -> filter.initialize());

            filter.doFilter(requestWithBearer(sign(key, claims().build())), Mockito.mock(ServletResponse.class), Mockito.mock(FilterChain.class));

            assertNull(SecurityContextHolder.getContext().getAuthentication());
        } finally {
            clearJwtProperties();
        }
    }

    private static HttpServer serveJwks(RSAKey key) throws IOException {
        byte[]     body   = new JWKSet(key.toPublicJWK()).toString().getBytes(StandardCharsets.UTF_8);
        HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);

        server.createContext("/jwks", exchange -> {
            exchange.getResponseHeaders().add("Content-Type", "application/json");
            exchange.sendResponseHeaders(200, body.length);

            try (OutputStream os = exchange.getResponseBody()) {
                os.write(body);
            }
        });
        server.start();

        return server;
    }

    private static JWTClaimsSet.Builder claims() {
        return new JWTClaimsSet.Builder().issuer(ISSUER).audience(AUDIENCE).subject("alice").expirationTime(new Date(System.currentTimeMillis() + 60_000));
    }

    private static String sign(RSAKey key, JWTClaimsSet claims) throws Exception {
        SignedJWT jwt = new SignedJWT(new JWSHeader.Builder(JWSAlgorithm.RS256).keyID(key.getKeyID()).build(), claims);

        jwt.sign(new RSASSASigner(key));

        return jwt.serialize();
    }

    private static HttpServletRequest requestWithBearer(String token) {
        HttpServletRequest req = Mockito.mock(HttpServletRequest.class);

        lenient().when(req.getHeader("Authorization")).thenReturn("Bearer " + token);
        lenient().when(req.getRemoteAddr()).thenReturn("127.0.0.1");

        return req;
    }

    private static void clearJwtProperties() {
        PropertiesUtil.getPropertiesMap().remove(RangerSSOAuthenticationFilter.JWT_AUTH_PROVIDER_URL);
        PropertiesUtil.getPropertiesMap().remove(RangerSSOAuthenticationFilter.JWT_AUDIENCES);
        PropertiesUtil.getPropertiesMap().remove(RangerSSOAuthenticationFilter.JWT_ISSUER);
    }

    @Test
    public void testInit_noopDoesNotThrow() {
        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();
        FilterConfig cfg = Mockito.mock(FilterConfig.class);
        assertDoesNotThrow(() -> filter.init(cfg));
    }

    @Test
    public void testDestroy_noopDoesNotThrow() {
        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();
        assertDoesNotThrow(() -> filter.destroy());
    }

    @Test
    public void testInitialize_doesNotThrow() {
        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();
        assertDoesNotThrow(() -> filter.initialize());
    }

    @Test
    public void testDoFilter_setsAuthenticationWhenAuthenticateSucceeds() throws ServletException, IOException {
        RangerJwtAuthFilter filter = Mockito.spy(new RangerJwtAuthFilter());

        HttpServletRequest req = Mockito.mock(HttpServletRequest.class);
        ServletResponse res = Mockito.mock(ServletResponse.class);
        FilterChain chain = Mockito.mock(FilterChain.class);

        RangerAuth rangerAuth = new RangerAuth("alice", RangerAuth.AuthType.JWT_JWKS);

        doReturn(rangerAuth).when(filter).authenticate(any(HttpServletRequest.class));

        filter.doFilter(req, res, chain);

        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        assertNotNull(auth);
        assertTrue(auth instanceof RangerAuthenticationToken);
        assertEquals(XXAuthSession.AUTH_TYPE_JWT, ((RangerAuthenticationToken) auth).getAuthType());
        assertTrue(auth.getPrincipal() instanceof User);
        User user = (User) auth.getPrincipal();
        assertEquals("alice", user.getUsername());

        Collection<? extends GrantedAuthority> authorities = auth.getAuthorities();
        assertNotNull(authorities);
        assertFalse(authorities.isEmpty());
    }

    @Test
    public void testDoFilter_leavesAuthenticationNullWhenAuthenticateReturnsNull()
            throws ServletException, IOException {
        RangerJwtAuthFilter filter = Mockito.spy(new RangerJwtAuthFilter());

        HttpServletRequest req = Mockito.mock(HttpServletRequest.class);
        ServletResponse res = Mockito.mock(ServletResponse.class);
        FilterChain chain = Mockito.mock(FilterChain.class);

        doReturn(null).when(filter).authenticate(any(HttpServletRequest.class));

        filter.doFilter(req, res, chain);

        assertNull(SecurityContextHolder.getContext().getAuthentication());
    }

    @Test
    void testIsProxyEnabled_defaultFalse() {
        PropertiesUtil.getPropertiesMap().remove("ranger.authentication.allow.trustedproxy");
        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();
        assertFalse(filter.isProxyEnabled());
    }

    @Test
    void testIsProxyEnabled_trueWhenConfigured() {
        PropertiesUtil.getPropertiesMap().put("ranger.authentication.allow.trustedproxy", "true");
        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();
        assertTrue(filter.isProxyEnabled());
        PropertiesUtil.getPropertiesMap().remove("ranger.authentication.allow.trustedproxy");
    }

    @Test
    void testAuthorizeProxyUser_returnsFalseWhenNoProxyConfigLoaded() {
        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();
        // no proxyuser config loaded into ProxyUsers -> should fail safely
        assertFalse(filter.authorizeProxyUser("knoxui", "admin", "10.0.0.1"));
    }

    @Test
    void testGetProxyuserConfiguration_copiesOnlyProxyuserKeys() throws Exception {
        // Arrange: put both proxyuser keys and non-proxyuser keys
        PropertiesUtil.getPropertiesMap().put("ranger.proxyuser.knoxui.hosts", "*");
        PropertiesUtil.getPropertiesMap().put("ranger.proxyuser.knoxui.groups", "*");
        PropertiesUtil.getPropertiesMap().put("ranger.some.other.key", "shouldNotBeCopied");

        RangerJwtAuthFilter filter = new RangerJwtAuthFilter();

        // Call private getProxyuserConfiguration() via reflection
        Method m = RangerJwtAuthFilter.class.getDeclaredMethod("getProxyuserConfiguration");
        m.setAccessible(true);

        Configuration conf = (Configuration) m.invoke(filter);

        // Assert: proxyuser keys copied
        assertEquals("*", conf.get("ranger.proxyuser.knoxui.hosts"));
        assertEquals("*", conf.get("ranger.proxyuser.knoxui.groups"));

        // Assert: non-proxyuser keys NOT copied
        assertNull(conf.get("ranger.some.other.key"));

        // Cleanup
        PropertiesUtil.getPropertiesMap().remove("ranger.proxyuser.knoxui.hosts");
        PropertiesUtil.getPropertiesMap().remove("ranger.proxyuser.knoxui.groups");
        PropertiesUtil.getPropertiesMap().remove("ranger.some.other.key");
    }
}
