/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ranger.plugin.util;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.script.ScriptEngine;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
* @generated by Cursor
* @description <Unit Test for JavaScriptEngineCreator class>
*/
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestJavaScriptEngineCreator {
    @Test
    public void test01_getScriptEngine_withNullClassLoader_returnsGracefully() {
        JavaScriptEngineCreator creator = new JavaScriptEngineCreator();
        ScriptEngine engine = creator.getScriptEngine(null);
        // engine may be null on JDKs without JavaScript engine; ensure no exception and
        // type if present
        assertTrue(engine == null || engine.getFactory() != null);
    }

    @Test
    public void test02_getScriptEngine_withCustomClassLoader_returnsGracefully() {
        ClassLoader cl = this.getClass().getClassLoader();
        JavaScriptEngineCreator creator = new JavaScriptEngineCreator();
        ScriptEngine engine = creator.getScriptEngine(cl);
        assertTrue(engine == null || engine.getFactory() != null);
    }
}
