/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.authz.api;

import org.apache.ranger.authz.model.RangerAccessContext;
import org.apache.ranger.authz.model.RangerAccessInfo;
import org.apache.ranger.authz.model.RangerAuthzRequest;
import org.apache.ranger.authz.model.RangerAuthzResult;
import org.apache.ranger.authz.model.RangerMultiAuthzRequest;
import org.apache.ranger.authz.model.RangerMultiAuthzResult;
import org.apache.ranger.authz.model.RangerResourceInfo;
import org.apache.ranger.authz.model.RangerResourcePermissions;
import org.apache.ranger.authz.model.RangerResourcePermissionsRequest;
import org.apache.ranger.authz.model.RangerUserInfo;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.Collections;
import java.util.Properties;

import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_ACCESS_CONTEXT_MISSING;
import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_ACCESS_INFO_MISSING;
import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_NAME_MATCH_SCOPE_INVALID;
import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_PERMISSIONS_EMPTY;
import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_RESOURCE_INFO_MISSING;
import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_RESOURCE_NAME_MISSING;
import static org.apache.ranger.authz.api.RangerAuthzApiErrorCode.INVALID_REQUEST_USER_INFO_MISSING;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerAuthorizer
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestRangerAuthorizer {
    @Test
    void validateRequest_positive_fullValidRequestPasses() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo      user     = new RangerUserInfo("alice");
        RangerResourceInfo  resource = new RangerResourceInfo("db:table", null, null, null);
        RangerAccessInfo    access   = new RangerAccessInfo(resource, null, Collections.singleton("read"));
        RangerAccessContext context  = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request  = new RangerAuthzRequest("r1", user, access, context);

        assertDoesNotThrow(() -> probe.validateAuthzRequest(request));
    }

    @Test
    void validateRequest_negative_missingUserThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerResourceInfo  resource = new RangerResourceInfo("db:table", null, null, null);
        RangerAccessInfo    access   = new RangerAccessInfo(resource, null, Collections.singleton("read"));
        RangerAccessContext context  = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request  = new RangerAuthzRequest("r1", null, access, context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateAuthzRequest(request));

        assertEquals(INVALID_REQUEST_USER_INFO_MISSING.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateRequest_negative_nullAccessThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo      user    = new RangerUserInfo("alice");
        RangerAccessContext context = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request = new RangerAuthzRequest("r1", user, null, context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateAuthzRequest(request));

        assertEquals(INVALID_REQUEST_ACCESS_INFO_MISSING.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateRequest_negative_emptyPermissionsThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo      user     = new RangerUserInfo("alice");
        RangerResourceInfo  resource = new RangerResourceInfo("db:table", null, null, null);
        RangerAccessInfo    access   = new RangerAccessInfo(resource, null, Collections.emptySet());
        RangerAccessContext context  = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request  = new RangerAuthzRequest("r1", user, access, context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateAuthzRequest(request));

        assertEquals(INVALID_REQUEST_PERMISSIONS_EMPTY.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateRequest_negative_missingResourceNameThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo      user     = new RangerUserInfo("alice");
        RangerResourceInfo  resource = new RangerResourceInfo("", null, null, null);
        RangerAccessInfo    access   = new RangerAccessInfo(resource, null, Collections.singleton("read"));
        RangerAccessContext context  = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request  = new RangerAuthzRequest("r1", user, access, context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateAuthzRequest(request));

        assertEquals(INVALID_REQUEST_RESOURCE_NAME_MISSING.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateRequest_negative_nullContextThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo     user     = new RangerUserInfo("alice");
        RangerResourceInfo resource = new RangerResourceInfo("db:table", null, null, null);
        RangerAccessInfo   access   = new RangerAccessInfo(resource, null, Collections.singleton("read"));
        RangerAuthzRequest request  = new RangerAuthzRequest("r1", user, access, null);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateAuthzRequest(request));

        assertEquals(INVALID_REQUEST_ACCESS_CONTEXT_MISSING.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateMultiAuthzRequest_negative_emptyAccessesListThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo          user    = new RangerUserInfo("alice");
        RangerAccessContext     context = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerMultiAuthzRequest request = new RangerMultiAuthzRequest("m1", user, Collections.emptyList(), context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateMultiAuthzRequest(request));

        assertEquals(INVALID_REQUEST_ACCESS_INFO_MISSING.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateResourcePermissionsRequest_negative_nullResourceThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerAccessContext              context = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerResourcePermissionsRequest request = new RangerResourcePermissionsRequest("p1", null, context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateResourcePermissionsRequest(request));

        assertEquals(INVALID_REQUEST_RESOURCE_INFO_MISSING.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateResourceInfo_negative_invalidNameMatchScopeWithSubResourcesThrows() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo user = new RangerUserInfo("alice");
        RangerResourceInfo resource = new RangerResourceInfo(
                "db:table",
                Collections.singleton("child"),
                RangerResourceInfo.ResourceMatchScope.SELF_OR_ANY_DESCENDANT,
                null);
        RangerAccessInfo    access  = new RangerAccessInfo(resource, null, Collections.singleton("read"));
        RangerAccessContext context = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request = new RangerAuthzRequest("r1", user, access, context);

        RangerAuthzException thrown = assertThrows(RangerAuthzException.class, () -> probe.validateAuthzRequest(request));

        assertEquals(INVALID_REQUEST_NAME_MATCH_SCOPE_INVALID.getCode(), thrown.getErrorCode().getCode());
    }

    @Test
    void validateMultiAuthzRequest_positive_multipleAccessesNormalizesContext() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo      user      = new RangerUserInfo("alice");
        RangerResourceInfo  resource1 = new RangerResourceInfo("db:t1", null, null, null);
        RangerAccessInfo    access1   = new RangerAccessInfo(resource1, null, Collections.singleton("read"));
        RangerResourceInfo  resource2 = new RangerResourceInfo("db:t2", null, null, null);
        RangerAccessInfo    access2   = new RangerAccessInfo(resource2, null, Collections.singleton("write"));
        RangerAccessContext context   = new RangerAccessContext("hive", "svc", 1L, null, null, null);

        context.setAccessTime(0L);
        context.setAdditionalInfo(null);

        RangerMultiAuthzRequest request = new RangerMultiAuthzRequest("m1", user, Arrays.asList(access1, access2), context);

        assertDoesNotThrow(() -> probe.validateMultiAuthzRequest(request));
        assertTrue(request.getContext().getAccessTime() > 0L);
        assertNotNull(request.getContext().getAdditionalInfo());
    }

    @Test
    void validateResourcePermissionsRequest_positive_validPasses() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerResourceInfo               resource = new RangerResourceInfo("name", null, null, null);
        RangerAccessContext              context  = new RangerAccessContext("hive", "svc", 50L, null, null, Collections.singletonMap("k", 1));
        RangerResourcePermissionsRequest request  = new RangerResourcePermissionsRequest("p2", resource, context);

        assertDoesNotThrow(() -> probe.validateResourcePermissionsRequest(request));
    }

    @Test
    void validateRequest_positive_selfScopeWithSubresourcesPasses() {
        ValidationProbe probe = new ValidationProbe(new Properties());

        RangerUserInfo user = new RangerUserInfo("alice");
        RangerResourceInfo resource = new RangerResourceInfo(
                "db:table",
                Collections.singleton("child"),
                RangerResourceInfo.ResourceMatchScope.SELF,
                null);
        RangerAccessInfo    access  = new RangerAccessInfo(resource, null, Collections.singleton("read"));
        RangerAccessContext context = new RangerAccessContext("hive", "svc", 1L, null, null, null);
        RangerAuthzRequest  request = new RangerAuthzRequest("r1", user, access, context);

        assertDoesNotThrow(() -> probe.validateAuthzRequest(request));
    }

    /**
     * Local subclass exposing {@link RangerAuthorizer} protected validation helpers for these tests.
     */
    private static final class ValidationProbe extends RangerAuthorizer {
        private ValidationProbe(Properties properties) {
            super(properties);
        }

        @Override
        public void init() throws RangerAuthzException {
        }

        @Override
        public void close() throws RangerAuthzException {
        }

        @Override
        public RangerAuthzResult authorize(RangerAuthzRequest request) throws RangerAuthzException {
            return null;
        }

        @Override
        public RangerMultiAuthzResult authorize(RangerMultiAuthzRequest request) throws RangerAuthzException {
            return null;
        }

        @Override
        public RangerResourcePermissions getResourcePermissions(RangerResourcePermissionsRequest request) throws RangerAuthzException {
            return null;
        }

        void validateAuthzRequest(RangerAuthzRequest request) throws RangerAuthzException {
            validateRequest(request);
        }

        void validateMultiAuthzRequest(RangerMultiAuthzRequest request) throws RangerAuthzException {
            validateRequest(request);
        }

        void validateResourcePermissionsRequest(RangerResourcePermissionsRequest request) throws RangerAuthzException {
            validateRequest(request);
        }
    }
}
