#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

INSTALL_BASE=/usr/bin

MOD_NAME=ranger-usersync

MOD_DIR=${INSTALL_BASE}/${MOD_NAME}

if [ -L ${MOD_DIR} ]
then
	case $1 in
	start)
		cd ${MOD_DIR} ; ./start.sh
		;;
	stop)
		cd ${MOD_DIR} ; ./stop.sh
		;;
	*)
		echo "Invalid argument [$1]; Only start|stop are supported."
		exit 1
	esac
fi
