#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### BEGIN INIT INFO
# Provides:        ranger-usersync
# Required-Start:  $local_fs $remote_fs $network $named $syslog $time
# Required-Stop:   $local_fs $remote_fs $network $named $syslog $time
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start/Stop Ranger Usersync
### END INIT INFO

BIN_PATH=/usr/bin
MOD_NAME=ranger-usersync

case $1 in
	start)
		${BIN_PATH}/${MOD_NAME} start
		;;
	stop)
		${BIN_PATH}/${MOD_NAME} stop
		;;
	restart)
		echo "Stopping Apache Ranger Usersync."
		${BIN_PATH}/${MOD_NAME} stop
		echo "Starting Apache Ranger Usersync."
		${BIN_PATH}/${MOD_NAME} start
		;;
	*)
		echo "Invalid argument [$1]; Only start | stop | restart, are supported."
		exit 1
	esac
