#!/usr/bin/env python3

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Renders conf/ranger-audit-ingestor-site.xml from configs/ranger-audit-ingestor-site.yaml and env
# variables, the same way dba.py prepares Ranger Admin. A mounted configs/ranger-audit-ingestor-site.xml
# is copied as it is instead; nothing is rendered over it.

import logging
import os
import shutil
import sys
import xml.etree.ElementTree as ET

import yaml

AUDIT_INGESTOR_DIR = os.environ.get('AUDIT_INGESTOR_HOME_DIR', '/opt/ranger/audit-ingestor')
CONF_DIR           = os.environ.get('AUDIT_INGESTOR_CONF_DIR', os.path.join(AUDIT_INGESTOR_DIR, 'conf'))
CONFIGS_DIR        = os.environ.get('AUDIT_INGESTOR_CONFIGS', os.path.join(AUDIT_INGESTOR_DIR, 'configs'))
SITE_XML_NAME      = 'ranger-audit-ingestor-site.xml'
SITE_YAML_NAME     = 'ranger-audit-ingestor-site.yaml'
PREFIX             = 'ranger.audit.ingestor.'

# env variable -> property; an empty KAFKA_SASL_MECHANISM or OAUTHBEARER leaves the code default in place
ENV_OVERRIDES = {
    'KAFKA_BOOTSTRAP_SERVERS': PREFIX + 'kafka.bootstrap.servers',
    'KAFKA_SASL_MECHANISM':    PREFIX + 'kafka.sasl.mechanism',
}

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s audit-ingestor-config: %(message)s')
LOG = logging.getLogger('audit-ingestor-config')


def to_property_value(value):
    if isinstance(value, bool):
        return str(value).lower()

    return '' if value is None else str(value)


def render_site_xml():
    site_xml  = os.path.join(CONFIGS_DIR, SITE_XML_NAME)
    site_yaml = os.path.join(CONFIGS_DIR, SITE_YAML_NAME)
    target    = os.path.join(CONF_DIR, SITE_XML_NAME)

    if os.path.isfile(site_xml):
        shutil.copyfile(site_xml, target)
        LOG.info(f'Using {site_xml} as it is, conf/{SITE_XML_NAME} is not rendered from YAML')

        return

    if not os.path.isfile(site_yaml):
        raise FileNotFoundError(f'configuration not found: neither {site_xml} nor {site_yaml} exists')

    with open(site_yaml) as f:
        config = yaml.safe_load(f) or {}

    if not isinstance(config, dict) or any(isinstance(value, (dict, list)) for value in config.values()):
        raise ValueError(f'{site_yaml} must be a flat map of property names to values')

    props = {str(name): to_property_value(value) for name, value in config.items()}

    for env_name, prop_name in ENV_OVERRIDES.items():
        value = os.environ.get(env_name, '').strip()

        if env_name == 'KAFKA_SASL_MECHANISM' and value.upper() == 'OAUTHBEARER':
            value = ''

        if value or env_name == 'KAFKA_SASL_MECHANISM' and env_name in os.environ:
            props[prop_name] = value
            LOG.info(f"{prop_name}: '{value}' (from env {env_name})")

    root = ET.Element('configuration')

    root.append(ET.Comment(f' generated by audit-ingestor-config.py from {SITE_YAML_NAME} '))

    for name, value in props.items():
        prop = ET.SubElement(root, 'property')

        ET.SubElement(prop, 'name').text  = name
        ET.SubElement(prop, 'value').text = value

    ET.indent(root)
    os.makedirs(CONF_DIR, exist_ok=True)
    ET.ElementTree(root).write(target, encoding='utf-8', xml_declaration=True)

    LOG.info(f'Rendered {target} with {len(props)} properties from {site_yaml}')


if __name__ == '__main__':
    try:
        render_site_xml()
    except (OSError, ValueError, ET.ParseError, yaml.YAMLError) as err:
        LOG.error(f'{err}')
        sys.exit(1)
