/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.sizing;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for PerfMemTimeTracker
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestPerfMemTimeTracker {
    @Test
    public void test01_constructor_negative_timeTakenNegativeBeforeStop() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("preStop");

        assertTrue(tracker.getTimeTaken() < 0);
    }

    @Test
    public void test02_constructor_positive_exposesStableTagAndStartMarkers() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("tagged");

        assertEquals("tagged", tracker.getTag());
        assertTrue(tracker.getStartTime() >= 0);
        assertTrue(tracker.getGcTime() >= 0);
    }

    @Test
    public void test03_stop_negative_memoryDeltaInvalidBeforeStopFinalizesMemoryRead() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("open");

        assertTrue(tracker.getEndTime() == 0L);
        assertTrue(tracker.getMemoryDelta() <= 0);
    }

    @Test
    public void test04_stop_positive_recordsNonNegativeElapsedAndMemoryDeltaAfterStop() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("closed");

        tracker.stop();

        assertTrue(tracker.getEndTime() >= tracker.getStartTime());
        assertTrue(tracker.getEndMemory() >= 0);
        assertTrue(tracker.getTimeTaken() >= 0);
    }

    @Test
    public void test05_addChild_negative_reportsNullChildrenInitially() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("solo");

        assertNull(tracker.getChildren());
    }

    @Test
    public void test06_addChild_positive_nestedTotalGcCombinesBothTrackers() {
        PerfMemTimeTracker parent = new PerfMemTimeTracker("parent");
        PerfMemTimeTracker child  = new PerfMemTimeTracker("child");

        child.stop();
        parent.addChild(child);
        parent.stop();

        assertNotNull(parent.getChildren());
        assertTrue(parent.getChildren().contains(child));
        assertTrue(parent.getTotalGcTime() >= child.getTotalGcTime());
    }

    @Test
    public void test07_print_negative_headerSuppressedProducesSingleDataLineMinimum() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("plain");
        tracker.stop();

        ByteArrayOutputStream buffer = new ByteArrayOutputStream();

        try (PrintStream printStream = new PrintStream(buffer, true)) {
            tracker.print(printStream, false);
        }

        String rendered = new String(buffer.toByteArray(), StandardCharsets.UTF_8);
        assertTrue(rendered.contains(PerfMemTimeTracker.STR_FIELD_SEP));
        assertTrue(rendered.contains("plain"));
    }

    @Test
    public void test08_print_positive_headerIncludesColumnTitles() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("withHeader");
        tracker.stop();

        ByteArrayOutputStream buffer = new ByteArrayOutputStream();

        try (PrintStream printStream = new PrintStream(buffer, true)) {
            tracker.print(printStream, true);
        }

        String rendered = new String(buffer.toByteArray(), StandardCharsets.UTF_8);
        assertTrue(rendered.contains("Task|Time (ms)|Memory (bytes)"));
        assertTrue(rendered.contains("withHeader"));
    }

    @Test
    public void test09_toString_negative_doesNotThrowBeforeStop() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("unset");

        String description = tracker.toString();

        assertTrue(description.startsWith("unset"));
    }

    @Test
    public void test10_toString_positive_includesTimingAfterStopCompletes() {
        PerfMemTimeTracker tracker = new PerfMemTimeTracker("ready");
        tracker.stop();

        assertTrue(tracker.toString().contains("TimeTaken"));
    }
}
