/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.services.ozone;

import org.apache.ranger.plugin.model.RangerPolicy;
import org.apache.ranger.plugin.model.RangerService;
import org.apache.ranger.plugin.model.RangerServiceDef;
import org.apache.ranger.plugin.policyengine.RangerPolicyEngine;
import org.apache.ranger.plugin.service.RangerBaseService;
import org.apache.ranger.plugin.service.ResourceLookupContext;
import org.apache.ranger.plugin.store.EmbeddedServiceDefsUtil;
import org.apache.ranger.services.ozone.client.OzoneResourceMgr;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyMap;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.same;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.never;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerServiceOzone
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestRangerServiceOzone {
    private static final String CREATE_DEFAULT_POLICY_PER_HIERARCHY = "create.default.policy.per.hierarchy";

    @Test
    void test01_init_whenServiceProvided_setsIdentifiers() throws Exception {
        RangerServiceOzone ozone = new RangerServiceOzone();
        RangerServiceDef def = EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_OZONE_NAME);

        assertNotNull(def);

        Map<String, String> cfg     = sampleServiceConfigs();
        RangerService       service = buildService("svc-ozone", "ozone", cfg);

        ozone.init(def, service);

        assertEquals(def, ozone.getServiceDef());
        assertEquals(service, ozone.getService());
        assertEquals(cfg, ozone.getConfigs());
        assertEquals("svc-ozone", ozone.getServiceName());
        assertEquals("ozone", ozone.getServiceType());
    }

    @Test
    void test02_init_whenServiceIsNull_throwsNullPointerException() throws Exception {
        RangerServiceOzone ozone = new RangerServiceOzone();
        RangerServiceDef def   = EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_OZONE_NAME);

        assertNotNull(def);
        assertThrows(NullPointerException.class, () -> ozone.init(def, null));
    }

    @Test
    void test03_validateConfig_whenConfigsAbsent_returnsEmptyResponse() throws Exception {
        RangerServiceOzone ozone = initOzone(sampleServiceConfigs());
        ozone.setConfigs(null);

        Map<String, Object> out = ozone.validateConfig();

        assertNotNull(out);
        assertTrue(out.isEmpty());
    }

    @Test
    void test04_validateConfig_whenConfigsAvailable_delegatesToOzoneResourceMgr() throws Exception {
        RangerServiceOzone ozone    = initOzone(sampleServiceConfigs());
        Map<String, Object> expected = Collections.singletonMap("connectivityStatus", Boolean.TRUE);

        try (MockedStatic<OzoneResourceMgr> mocked = mockStatic(OzoneResourceMgr.class)) {
            mocked.when(() -> OzoneResourceMgr.connectionTest(eq("ozone-svc"), anyMap())).thenReturn(expected);

            Map<String, Object> actual = ozone.validateConfig();

            assertSame(expected, actual);
            mocked.verify(() -> OzoneResourceMgr.connectionTest(eq("ozone-svc"), anyMap()));
        }
    }

    @Test
    void test05_lookupResource_whenContextIsNull_returnsEmptyList() throws Exception {
        RangerServiceOzone ozone = initOzoneForLookup(sampleServiceConfigs());

        try (MockedStatic<OzoneResourceMgr> mocked = mockStatic(OzoneResourceMgr.class)) {
            List<String> result = ozone.lookupResource(null);

            assertEquals(Collections.emptyList(), result);

            mocked.verify(() -> OzoneResourceMgr.getOzoneResources(anyString(), anyString(), anyMap(), any()),
                    never());
        }
    }

    @Test
    void test06_lookupResource_whenContextPresent_delegatesToOzoneResourceMgr() throws Exception {
        RangerServiceOzone    ozone       = initOzoneForLookup(sampleServiceConfigs());
        ResourceLookupContext ctx         = sampleLookupContext();
        List<String> expected = Arrays.asList("/a", "/b");

        try (MockedStatic<OzoneResourceMgr> mocked = mockStatic(OzoneResourceMgr.class)) {
            mocked.when(() -> OzoneResourceMgr.getOzoneResources(eq("svc-lookup"), eq("ozone"), anyMap(), same(ctx))).thenReturn(expected);

            List<String> result = ozone.lookupResource(ctx);

            assertSame(expected, result);
        }
    }

    @Test
    void test07_getDefaultRangerPolicies_addsOwnerGrantForPoliciesNamedAll() throws Exception {
        RangerServiceOzone ozone = new RangerServiceOzone();
        RangerServiceDef   def   = EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_OZONE_NAME);

        ozone.init(def, buildService("def-svc", "ozone", defaultPolicyConfigs()));

        List<RangerPolicy> policies = ozone.getDefaultRangerPolicies();

        assertFalse(policies.isEmpty());

        boolean foundExtended = policies.stream().anyMatch(p ->
                p.getName() != null
                        && p.getName().startsWith("all")
                        && p.getPolicyItems().stream().anyMatch(pi ->
                                pi.getUsers() != null && pi.getUsers().contains(RangerPolicyEngine.RESOURCE_OWNER)));

        assertTrue(foundExtended);
    }

    @Test
    void test08_getDefaultRangerPolicies_whenLookupUserPresent_addsDedicatedPolicyItems() throws Exception {
        RangerServiceOzone ozone = new RangerServiceOzone();

        Field lookUpField = RangerBaseService.class.getDeclaredField("lookUpUser");
        lookUpField.setAccessible(true);
        lookUpField.set(ozone, "resolver-user");

        RangerServiceDef def = EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_OZONE_NAME);
        ozone.init(def, buildService("def-svc-2", "ozone", defaultPolicyConfigs()));

        List<RangerPolicy> policies = ozone.getDefaultRangerPolicies();

        Set<String> allPolicyNames = new HashSet<>();
        for (RangerPolicy p : policies) {
            if (p.getName() != null && p.getName().startsWith("all")) {
                boolean hasLookup = p.getPolicyItems().stream().anyMatch(pi ->
                        pi.getUsers() != null && pi.getUsers().contains("resolver-user"));
                assertTrue(hasLookup, "expected lookup user grants on policy " + p.getName());
                allPolicyNames.add(p.getName());
            }
        }

        assertFalse(allPolicyNames.isEmpty());
    }

    private RangerServiceOzone initOzone(Map<String, String> cfg) throws Exception {
        RangerServiceOzone svc = new RangerServiceOzone();

        RangerServiceDef def = EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_OZONE_NAME);
        assertNotNull(def);

        svc.init(def, buildService("ozone-svc", "ozone", cfg));
        return svc;
    }

    private RangerServiceOzone initOzoneForLookup(Map<String, String> cfg) throws Exception {
        RangerServiceOzone svc = new RangerServiceOzone();

        RangerServiceDef def = EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(EmbeddedServiceDefsUtil.EMBEDDED_SERVICEDEF_OZONE_NAME);
        assertNotNull(def);

        svc.init(def, buildService("svc-lookup", "ozone", cfg));
        return svc;
    }

    private RangerService buildService(String name, String type, Map<String, String> cfg) {
        RangerService service = new RangerService();
        service.setName(name);
        service.setType(type);
        service.setConfigs(cfg);
        return service;
    }

    private Map<String, String> sampleServiceConfigs() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("username", "u");
        cfg.put("password", "p");
        cfg.put("ozone.om.http-address", "localhost:9862");
        return cfg;
    }

    private ResourceLookupContext sampleLookupContext() {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("volume-a");
        ctx.setResourceName("volume");
        return ctx;
    }

    private Map<String, String> defaultPolicyConfigs() {
        Map<String, String> cfg = sampleServiceConfigs();
        cfg.put("setup.additional.default.policies", "false");
        cfg.put(CREATE_DEFAULT_POLICY_PER_HIERARCHY, Boolean.TRUE.toString());
        return cfg;
    }
}
