#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

POLICYMGR_HOME=/usr/lib/xapolicymgr
export POLICYMGR_HOME

case $1 in
start)
	/bin/su --login  xasecure "${POLICYMGR_HOME}/startpolicymgr.sh"
	;;
stop)
	/bin/su --login  xasecure "${POLICYMGR_HOME}/stoppolicymgr.sh"
    ;;
restart)
	/bin/su --login  xasecure "${POLICYMGR_HOME}/stoppolicymgr.sh"  && sleep 30
	/bin/su --login  xasecure "${POLICYMGR_HOME}/startpolicymgr.sh"

	;;
*)
	echo "Invalid argument [$1]; Only start|stop|restart are supported."
    exit 1
esac
