/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.ranger.security.web.authentication;

import org.apache.ranger.common.JSONUtil;
import org.apache.ranger.view.VXResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.Authentication;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.io.PrintWriter;
import java.io.StringWriter;

import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
* @generated by Cursor
* @description <Unit Test for TestCustomLogoutSuccessHandler class>
*/
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestCustomLogoutSuccessHandler {
    @InjectMocks
    private CustomLogoutSuccessHandler handler = new CustomLogoutSuccessHandler();

    @Mock
    private JSONUtil jsonUtil;
    @Mock
    private HttpServletRequest  request;
    @Mock
    private HttpServletResponse response;
    @Mock
    private Authentication      authentication;
    @Mock
    private ServletContext      servletContext;

    private StringWriter responseBuffer;

    @BeforeEach
    public void setup() throws Exception {
        responseBuffer = new StringWriter();
        when(response.getWriter()).thenReturn(new PrintWriter(responseBuffer));
        when(jsonUtil.writeObjectAsString(any(VXResponse.class))).thenReturn("{\"statusCode\":200}");
        when(request.getServletContext()).thenReturn(servletContext);
        when(request.getRequestedSessionId()).thenReturn("sid");
    }

    @Test
    public void testOnLogoutSuccess_removesServletContextAttribute_andWritesJson() throws Exception {
        handler.onLogoutSuccess(request, response, authentication);

        verify(servletContext).removeAttribute("sid");
        verify(response).setStatus(HttpServletResponse.SC_OK);
        assertThat(responseBuffer.toString(), containsString("200"));
    }
}
