/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.ranger.services.kudu;

import org.apache.ranger.plugin.service.ResourceLookupContext;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.HashMap;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerServiceKudu
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestRangerServiceKudu {
    @Mock
    private ResourceLookupContext resourceLookupContext;

    @Test
    void testLookupResource_negative_nullContextReturnsEmptyList() throws Exception {
        RangerServiceKudu subject = new RangerServiceKudu();

        List<String> result = subject.lookupResource(null);

        assertNotNull(result);
        assertTrue(result.isEmpty());
    }

    @Test
    void testLookupResource_positive_nonNullContextReturnsEmptyList() throws Exception {
        RangerServiceKudu subject = new RangerServiceKudu();

        List<String> result = subject.lookupResource(resourceLookupContext);

        assertNotNull(result);
        assertTrue(result.isEmpty());
    }

    @Test
    void testValidateConfig_negative_distinctInstancePerCall() throws Exception {
        RangerServiceKudu subject = new RangerServiceKudu();

        HashMap<String, Object> first = subject.validateConfig();
        HashMap<String, Object> second = subject.validateConfig();

        assertNotNull(first);
        assertNotNull(second);
        assertNotSame(second, first);
    }

    @Test
    void testValidateConfig_positive_returnsNonNullEmptyMap() throws Exception {
        RangerServiceKudu subject = new RangerServiceKudu();

        HashMap<String, Object> result = subject.validateConfig();

        assertNotNull(result);
        assertTrue(result.isEmpty());
    }
}
