/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.services.ozone.client;

import org.apache.ranger.plugin.client.HadoopException;
import org.apache.ranger.plugin.service.ResourceLookupContext;
import org.apache.ranger.plugin.util.TimedEventUtil;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedConstruction;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @generated by Cursor
 * @description : Unit Test cases for OzoneResourceMgr
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestOzoneResourceMgr {
    @Test
    void test01_connectionTest_whenOzoneClientOk_returnsMap() throws Exception {
        Map<String, String> cfg      = new HashMap<>();
        cfg.put("ozone.om.service.ids", "ozone1");
        Map<String, Object> expected = Collections.singletonMap("connectivityStatus", Boolean.TRUE);

        try (MockedStatic<OzoneClient> mocked = Mockito.mockStatic(OzoneClient.class)) {
            mocked.when(() -> OzoneClient.connectionTest(Mockito.eq("svc"), Mockito.eq(cfg))).thenReturn(expected);

            Map<String, Object> result = OzoneResourceMgr.connectionTest("svc", cfg);

            assertSame(expected, result);
            mocked.verify(() -> OzoneClient.connectionTest(Mockito.eq("svc"), Mockito.eq(cfg)));
        }
    }

    @Test
    void test02_connectionTest_whenOzoneClientThrowsPropagatesHadoopException() {
        Map<String, String> cfg        = new HashMap<>();
        HadoopException     hadoopFail = new HadoopException("boom", new RuntimeException("root"));

        try (MockedStatic<OzoneClient> mocked = Mockito.mockStatic(OzoneClient.class)) {
            mocked.when(() -> OzoneClient.connectionTest(Mockito.eq("svc"), Mockito.eq(cfg))).thenThrow(hadoopFail);

            assertThrows(HadoopException.class, () -> OzoneResourceMgr.connectionTest("svc", cfg));
        }
    }

    @Test
    void test03_connectionTest_whenUncheckedException_propagates() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("k", "v");
        IllegalStateException fail = new IllegalStateException("not-hadoop");

        try (MockedStatic<OzoneClient> mocked = Mockito.mockStatic(OzoneClient.class)) {
            mocked.when(() -> OzoneClient.connectionTest(Mockito.eq("svc"), Mockito.eq(cfg))).thenThrow(fail);

            assertThrows(IllegalStateException.class, () -> OzoneResourceMgr.connectionTest("svc", cfg));
        }
    }

    @Test
    void test04_getOzoneResources_whenBucketPrefix_resolvesViaTimedTask() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("bpre");
        ctx.setResourceName("bucket");
        ctx.setResources(Collections.singletonMap("volume", Collections.singletonList("v1")));

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);
        List<String>        want   = Arrays.asList("b-a", "b-b");
        Mockito.when(client.getBucketList(Mockito.eq("bpre"), Mockito.eq(Collections.singletonList("v1")))).thenReturn(want);

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            assertEquals(want, OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test05_getOzoneResources_whenKeyPrefix_resolvesViaTimedTask() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("kpre");
        ctx.setResourceName("key");

        Map<String, List<String>> res = new HashMap<>();
        res.put("volume", Collections.singletonList("v1"));
        res.put("bucket", Collections.singletonList("b1"));
        ctx.setResources(res);

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);
        Mockito.when(client.getKeyList(Mockito.eq("kpre"), Mockito.eq(Collections.singletonList("v1")),
                        Mockito.eq(Collections.singletonList("b1")))).thenReturn(Collections.singletonList("k1"));

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            assertEquals(Collections.singletonList("k1"), OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test06_getOzoneResources_whenResourceUnknown_doesNotScheduleCallable() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("x");
        ctx.setResourceName("unknown");

        Map<String, String> cfg = new HashMap<>();

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.anyString(), Mockito.anyString(), Mockito.anyMap()))
                                .thenReturn(Mockito.mock(OzoneClient.class)))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.anyLong(), Mockito.any(TimeUnit.class)))
                    .thenThrow(new AssertionError("timedTask should not run"));

            assertNull(OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test07_getOzoneResources_whenResourceNameTrimmedNormalizesCase() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("vp");
        ctx.setResourceName("  VOLUME  ");

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);
        Mockito.when(client.getVolumeList(Mockito.eq("vp"))).thenReturn(Collections.singletonList("only"));

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            assertEquals(Collections.singletonList("only"), OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test08_getOzoneResources_whenServiceNameNull_returnsNull() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("vol");
        ctx.setResourceName("volume");

        Map<String, String> cfg = new HashMap<>();

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class)) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.anyLong(), Mockito.any(TimeUnit.class)))
                    .thenThrow(new AssertionError("timedTask should not run"));

            assertNull(OzoneResourceMgr.getOzoneResources(null, "ozone", cfg, ctx));
        }
    }

    @Test
    void test09_getOzoneResources_whenUserInputNull_returnsNull() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput(null);
        ctx.setResourceName("volume");

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class)) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.anyLong(), Mockito.any(TimeUnit.class)))
                    .thenThrow(new AssertionError("timedTask should not run"));

            assertNull(OzoneResourceMgr.getOzoneResources("svc", "ozone", new HashMap<>(), ctx));
        }
    }

    @Test
    void test10_getOzoneResources_whenUserInputEmptyOnVolume_noCallable() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("");
        ctx.setResourceName("volume");

        Map<String, String> cfg = new HashMap<>();

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg)))
                                .thenReturn(Mockito.mock(OzoneClient.class)))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.anyLong(), Mockito.any(TimeUnit.class)))
                    .thenThrow(new AssertionError("timedTask should not run"));

            assertNull(OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test11_getOzoneResources_whenOzoneClientNull_returnsNull() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("vol");
        ctx.setResourceName("volume");

        Map<String, String> cfg = new HashMap<>();

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.anyString(), Mockito.anyString(), Mockito.anyMap())).thenReturn(null))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.anyLong(), Mockito.any(TimeUnit.class)))
                    .thenThrow(new AssertionError("timedTask should not run"));

            assertNull(OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test12_getOzoneResources_whenTimedTaskThrows_propagates() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("v");
        ctx.setResourceName("volume");

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS)))
                    .thenThrow(new IllegalStateException("timed-fail"));

            assertThrows(IllegalStateException.class, () -> OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test13_getOzoneResources_whenKeyCallableThrows_propagatesException() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("kpre");
        ctx.setResourceName("key");

        Map<String, List<String>> res = new HashMap<>();
        res.put("volume", Collections.singletonList("v1"));
        res.put("bucket", Collections.singletonList("b1"));
        ctx.setResources(res);

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);

        Mockito.when(client.getKeyList(Mockito.eq("kpre"), Mockito.eq(Collections.singletonList("v1")),
                        Mockito.eq(Collections.singletonList("b1")))).thenThrow(new NullPointerException("simulated"));

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            assertThrows(NullPointerException.class, () -> OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test14_getOzoneResources_whenVolumePrefix_resolvesViaTimedTask() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("vol");
        ctx.setResourceName("volume");

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);
        List<String>        want   = Arrays.asList("v1", "v2");
        Mockito.when(client.getVolumeList(Mockito.eq("vol"))).thenReturn(want);

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            List<String> out = OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx);

            assertEquals(want, out);
        }
    }

    @Test
    void test15_privateConstructor_rejectsInstantiation() throws Exception {
        Constructor<OzoneResourceMgr> ctor = OzoneResourceMgr.class.getDeclaredConstructor();
        ctor.setAccessible(true);

        InvocationTargetException ite = assertThrows(InvocationTargetException.class, ctor::newInstance);
        assertTrue(ite.getCause() instanceof UnsupportedOperationException);
    }

    @Test
    void test16_getOzoneResources_whenResourceNameNull_skipsPrefixes() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("vol");
        ctx.setResourceName(null);

        Map<String, String> cfg = new HashMap<>();

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg)))
                                .thenReturn(Mockito.mock(OzoneClient.class)))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.anyLong(), Mockito.any(TimeUnit.class)))
                    .thenThrow(new AssertionError("timedTask should not run"));

            assertNull(OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test17_getOzoneResources_whenResourceMapEmpty_skipsInheritedLists() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("buck");
        ctx.setResourceName("bucket");
        ctx.setResources(new HashMap<>());

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);
        Mockito.when(client.getBucketList(Mockito.eq("buck"), Mockito.isNull())).thenReturn(Collections.singletonList("only-b"));

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            assertEquals(Collections.singletonList("only-b"), OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }

    @Test
    void test18_getOzoneResources_whenResourceMapHasNoOzoneKeys_listsStayNull() throws Exception {
        ResourceLookupContext ctx = new ResourceLookupContext();
        ctx.setUserInput("bpre");
        ctx.setResourceName("bucket");
        ctx.setResources(Collections.singletonMap("other", Collections.singletonList("orphan")));

        Map<String, String> cfg    = new HashMap<>();
        OzoneClient         client = Mockito.mock(OzoneClient.class);
        Mockito.when(client.getBucketList(Mockito.eq("bpre"), Mockito.isNull())).thenReturn(Collections.singletonList("b2"));

        try (MockedStatic<TimedEventUtil> timed = Mockito.mockStatic(TimedEventUtil.class);
                MockedConstruction<OzoneConnectionMgr> ignored = Mockito.mockConstruction(OzoneConnectionMgr.class,
                        (mock, context) -> Mockito.when(mock.getOzoneConnection(Mockito.eq("svc"), Mockito.eq("ozone"), Mockito.eq(cfg))).thenReturn(client))) {
            timed.when(() -> TimedEventUtil.timedTask(Mockito.any(Callable.class), Mockito.eq(5L), Mockito.eq(TimeUnit.SECONDS))).then(inv -> {
                @SuppressWarnings("unchecked")
                Callable<List<String>> callable = inv.getArgument(0);

                return callable.call();
            });

            assertEquals(Collections.singletonList("b2"), OzoneResourceMgr.getOzoneResources("svc", "ozone", cfg, ctx));
        }
    }
}
