/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.services.ozone.client;

import org.apache.hadoop.hdds.conf.ConfigurationSource;
import org.apache.hadoop.ozone.client.OzoneClientFactory;
import org.apache.ranger.plugin.util.TimedEventUtil;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.security.auth.Subject;

import java.security.PrivilegedExceptionAction;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * @generated by Cursor
 * @description : Unit Test cases for OzoneConnectionMgr
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestOzoneConnectionMgr {
    /**
     * Extends manager to expose protected cache fields for assertions.
     */
    private static final class OzoneConnectionMgrHarness extends OzoneConnectionMgr {
    }

    @Test
    void test01_getOzoneConnection_whenServiceTypeNull_returnsNull() {
        OzoneConnectionMgrHarness mgr    = new OzoneConnectionMgrHarness();
        Map<String, String>       config = new HashMap<>();
        config.put("k", "v");

        assertNull(mgr.getOzoneConnection("svc", null, config));
    }

    @Test
    void test02_getOzoneConnection_whenTimedTaskReturnsClient_cachesConnection() throws Exception {
        OzoneConnectionMgrHarness mgr         = new OzoneConnectionMgrHarness();
        OzoneClient               freshClient = mock(OzoneClient.class);
        Map<String, String>       config      = new HashMap<>();
        config.put("ozone.om.service.ids", "ozone1");

        try (MockedStatic<TimedEventUtil> timed = mockStatic(TimedEventUtil.class)) {
            timed.when(() -> TimedEventUtil.timedTask(any(Callable.class), eq(5L), eq(TimeUnit.SECONDS))).thenReturn(freshClient);

            OzoneClient result = mgr.getOzoneConnection("new-svc", "ozone", config);

            assertSame(freshClient, result);
            assertSame(freshClient, mgr.ozoneConnectionCache.get("new-svc"));
            assertEquals(Boolean.TRUE, mgr.repoConnectStatusMap.get("new-svc"));
        }
    }

    @Test
    void test03_getOzoneConnection_whenConfigsNullOnMiss_logsAndReturnsNull() {
        OzoneConnectionMgrHarness mgr = new OzoneConnectionMgrHarness();

        assertNull(mgr.getOzoneConnection("svc", "ozone", null));
        assertTrue(mgr.ozoneConnectionCache.isEmpty());
    }

    @Test
    void test04_getOzoneConnection_whenTimedTaskThrows_returnsNull() throws Exception {
        OzoneConnectionMgrHarness mgr = new OzoneConnectionMgrHarness();
        Map<String, String> config = minimalConfig();

        try (MockedStatic<TimedEventUtil> timed = mockStatic(TimedEventUtil.class)) {
            timed.when(() -> TimedEventUtil.timedTask(any(Callable.class), eq(5L), eq(TimeUnit.SECONDS)))
                    .thenThrow(new IllegalStateException("connect-fail"));

            assertNull(mgr.getOzoneConnection("boom", "ozone", config));
            assertEquals(Boolean.TRUE, mgr.repoConnectStatusMap.get("boom"));
        }
    }

    @Test
    void test05_getOzoneConnection_whenPutIfAbsentReturnsExisting_closesNewborn() throws Exception {
        OzoneConnectionMgrHarness mgr    = new OzoneConnectionMgrHarness();
        OzoneClient               winner = mock(OzoneClient.class);
        OzoneClient               loser  = mock(OzoneClient.class);
        Map<String, String>       config = minimalConfig();

        try (MockedStatic<TimedEventUtil> timed = mockStatic(TimedEventUtil.class)) {
            timed.when(() -> TimedEventUtil.timedTask(any(Callable.class), eq(5L), eq(TimeUnit.SECONDS)))
                    .thenAnswer(invocation -> {
                        mgr.ozoneConnectionCache.put("svc", winner);
                        return loser;
                    });

            OzoneClient result = mgr.getOzoneConnection("svc", "ozone", config);

            assertSame(winner, result);
            verify(loser).close();
            verify(winner, never()).close();
            assertEquals(Boolean.TRUE, mgr.repoConnectStatusMap.get("svc"));
        }
    }

    @Test
    void test06_getOzoneConnection_whenCachedPingFails_reloadsConnection() throws Exception {
        OzoneConnectionMgrHarness mgr      = new OzoneConnectionMgrHarness();
        Map<String, String>       config   = minimalConfig();
        OzoneClient               stale    = mock(OzoneClient.class);
        OzoneClient               fresh    = mock(OzoneClient.class);

        when(stale.getVolumeList(isNull())).thenThrow(new IllegalStateException("stale-connection"));

        mgr.ozoneConnectionCache.put("rec", stale);

        try (MockedStatic<TimedEventUtil> timed = mockStatic(TimedEventUtil.class)) {
            timed.when(() -> TimedEventUtil.timedTask(any(Callable.class), eq(5L), eq(TimeUnit.SECONDS))).thenReturn(fresh);

            OzoneClient result = mgr.getOzoneConnection("rec", "ozone", config);

            assertSame(fresh, result);
            verify(stale).close();
            verify(stale).getVolumeList(null);
            assertSame(fresh, mgr.ozoneConnectionCache.get("rec"));
        }
    }

    @Test
    void test07_getOzoneConnection_whenCacheHitHealthy_returnsExistingClient() throws Exception {
        OzoneConnectionMgrHarness mgr    = new OzoneConnectionMgrHarness();
        Map<String, String>       config = minimalConfig();
        OzoneClient               cached = mock(OzoneClient.class);

        when(cached.getVolumeList(isNull())).thenReturn(Collections.emptyList());
        mgr.ozoneConnectionCache.put("reuse", cached);

        OzoneClient result = mgr.getOzoneConnection("reuse", "ozone", config);

        assertSame(cached, result);
        verify(cached).getVolumeList(null);
    }

    @Test
    void test08_getOzoneConnection_whenCallableBuildsClient_invokesOzoneClientConstructor() throws Exception {
        OzoneConnectionMgrHarness mgr    = new OzoneConnectionMgrHarness();
        Map<String, String>       config = minimalConfig();

        org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);

        try (MockedStatic<TimedEventUtil> timed = mockStatic(TimedEventUtil.class);
                MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            subjectStatic.when(() -> Subject.doAs(any(Subject.class), any(PrivilegedExceptionAction.class)))
                    .thenAnswer(invocation -> {
                        PrivilegedExceptionAction<?> pea = invocation.getArgument(1);
                        return pea.run();
                    });
            factoryStatic.when(() -> OzoneClientFactory.getRpcClient(anyString(), any(ConfigurationSource.class))).thenReturn(hdc);

            timed.when(() -> TimedEventUtil.timedTask(any(Callable.class), eq(5L), eq(TimeUnit.SECONDS)))
                    .thenAnswer(invocation -> {
                        @SuppressWarnings("unchecked")
                        Callable<OzoneClient> callable = invocation.getArgument(0);
                        return callable.call();
                    });

            OzoneClient result = mgr.getOzoneConnection("live", "ozone", config);

            assertNotNull(result);
            assertSame(result, mgr.ozoneConnectionCache.get("live"));
            factoryStatic.verify(() -> OzoneClientFactory.getRpcClient(anyString(), any(ConfigurationSource.class)));
        }
    }

    @Test
    void test09_getOzoneConnection_whenTimedTaskReturnsNull_butCacheFilled_usesWinner() throws Exception {
        OzoneConnectionMgrHarness mgr    = new OzoneConnectionMgrHarness();
        OzoneClient               winner = mock(OzoneClient.class);
        Map<String, String>       config = minimalConfig();

        try (MockedStatic<TimedEventUtil> timed = mockStatic(TimedEventUtil.class)) {
            timed.when(() -> TimedEventUtil.timedTask(any(Callable.class), eq(5L), eq(TimeUnit.SECONDS))).thenAnswer(
                    invocation -> {
                        mgr.ozoneConnectionCache.put("svc", winner);
                        return null;
                    });

            OzoneClient result = mgr.getOzoneConnection("svc", "ozone", config);

            assertSame(winner, result);
            verify(winner, never()).close();
            assertSame(winner, mgr.ozoneConnectionCache.get("svc"));
            assertEquals(Boolean.TRUE, mgr.repoConnectStatusMap.get("svc"));
        }
    }

    private static Map<String, String> minimalConfig() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("username", "u");
        cfg.put("password", "p");
        cfg.put("hadoop.security.authentication", "simple");
        cfg.put("ozone.om.service.ids", "ozone1");
        return cfg;
    }
}
