/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.services.ozone.client;

import org.apache.hadoop.hdds.conf.ConfigurationSource;
import org.apache.hadoop.ozone.client.ObjectStore;
import org.apache.hadoop.ozone.client.OzoneBucket;
import org.apache.hadoop.ozone.client.OzoneClientFactory;
import org.apache.hadoop.ozone.client.OzoneKey;
import org.apache.hadoop.ozone.client.OzoneVolume;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedConstruction;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

import javax.security.auth.Subject;

import java.io.IOException;
import java.lang.reflect.Field;
import java.security.PrivilegedExceptionAction;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockConstruction;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * @generated by Cursor
 * @description : Unit Test cases for OzoneClient
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestOzoneClient {
    @Test
    void test01_close_whenHadoopClientCloseThrows_swallowsIOException() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        doThrow(new IOException("close-fail")).when(hdc).close();

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());
            rangerClient.close();

            verify(hdc).close();
        }
    }

    @Test
    void test02_connectionTest_whenVolumesEmpty_returnsFailureMap() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.listVolumes(eq(""))).thenReturn(Collections.emptyIterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            Map<String, Object> out = OzoneClient.connectionTest("svc", minimalConnectionProperties());

            assertEquals(Boolean.FALSE, out.get("connectivityStatus"));
            verify(hdc).close();
        }
    }

    @Test
    void test03_connectionTest_whenVolumesPresent_returnsSuccessMap() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);

        OzoneVolume vol = mock(OzoneVolume.class);
        when(vol.getName()).thenReturn("vol-a");
        List<OzoneVolume> singleVol = Collections.singletonList(vol);
        when(objectStore.listVolumes(eq(""))).thenAnswer(invocation -> singleVol.iterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            Map<String, Object> out = OzoneClient.connectionTest("svc", minimalConnectionProperties());

            assertEquals(Boolean.TRUE, out.get("connectivityStatus"));
            verify(hdc).close();
        }
    }

    @Test
    void test04_connectionTest_whenListVolumesIteratorNull_handlesGracefully() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.listVolumes(eq(""))).thenReturn(null);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            Map<String, Object> out = OzoneClient.connectionTest("svc", minimalConnectionProperties());

            assertEquals(Boolean.FALSE, out.get("connectivityStatus"));
        }
    }

    @Test
    void test05_constructor_skipsEntriesWithNullValues() throws Exception {
        Map<String, String> props = minimalConnectionProperties();
        props.put("ignored.null.value", null);

        org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", props);
            assertNotNull(rangerClient);
            rangerClient.close();
        }
    }

    @Test
    void test06_getBucketList_whenBucketsPresent_returnsNames() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        OzoneBucket                                b1          = mock(OzoneBucket.class);

        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(eq("v1"))).thenReturn(ozoneVolume);

        when(b1.getName()).thenReturn("buck-a");
        List<OzoneBucket> buckets = new ArrayList<>();
        buckets.add(b1);

        when(ozoneVolume.listBuckets(eq("pre"))).thenAnswer(invocation -> buckets.iterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient  rangerClient = new OzoneClient("svc", minimalConnectionProperties());
            List<String> names        = rangerClient.getBucketList("pre", Collections.singletonList("v1"));

            assertEquals(Collections.singletonList("buck-a"), names);
        }
    }

    @Test
    void test07_getBucketList_whenIteratorNull_returnsEmpty() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(eq("v1"))).thenReturn(ozoneVolume);
        when(ozoneVolume.listBuckets(eq("pre"))).thenReturn(null);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getBucketList("pre", Collections.singletonList("v1")).isEmpty());
        }
    }

    @Test
    void test08_getBucketList_whenListVolumesThrowsIOException_returnsEmptyAndLogs() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(anyString())).thenThrow(new IOException("no-volume"));

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getBucketList("bp", Collections.singletonList("v1")).isEmpty());
        }
    }

    @Test
    void test09_getBucketList_whenVolumeListNull_skipsReads() throws Exception {
        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getBucketList("bp", null).isEmpty());
            assertTrue(rangerClient.getBucketList("bp", Collections.emptyList()).isEmpty());

            verify(hdc, never()).getObjectStore();
        }
    }

    @Test
    void test10_getKeyList_whenKeysPresent_returnsNames() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        OzoneBucket                                bucket      = mock(OzoneBucket.class);
        OzoneKey                                   ozoneKey    = mock(OzoneKey.class);

        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(eq("v1"))).thenReturn(ozoneVolume);

        when(bucket.getName()).thenReturn("b-target");
        when(ozoneKey.getName()).thenReturn("key-1");

        when(bucket.listKeys(eq("kp")))
                .thenAnswer(invocation -> Collections.singletonList(ozoneKey).iterator());

        when(ozoneVolume.listBuckets(isNull()))
                .thenAnswer(invocation -> Collections.singletonList(bucket).iterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            List<String> names = rangerClient.getKeyList("kp", Collections.singletonList("v1"), Collections.singletonList("b-target"));

            assertEquals(Collections.singletonList("key-1"), names);
        }
    }

    @Test
    void test11_getKeyList_whenBucketNotListed_skipsKeys() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        OzoneBucket                                other       = mock(OzoneBucket.class);

        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(eq("v1"))).thenReturn(ozoneVolume);
        when(other.getName()).thenReturn("other-bucket");
        when(ozoneVolume.listBuckets(isNull())).thenAnswer(invocation -> Collections.singletonList(other).iterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getKeyList("kp", Collections.singletonList("v1"),
                    Collections.singletonList("wanted-bucket")).isEmpty());

            verify(other, never()).listKeys(anyString());
        }
    }

    @Test
    void test12_getKeyList_whenBucketIteratorNull_returnsEmpty() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(anyString())).thenReturn(ozoneVolume);
        when(ozoneVolume.listBuckets(isNull())).thenReturn(null);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getKeyList("kp", Collections.singletonList("v1"),
                    Collections.singletonList("b")).isEmpty());
        }
    }

    @Test
    void test13_getVolumeList_whenHadoopThrowsIOException_returnsEmpty() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.listVolumes(eq("pfx"))).thenThrow(new IOException("no-list"));

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getVolumeList("pfx").isEmpty());
        }
    }

    @Test
    void test14_getVolumeList_whenInnerClientNull_returnsEmptyAfterClear() throws Exception {
        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);

            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());
            Field       inner        = OzoneClient.class.getDeclaredField("ozoneClient");
            inner.setAccessible(true);
            inner.set(rangerClient, null);

            assertTrue(rangerClient.getVolumeList("pfx").isEmpty());
        }
    }

    @Test
    void test15_getVolumeList_whenVolumesPresent_collectsNames() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                vol         = mock(OzoneVolume.class);
        when(vol.getName()).thenReturn("v-a");
        when(objectStore.listVolumes(eq("vp"))).thenAnswer(invocation -> Collections.singletonList(vol).iterator());
        when(hdc.getObjectStore()).thenReturn(objectStore);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertEquals(Collections.singletonList("v-a"), rangerClient.getVolumeList("vp"));
        }
    }

    @Test
    void test16_getVolumeList_whenVolumeIteratorNull_returnsEmpty() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.listVolumes(eq("pfx"))).thenReturn(null);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getVolumeList("pfx").isEmpty());
        }
    }

    @Test
    void test17_getKeyList_whenBucketListNull_throwsNullPointer() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        OzoneBucket                                bucket      = mock(OzoneBucket.class);

        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(eq("v1"))).thenReturn(ozoneVolume);
        when(bucket.getName()).thenReturn("b-any");
        when(ozoneVolume.listBuckets(isNull())).thenAnswer(invocation -> Collections.singletonList(bucket).iterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertThrows(NullPointerException.class, () -> rangerClient.getKeyList("kp", Collections.singletonList("v1"), null));
        }
    }

    @Test
    void test18_getKeyList_whenKeyIteratorNull_skipsKeys() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                ozoneVolume = mock(OzoneVolume.class);
        OzoneBucket                                bucket      = mock(OzoneBucket.class);

        when(hdc.getObjectStore()).thenReturn(objectStore);
        when(objectStore.getVolume(eq("v1"))).thenReturn(ozoneVolume);
        when(bucket.getName()).thenReturn("b1");
        when(bucket.listKeys(eq("kp"))).thenReturn(null);
        when(ozoneVolume.listBuckets(isNull())).thenAnswer(invocation -> Collections.singletonList(bucket).iterator());

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getKeyList("kp", Collections.singletonList("v1"),
                    Collections.singletonList("b1")).isEmpty());
        }
    }

    @Test
    void test19_getVolumeList_whenMultipleVolumes_appendsAll() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc         = mock(org.apache.hadoop.ozone.client.OzoneClient.class);
        ObjectStore                                objectStore = mock(ObjectStore.class);
        OzoneVolume                                v1          = mock(OzoneVolume.class);
        OzoneVolume                                v2          = mock(OzoneVolume.class);
        when(v1.getName()).thenReturn("va");
        when(v2.getName()).thenReturn("vb");
        List<OzoneVolume> both = Arrays.asList(v1, v2);
        when(objectStore.listVolumes(eq("pref"))).thenAnswer(invocation -> both.iterator());
        when(hdc.getObjectStore()).thenReturn(objectStore);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertEquals(Arrays.asList("va", "vb"), rangerClient.getVolumeList("pref"));
        }
    }

    @Test
    void test20_connectionTest_whenGetVolumeListReturnsNull_reportsDisconnected() throws Exception {
        Map<String, String> cfg = minimalConnectionProperties();

        try (MockedConstruction<OzoneClient> cons = mockConstruction(OzoneClient.class,
                (mock, context) -> when(mock.getVolumeList(eq(""))).thenReturn(null))) {
            Map<String, Object> out = OzoneClient.connectionTest("svc", cfg);

            assertEquals(Boolean.FALSE, out.get("connectivityStatus"));

            assertEquals(1, cons.constructed().size());
            verify(cons.constructed().get(0)).close();
        }
    }

    @Test
    void test21_getBucketList_whenInnerClientNull_returnsEmpty() throws Exception {
        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);

            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());
            Field       inner        = OzoneClient.class.getDeclaredField("ozoneClient");
            inner.setAccessible(true);
            inner.set(rangerClient, null);

            assertTrue(rangerClient.getBucketList("pre", Collections.singletonList("v1")).isEmpty());
        }
    }

    @Test
    void test22_getKeyList_whenInnerClientNull_returnsEmpty() throws Exception {
        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);

            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());
            Field       inner        = OzoneClient.class.getDeclaredField("ozoneClient");
            inner.setAccessible(true);
            inner.set(rangerClient, null);

            assertTrue(rangerClient.getKeyList("kp", Collections.singletonList("v1"),
                    Collections.singletonList("b")).isEmpty());
        }
    }

    @Test
    void test23_getKeyList_whenVolumeListEmpty_skipsStoreAccess() throws Exception {
        org.apache.hadoop.ozone.client.OzoneClient hdc = mock(org.apache.hadoop.ozone.client.OzoneClient.class);

        try (MockedStatic<Subject> subjectStatic = mockStatic(Subject.class);
                MockedStatic<OzoneClientFactory> factoryStatic = mockStatic(OzoneClientFactory.class)) {
            stubSubjectExecutesExceptionAction(subjectStatic);
            stubFactoryReturns(factoryStatic, hdc);

            OzoneClient rangerClient = new OzoneClient("svc", minimalConnectionProperties());

            assertTrue(rangerClient.getKeyList("kp", Collections.emptyList(),
                    Collections.singletonList("b")).isEmpty());

            verify(hdc, never()).getObjectStore();
        }
    }

    private static Map<String, String> minimalConnectionProperties() {
        Map<String, String> cfg = new HashMap<>();
        cfg.put("username", "u");
        cfg.put("password", "p");
        cfg.put("hadoop.security.authentication", "simple");
        cfg.put("ozone.om.service.ids", "ozone1");
        return cfg;
    }

    private static void stubSubjectExecutesExceptionAction(MockedStatic<Subject> subjectStatic) {
        subjectStatic.when(() -> Subject.doAs(any(Subject.class), any(PrivilegedExceptionAction.class)))
                .thenAnswer(invocation -> {
                    PrivilegedExceptionAction<?> pea = invocation.getArgument(1);
                    return pea.run();
                });
    }

    private static void stubFactoryReturns(MockedStatic<OzoneClientFactory> factoryStatic,
            org.apache.hadoop.ozone.client.OzoneClient hadoopClient) {
        factoryStatic.when(() -> OzoneClientFactory.getRpcClient(anyString(), any(ConfigurationSource.class))).thenReturn(hadoopClient);
    }
}
