/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.ranger.common;

import org.apache.ranger.plugin.model.validation.RangerPolicyValidator;
import org.apache.ranger.plugin.model.validation.RangerRoleValidator;
import org.apache.ranger.plugin.model.validation.RangerSecurityZoneValidator;
import org.apache.ranger.plugin.model.validation.RangerServiceDefValidator;
import org.apache.ranger.plugin.model.validation.RangerServiceValidator;
import org.apache.ranger.plugin.store.RoleStore;
import org.apache.ranger.plugin.store.SecurityZoneStore;
import org.apache.ranger.plugin.store.ServiceStore;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerValidatorFactory
 */
@ExtendWith(MockitoExtension.class)
public class TestRangerValidatorFactory {
    private RangerValidatorFactory factory;

    private ServiceStore      mockServiceStore;
    private RoleStore         mockRoleStore;
    private SecurityZoneStore mockSecurityZoneStore;

    @BeforeEach
    public void setUp() {
        factory               = new RangerValidatorFactory();
        mockServiceStore      = mock(ServiceStore.class);
        mockRoleStore         = mock(RoleStore.class);
        mockSecurityZoneStore = mock(SecurityZoneStore.class);
    }

    @Test
    public void testGetServiceValidator() {
        RangerServiceValidator validator = factory.getServiceValidator(mockServiceStore);
        assertNotNull(validator);
    }

    @Test
    public void testGetPolicyValidator() {
        RangerPolicyValidator validator = factory.getPolicyValidator(mockServiceStore);
        assertNotNull(validator);
    }

    @Test
    public void testGetServiceDefValidator() {
        RangerServiceDefValidator validator = factory.getServiceDefValidator(mockServiceStore);
        assertNotNull(validator);
    }

    @Test
    public void testGetSecurityZoneValidator() {
        RangerSecurityZoneValidator validator = factory.getSecurityZoneValidator(mockServiceStore, mockSecurityZoneStore);
        assertNotNull(validator);
    }

    @Test
    public void testGetRangerRoleValidator() {
        RangerRoleValidator validator = factory.getRangerRoleValidator(mockRoleStore);
        assertNotNull(validator);
    }
}
