#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### BEGIN INIT INFO
# Provides:        ranger-admin
# Required-Start:  $local_fs $remote_fs $network $named $syslog $time
# Required-Stop:   $local_fs $remote_fs $network $named $syslog $time
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start/Stop Ranger Admin
### END INIT INFO

LINUX_USER=ranger
BIN_PATH=/usr/bin

case $1 in
start)
	/bin/su --login  $LINUX_USER "${BIN_PATH}/ranger-admin-start"
	;;
stop)
	/bin/su --login  $LINUX_USER "${BIN_PATH}/ranger-admin-stop"
    ;;
restart)
	/bin/su --login  $LINUX_USER "${BIN_PATH}/stop-ranger-admin.sh"  && sleep 30
	/bin/su --login  $LINUX_USER "${BIN_PATH}/start-ranger-admin.sh"

	;;
*)
	echo "Invalid argument [$1]; Only start|stop|restart are supported."
    exit 1
esac
