#
#   Licensed to the Apache Software Foundation (ASF) under one or more
#   contributor license agreements.  See the NOTICE file distributed with
#   this work for additional information regarding copyright ownership.
#   The ASF licenses this file to You under the Apache License, Version 2.0
#   (the "License"); you may not use this file except in compliance with
#   the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# syntax: [prefix].[source|sink].[instance].[options]
# See javadoc of package-info.java for org.apache.hadoop.metrics2 for details

# syntax: [prefix].[source|sink].[instance].[options]
# See javadoc of package-info.java for org.apache.hadoop.metrics2 for details

# default sampling period, in seconds
*.period=30
#*.periodMillis=100

####### File Sink >>>>>> CONF
# prefix=* && context=*
#*.sink.file.class=org.apache.hadoop.metrics2.sink.FileSink
#*.sink.file.filename=${ranger.usersync.log.dir}/${ranger.usersync.metrics.file}-all-metrics.out

# prefix=usersync && context=*
#usersync.sink.file.filename=${ranger.usersync.log.dir}/${ranger.usersync.metrics.file}-metrics.out

# prefix=usersync && context=auth
#usersync.sink.file_auth.class=org.apache.hadoop.metrics2.sink.FileSink
#usersync.sink.file_auth.context=auth
#usersync.sink.file_auth.filename=${ranger.usersync.log.dir}/${ranger.usersync.metrics.file}-auth-metrics.out

## prefix=usersync && context=global
#usersync.sink.file_global.class=org.apache.hadoop.metrics2.sink.FileSink
#usersync.sink.file_global.context=global
#usersync.sink.file_global.filename=${ranger.usersync.log.dir}/${ranger.usersync.metrics.file}-global-metrics.out

## prefix=usersync && context=adls
#usersync.sink.file_adls.class=org.apache.hadoop.metrics2.sink.FileSink
#usersync.sink.file_adls.context=adls
#usersync.sink.file_adls.filename=${ranger.usersync.log.dir}/${ranger.usersync.metrics.file}-adls-metrics.out
####### File Sink <<<<<< CONF

####### Graphite Sink >>>>>> CONF
## prefix=* && context=*
#*.sink.graphite.class=org.apache.hadoop.metrics2.sink.GraphiteSink
#*.sink.graphite.server_host=127.0.0.1
#*.sink.graphite.server_port=2003
#*.sink.graphite.metrics_prefix=usersync

## prefix=usersync && context=auth
#usersync.sink.graphite_usersynccntx.class=org.apache.hadoop.metrics2.sink.GraphiteSink
#usersync.sink.graphite_usersynccntx.server_host=127.0.0.1
#usersync.sink.graphite_usersynccntx.server_port=2003
#usersync.sink.graphite_usersynccntx.metrics_prefix=usersync
#usersync.sink.graphite_usersynccntx.context=auth
####### Graphite Sink <<<<<< CONF
