/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ranger.patch;

import org.apache.ranger.biz.ServiceDBStore;
import org.apache.ranger.common.JSONUtil;
import org.apache.ranger.common.RangerValidatorFactory;
import org.apache.ranger.common.StringUtil;
import org.apache.ranger.db.RangerDaoManager;
import org.apache.ranger.db.XXServiceDefDao;
import org.apache.ranger.entity.XXServiceDef;
import org.apache.ranger.plugin.model.RangerServiceDef;
import org.apache.ranger.plugin.model.validation.RangerServiceDefValidator;
import org.apache.ranger.plugin.store.EmbeddedServiceDefsUtil;
import org.apache.ranger.service.RangerPolicyService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @generated by Cursor
 * @description <Unit Test for PatchForHiveServiceDefUpdate_J10009 class>
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestPatchForHiveServiceDefUpdate_J10009 {
    @Test
    public void testExecLoadAndPrintStats() {
        try (MockedStatic<EmbeddedServiceDefsUtil> utilMock = Mockito.mockStatic(EmbeddedServiceDefsUtil.class)) {
            EmbeddedServiceDefsUtil util = Mockito.mock(EmbeddedServiceDefsUtil.class);
            utilMock.when(EmbeddedServiceDefsUtil::instance).thenReturn(util);

            PatchForHiveServiceDefUpdate_J10009 patch = new PatchForHiveServiceDefUpdate_J10009();
            patch.daoMgr = Mockito.mock(RangerDaoManager.class);
            patch.svcDBStore = Mockito.mock(ServiceDBStore.class);
            patch.jsonUtil = new JSONUtil();
            patch.policyService = Mockito.mock(RangerPolicyService.class);
            patch.stringUtil = new StringUtil();
            patch.validatorFactory = Mockito.mock(RangerValidatorFactory.class);
            patch.svcStore = patch.svcDBStore;

            patch.execLoad();
            patch.printStats();
        }
    }

    @Test
    public void testJsonStringToMap_fallbackParsesPairs() throws Exception {
        PatchForHiveServiceDefUpdate_J10009 patch = new PatchForHiveServiceDefUpdate_J10009();
        Method m = PatchForHiveServiceDefUpdate_J10009.class.getDeclaredMethod("jsonStringToMap", String.class);
        m.setAccessible(true);
        @SuppressWarnings("unchecked")
        HashMap<String, String> res = (HashMap<String, String>) m.invoke(patch, "x=1;y=2");
        Assertions.assertEquals("1", res.get("x"));
        Assertions.assertEquals("2", res.get("y"));

        Object res2 = m.invoke(patch, new Object[] {null});
        Assertions.assertNull(res2);
    }

    @Test
    public void testMapToJsonString_handlesNullAndException() throws Exception {
        PatchForHiveServiceDefUpdate_J10009 patch = new PatchForHiveServiceDefUpdate_J10009();
        Method m = PatchForHiveServiceDefUpdate_J10009.class.getDeclaredMethod("mapToJsonString", Map.class);
        m.setAccessible(true);
        Object resNull = m.invoke(patch, new Object[] {null});
        Assertions.assertNull(resNull);

        PatchForHiveServiceDefUpdate_J10009 patch2 = new PatchForHiveServiceDefUpdate_J10009();
        JSONUtil jsonUtil = Mockito.mock(JSONUtil.class);
        Mockito.when(jsonUtil.readMapToString(Mockito.anyMap())).thenThrow(new RuntimeException("bad"));
        patch2.jsonUtil = jsonUtil;
        Object resExc = m.invoke(patch2, new HashMap<String, String>());
        Assertions.assertNull(resExc);
    }

    @Test
    public void testCheckHiveAccessType_trueAndFalse() throws Exception {
        PatchForHiveServiceDefUpdate_J10009 patch = new PatchForHiveServiceDefUpdate_J10009();
        Method m = PatchForHiveServiceDefUpdate_J10009.class.getDeclaredMethod("checkHiveAccessType", List.class);
        m.setAccessible(true);

        List<RangerServiceDef.RangerAccessTypeDef> list = new ArrayList<>();
        RangerServiceDef.RangerAccessTypeDef def = new RangerServiceDef.RangerAccessTypeDef();
        def.setName("select");
        list.add(def);
        Assertions.assertFalse((boolean) m.invoke(patch, list));

        RangerServiceDef.RangerAccessTypeDef repl = new RangerServiceDef.RangerAccessTypeDef();
        repl.setName("repladmin");
        list.add(repl);
        Assertions.assertTrue((boolean) m.invoke(patch, list));
    }

    @Test
    public void testUpdateHiveServiceDef_fullFlow_andOptionsRestore_andFailurePath() throws Exception {
        try (MockedStatic<EmbeddedServiceDefsUtil> utilMock = Mockito.mockStatic(EmbeddedServiceDefsUtil.class)) {
            EmbeddedServiceDefsUtil util = Mockito.mock(EmbeddedServiceDefsUtil.class);
            utilMock.when(EmbeddedServiceDefsUtil::instance).thenReturn(util);
            RangerServiceDef embedded = new RangerServiceDef();
            List<RangerServiceDef.RangerAccessTypeDef> access = new ArrayList<>();
            RangerServiceDef.RangerAccessTypeDef repl = new RangerServiceDef.RangerAccessTypeDef();
            repl.setName("repladmin");
            access.add(repl);
            embedded.setAccessTypes(access);
            Mockito.when(util.getEmbeddedServiceDef(Mockito.anyString())).thenReturn(embedded);

            PatchForHiveServiceDefUpdate_J10009 patch = new PatchForHiveServiceDefUpdate_J10009();
            RangerDaoManager daoMgr = Mockito.mock(RangerDaoManager.class);
            XXServiceDefDao sdefDao = Mockito.mock(XXServiceDefDao.class);
            Mockito.when(daoMgr.getXXServiceDef()).thenReturn(sdefDao);
            XXServiceDef xx = new XXServiceDef();
            xx.setDefOptions(null);
            Mockito.when(sdefDao.findByName(Mockito.anyString())).thenReturn(xx);

            ServiceDBStore svcDB = Mockito.mock(ServiceDBStore.class);
            patch.daoMgr = daoMgr;
            patch.svcDBStore = svcDB;
            patch.svcStore = svcDB;
            patch.jsonUtil = new JSONUtil();
            RangerValidatorFactory vf = Mockito.mock(RangerValidatorFactory.class);
            RangerServiceDefValidator validator = Mockito.mock(RangerServiceDefValidator.class);
            Mockito.when(vf.getServiceDefValidator(Mockito.any())).thenReturn(validator);
            patch.validatorFactory = vf;

            RangerServiceDef dbDef = new RangerServiceDef();
            dbDef.setAccessTypes(new ArrayList<>());
            Mockito.when(svcDB.getServiceDefByName(Mockito.anyString())).thenReturn(dbDef);
            Mockito.when(svcDB.updateServiceDef(Mockito.any())).thenReturn(dbDef);

            XXServiceDef xxAfter = new XXServiceDef();
            HashMap<String, String> postOptions = new HashMap<>();
            postOptions.put(RangerServiceDef.OPTION_ENABLE_DENY_AND_EXCEPTIONS_IN_POLICIES, "true");
            String postStr = new JSONUtil().readMapToString(postOptions);
            xxAfter.setDefOptions(postStr);
            Mockito.when(sdefDao.findByName(Mockito.anyString())).thenReturn(xx, xxAfter);

            Method m = PatchForHiveServiceDefUpdate_J10009.class.getDeclaredMethod("updateHiveServiceDef");
            m.setAccessible(true);
            Assertions.assertDoesNotThrow(() -> {
                try {
                    m.invoke(patch);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            });
            Mockito.verify(sdefDao, Mockito.times(1)).update(Mockito.any(XXServiceDef.class));

            Mockito.when(svcDB.updateServiceDef(Mockito.any())).thenReturn(null);
            Assertions.assertDoesNotThrow(() -> {
                try {
                    m.invoke(patch);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            });
        }
    }
}
