/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ranger.patch;

import org.apache.ranger.biz.ServiceDBStore;
import org.apache.ranger.common.JSONUtil;
import org.apache.ranger.common.RangerValidatorFactory;
import org.apache.ranger.common.StringUtil;
import org.apache.ranger.db.RangerDaoManager;
import org.apache.ranger.db.XXServiceDefDao;
import org.apache.ranger.entity.XXServiceDef;
import org.apache.ranger.plugin.model.RangerServiceDef;
import org.apache.ranger.plugin.model.RangerServiceDef.RangerAccessTypeDef;
import org.apache.ranger.plugin.model.RangerServiceDef.RangerResourceDef;
import org.apache.ranger.plugin.model.validation.RangerServiceDefValidator;
import org.apache.ranger.plugin.store.EmbeddedServiceDefsUtil;
import org.apache.ranger.service.RangerPolicyService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.MockedStatic;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @generated by Cursor
 * @description <Unit Test for PatchForHiveServiceDefUpdate_J10017 class>
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestPatchForHiveServiceDefUpdate_J10017 {
    private static void setIfPresent(Object target, String fieldName, Object value) {
        try {
            Field f = target.getClass().getDeclaredField(fieldName);
            f.setAccessible(true);
            f.set(target, value);
        } catch (NoSuchFieldException ignored) {
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Test
    public void testExecLoad_noEmbeddedOrNoDao_noThrow() throws Exception {
        try (MockedStatic<EmbeddedServiceDefsUtil> utilMock = Mockito.mockStatic(EmbeddedServiceDefsUtil.class)) {
            EmbeddedServiceDefsUtil util = Mockito.mock(EmbeddedServiceDefsUtil.class);
            utilMock.when(EmbeddedServiceDefsUtil::instance).thenReturn(util);
            Mockito.when(util.getEmbeddedServiceDef(Mockito.anyString())).thenReturn(null);

            PatchForHiveServiceDefUpdate_J10017 patch = new PatchForHiveServiceDefUpdate_J10017();
            patch.daoMgr = Mockito.mock(RangerDaoManager.class);
            patch.svcDBStore = Mockito.mock(ServiceDBStore.class);
            patch.jsonUtil = new JSONUtil();
            patch.policyService = Mockito.mock(RangerPolicyService.class);
            patch.stringUtil = new StringUtil();
            patch.validatorFactory = Mockito.mock(RangerValidatorFactory.class);
            patch.svcStore = patch.svcDBStore;

            patch.execLoad();
            patch.printStats();
        }
    }

    @Test
    public void testUpdateHiveServiceDef_paths_andOptionRestore() throws Exception {
        try (MockedStatic<EmbeddedServiceDefsUtil> utilMock = Mockito.mockStatic(EmbeddedServiceDefsUtil.class)) {
            EmbeddedServiceDefsUtil util = Mockito.mock(EmbeddedServiceDefsUtil.class);
            utilMock.when(EmbeddedServiceDefsUtil::instance).thenReturn(util);

            PatchForHiveServiceDefUpdate_J10017 patch = new PatchForHiveServiceDefUpdate_J10017();
            RangerDaoManager daoMgr = Mockito.mock(RangerDaoManager.class);
            XXServiceDefDao sdefDao = Mockito.mock(XXServiceDefDao.class);
            Mockito.when(daoMgr.getXXServiceDef()).thenReturn(sdefDao);
            setIfPresent(patch, "daoMgr", daoMgr);

            ServiceDBStore svcStore = Mockito.mock(ServiceDBStore.class);
            setIfPresent(patch, "svcDBStore", svcStore);
            setIfPresent(patch, "jsonUtil", new JSONUtil());
            setIfPresent(patch, "policyService", Mockito.mock(RangerPolicyService.class));
            setIfPresent(patch, "stringUtil", new StringUtil());
            setIfPresent(patch, "svcStore", svcStore);

            // Embedded service def exists
            RangerServiceDef embedded = new RangerServiceDef();
            List<RangerResourceDef> resDefs = new ArrayList<>();
            RangerResourceDef global = new RangerResourceDef();
            global.setName("global");
            resDefs.add(global);
            embedded.setResources(resDefs);
            embedded.setAccessTypes(new ArrayList<RangerAccessTypeDef>());
            utilMock.when(() -> EmbeddedServiceDefsUtil.instance().getEmbeddedServiceDef(Mockito.anyString()))
                    .thenReturn(embedded);

            // DAO service-def missing -> method returns (log path)
            Mockito.when(sdefDao.findByName(Mockito.anyString())).thenReturn(null);
            patch.execLoad();

            // Set present DAO service-def and DB service-def
            XXServiceDef xx = new XXServiceDef();
            Map<String, String> pre = new HashMap<>();
            pre.put(RangerServiceDef.OPTION_ENABLE_DENY_AND_EXCEPTIONS_IN_POLICIES, "on");
            xx.setDefOptions(new JSONUtil().readMapToString(pre));
            Mockito.when(sdefDao.findByName(Mockito.anyString())).thenReturn(xx);

            RangerServiceDef db = new RangerServiceDef();
            db.setResources(new ArrayList<RangerResourceDef>());
            db.setAccessTypes(new ArrayList<RangerAccessTypeDef>());
            Mockito.when(svcStore.getServiceDefByName(Mockito.anyString())).thenReturn(db);

            RangerServiceDefValidator validator = Mockito.mock(RangerServiceDefValidator.class);
            RangerValidatorFactory vf = Mockito.mock(RangerValidatorFactory.class);
            Mockito.when(vf.getServiceDefValidator(Mockito.any())).thenReturn(validator);
            setIfPresent(patch, "validatorFactory", vf);

            Mockito.when(svcStore.updateServiceDef(Mockito.any())).thenReturn(db);

            // After update, ensure options are restored if changed
            XXServiceDef xxAfter = new XXServiceDef();
            Map<String, String> post = new HashMap<>();
            post.put(RangerServiceDef.OPTION_ENABLE_DENY_AND_EXCEPTIONS_IN_POLICIES, "off");
            xxAfter.setDefOptions(new JSONUtil().readMapToString(post));
            Mockito.when(sdefDao.findByName(Mockito.anyString())).thenReturn(xx, xxAfter);

            patch.execLoad();
            Mockito.verify(svcStore, Mockito.atLeastOnce()).updateServiceDef(Mockito.any());
        }
    }

    @Test
    public void testUpdateServiceDef_trueAndFalse() throws Exception {
        PatchForHiveServiceDefUpdate_J10017 patch = new PatchForHiveServiceDefUpdate_J10017();
        RangerValidatorFactory vf = Mockito.mock(RangerValidatorFactory.class);
        RangerServiceDefValidator validator = Mockito.mock(RangerServiceDefValidator.class);
        Mockito.when(vf.getServiceDefValidator(Mockito.any())).thenReturn(validator);
        setIfPresent(patch, "validatorFactory", vf);
        ServiceDBStore svcStore = Mockito.mock(ServiceDBStore.class);
        Mockito.when(svcStore.updateServiceDef(Mockito.any())).thenReturn(new RangerServiceDef());
        setIfPresent(patch, "svcStore", svcStore);

        Method m = PatchForHiveServiceDefUpdate_J10017.class.getDeclaredMethod("updateServiceDef",
                RangerServiceDef.class, RangerServiceDef.class);
        m.setAccessible(true);

        RangerServiceDef serviceDef = new RangerServiceDef();
        serviceDef.setAccessTypes(new ArrayList<RangerAccessTypeDef>());
        RangerServiceDef embedded = new RangerServiceDef();
        embedded.setAccessTypes(new ArrayList<RangerAccessTypeDef>());
        embedded.setResources(new ArrayList<RangerResourceDef>());

        // no global resource -> false
        Assertions.assertFalse((boolean) m.invoke(patch, serviceDef, embedded));

        // with global resource -> true
        RangerResourceDef global = new RangerResourceDef();
        global.setName("global");
        List<RangerResourceDef> resDefs = new ArrayList<>();
        resDefs.add(global);
        embedded.setResources(resDefs);
        Assertions.assertTrue((boolean) m.invoke(patch, serviceDef, embedded));
    }

    @Test
    public void testCheckHiveGlobalresourcePresent_trueAndFalse() throws Exception {
        PatchForHiveServiceDefUpdate_J10017 patch = new PatchForHiveServiceDefUpdate_J10017();
        Method m = PatchForHiveServiceDefUpdate_J10017.class
                .getDeclaredMethod("checkHiveGlobalresourcePresent", List.class);
        m.setAccessible(true);
        List<RangerResourceDef> defs = new ArrayList<>();
        RangerResourceDef d = new RangerResourceDef();
        d.setName("db");
        defs.add(d);
        Assertions.assertFalse((boolean) m.invoke(patch, defs));
        d.setName("global");
        Assertions.assertTrue((boolean) m.invoke(patch, defs));
    }
}
