/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.ha;

import org.apache.hadoop.conf.Configuration;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * @generated by Cursor
 * @description : Unit Test cases for RangerServiceServerIdSelector
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestRangerServiceServerIdSelector {
    @Test
    void testSelectServerId_negative_throwsWhenNoLocalBindingMatches() {
        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.ids", "only");
        configuration.set("svc.server.ha.address.only", "10.255.255.1:65000");
        configuration.set("svc.service.http.port", "65000");

        Assertions.assertThrows(Exception.class, () -> RangerServiceServerIdSelector.selectServerId(configuration));
    }

    @Test
    void testSelectServerId_positive_resolvesMatchingLocalId() throws Exception {
        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.ids", "local-id");
        configuration.set("svc.server.ha.address.local-id", "127.0.0.1:28080");
        configuration.set("svc.service.http.port", "28080");

        String serverId = RangerServiceServerIdSelector.selectServerId(configuration);

        Assertions.assertEquals("local-id", serverId);
    }
}
