/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.ha;

import org.apache.curator.framework.CuratorFramework;
import org.apache.curator.framework.CuratorFrameworkFactory;
import org.apache.curator.framework.recipes.leader.LeaderLatch;
import org.apache.curator.framework.recipes.locks.InterProcessMutex;
import org.apache.hadoop.conf.Configuration;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentMatchers;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

/**
 * @generated by Cursor
 * @description : Unit Test cases for CuratorFactory
 */
@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
class TestCuratorFactory {
    @Test
    void testClientInstance_negative_returnsNullWhenHaDisabled() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);

        Assertions.assertNull(factory.clientInstance());
    }

    @Test
    void testClientInstance_positive_returnsInjectedClient() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        CuratorFramework mockClient = Mockito.mock(CuratorFramework.class);

        injectCuratorFramework(factory, mockClient);

        Assertions.assertSame(mockClient, factory.clientInstance());
    }

    @Test
    void testClose_negative_noOpWhenFrameworkNull() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);

        Assertions.assertDoesNotThrow(factory::close);
    }

    @Test
    void testClose_positive_invokesCloseOnFramework() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        CuratorFramework mockClient = Mockito.mock(CuratorFramework.class);

        injectCuratorFramework(factory, mockClient);

        factory.close();

        Mockito.verify(mockClient).close();
    }

    @Test
    void testGetInstance_negative_returnsNullWhenConstructionFails() throws Exception {
        resetCuratorFactorySingleton();

        Configuration bad = Mockito.mock(Configuration.class);

        Mockito.when(bad.get(ArgumentMatchers.anyString(), ArgumentMatchers.anyString()))
                .thenThrow(new RuntimeException("boom"));

        Assertions.assertNull(CuratorFactory.getInstance(bad));
    }

    @Test
    void testGetInstance_positive_sameSingletonForHaDisabled() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory first  = CuratorFactory.getInstance(configuration);
        CuratorFactory second = CuratorFactory.getInstance(configuration);

        Assertions.assertSame(first, second);
    }

    @Test
    void testLeaderLatchInstance_negative_throwsWhenClientNull() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);

        Assertions.assertThrows(Exception.class, () -> factory.leaderLatchInstance("id", "/root"));
    }

    @Test
    void testLeaderLatchInstance_positive_buildsLatchWithInjectedClient() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        CuratorFramework mockClient = Mockito.mock(CuratorFramework.class);

        injectCuratorFramework(factory, mockClient);

        LeaderLatch latch = factory.leaderLatchInstance("sid", "/zk");

        Assertions.assertNotNull(latch);
    }

    @Test
    void testLockInstance_negative_throwsWhenClientNull() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);

        Assertions.assertThrows(Exception.class, () -> factory.lockInstance("/zk"));
    }

    @Test
    void testLockInstance_positive_buildsMutexWithInjectedClient() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        CuratorFramework mockClient = Mockito.mock(CuratorFramework.class);

        injectCuratorFramework(factory, mockClient);

        InterProcessMutex mutex = factory.lockInstance("/zk");

        Assertions.assertNotNull(mutex);
    }

    @Test
    void testEnhanceBuilderWithSecurityParameters_negative_skipsAclWhenNotConfigured() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, null, null);
        CuratorFrameworkFactory.Builder builder = Mockito.mock(CuratorFrameworkFactory.Builder.class);

        factory.enhanceBuilderWithSecurityParameters(props, builder);

        Mockito.verify(builder, Mockito.never()).aclProvider(ArgumentMatchers.any());
    }

    @Test
    void testEnhanceBuilderWithSecurityParameters_positive_appliesAclAndAuth() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, "world:anyone", "digest:user:secret");
        CuratorFrameworkFactory.Builder builder = Mockito.mock(CuratorFrameworkFactory.Builder.class);

        Mockito.when(builder.aclProvider(ArgumentMatchers.any())).thenReturn(builder);
        Mockito.when(builder.authorization(ArgumentMatchers.anyString(), ArgumentMatchers.any())).thenReturn(builder);

        factory.enhanceBuilderWithSecurityParameters(props, builder);

        Mockito.verify(builder).aclProvider(ArgumentMatchers.any());
        Mockito.verify(builder).authorization(ArgumentMatchers.eq("digest"), ArgumentMatchers.any());
    }

    @Test
    void testEnhanceBuilderWithSecurityParameters_aclOnly_skipsAuthorization() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, "world:anyone", null);
        CuratorFrameworkFactory.Builder builder = Mockito.mock(CuratorFrameworkFactory.Builder.class);

        Mockito.when(builder.aclProvider(ArgumentMatchers.any())).thenReturn(builder);

        factory.enhanceBuilderWithSecurityParameters(props, builder);

        Mockito.verify(builder).aclProvider(ArgumentMatchers.any());
        Mockito.verify(builder, Mockito.never()).authorization(ArgumentMatchers.anyString(), ArgumentMatchers.any());
    }

    @Test
    void testEnhanceBuilderWithSecurityParameters_saslAcl_exercisesAclLoggingBranch() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, "sasl:principal", null);
        CuratorFrameworkFactory.Builder builder = Mockito.mock(CuratorFrameworkFactory.Builder.class);

        Mockito.when(builder.aclProvider(ArgumentMatchers.any())).thenReturn(builder);

        factory.enhanceBuilderWithSecurityParameters(props, builder);

        Mockito.verify(builder).aclProvider(ArgumentMatchers.any());
    }

    @Test
    void testEnhanceBuilderWithSecurityParameters_unknownAclScheme_exercisesDefaultIdLogging() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        CuratorFactory factory = CuratorFactory.getInstance(configuration);
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, "custom:marker", null);
        CuratorFrameworkFactory.Builder builder = Mockito.mock(CuratorFrameworkFactory.Builder.class);

        Mockito.when(builder.aclProvider(ArgumentMatchers.any())).thenReturn(builder);

        factory.enhanceBuilderWithSecurityParameters(props, builder);

        Mockito.verify(builder).aclProvider(ArgumentMatchers.any());
    }

    @Test
    void testGetAclProvider_viaReflection_returnsNullWhenNoAcl() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, null, null);

        Object provider = invokePrivate(factory, "getAclProvider", new Class[] {HAConfiguration.ZookeeperProperties.class}, props);

        Assertions.assertNull(provider);
    }

    @Test
    void testGetAclProvider_viaReflection_returnsProviderForIpAcl() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("c", "/z", 1, 2, 3, "ip:10.0.0.1", null);

        Object provider = invokePrivate(factory, "getAclProvider", new Class[] {HAConfiguration.ZookeeperProperties.class}, props);

        Assertions.assertNotNull(provider);
    }

    @Test
    void testGetBuilder_viaReflection_returnsNonNullBuilder() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();
        HAConfiguration.ZookeeperProperties props = new HAConfiguration.ZookeeperProperties("localhost:2181", "/zk", 500, 2, 10000, null, null);

        Object builder = invokePrivate(factory, "getBuilder", new Class[] {HAConfiguration.ZookeeperProperties.class}, props);

        Assertions.assertNotNull(builder);
        Assertions.assertTrue(builder instanceof CuratorFrameworkFactory.Builder);
    }

    @Test
    void testGetCurrentUser_viaReflection_returnsNonNullString() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object user = invokePrivate(factory, "getCurrentUser", new Class[0]);

        Assertions.assertNotNull(user);
        Assertions.assertTrue(user instanceof String);
    }

    @Test
    void testGetIdForLogging_viaReflection_authSchemeUsesFirstSegment() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object id = invokePrivate(factory, "getIdForLogging", new Class[] {String.class, String.class}, CuratorFactory.AUTH_SCHEME, "user:extra");

        Assertions.assertEquals("user", id);
    }

    @Test
    void testGetIdForLogging_viaReflection_digestUsesFirstSegment() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object id = invokePrivate(factory, "getIdForLogging", new Class[] {String.class, String.class}, CuratorFactory.DIGEST_SCHEME, "user:hash:suffix");

        Assertions.assertEquals("user", id);
    }

    @Test
    void testGetIdForLogging_viaReflection_saslReturnsRawId() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object id = invokePrivate(factory, "getIdForLogging", new Class[] {String.class, String.class}, CuratorFactory.SASL_SCHEME, "principal");

        Assertions.assertEquals("principal", id);
    }

    @Test
    void testGetIdForLogging_viaReflection_ipReturnsRawId() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object id = invokePrivate(factory, "getIdForLogging", new Class[] {String.class, String.class}, CuratorFactory.IP_SCHEME, "192.168.0.1");

        Assertions.assertEquals("192.168.0.1", id);
    }

    @Test
    void testGetIdForLogging_viaReflection_unknownScheme() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object id = invokePrivate(factory, "getIdForLogging", new Class[] {String.class, String.class}, "other", "x");

        Assertions.assertEquals("unknown", id);
    }

    @Test
    void testGetIdForLogging_viaReflection_worldMapsToAnyoneConstant() throws Exception {
        CuratorFactory factory = curatorFactoryForEnhanceTests();

        Object id = invokePrivate(factory, "getIdForLogging", new Class[] {String.class, String.class}, CuratorFactory.WORLD_SCHEME, "ignored");

        Assertions.assertEquals(CuratorFactory.ANYONE_ID, id);
    }

    private static CuratorFactory curatorFactoryForEnhanceTests() throws Exception {
        resetCuratorFactorySingleton();

        Configuration configuration = new Configuration(false);

        configuration.set("ranger.service.name", "svc");
        configuration.set("svc.server.ha.enabled", "false");

        return CuratorFactory.getInstance(configuration);
    }

    private static Object invokePrivate(CuratorFactory target, String methodName, Class<?>[] paramTypes, Object... args) throws Exception {
        Method method = CuratorFactory.class.getDeclaredMethod(methodName, paramTypes);

        method.setAccessible(true);

        return method.invoke(target, args);
    }

    private static void injectCuratorFramework(CuratorFactory factory, CuratorFramework client) throws Exception {
        Field field = CuratorFactory.class.getDeclaredField("curatorFramework");

        field.setAccessible(true);
        field.set(factory, client);
    }

    private static void resetCuratorFactorySingleton() throws Exception {
        Field field = CuratorFactory.class.getDeclaredField("instance");

        field.setAccessible(true);
        field.set(null, null);
    }
}
