/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.ranger.ugsyncutil.transform;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

/**
 * @generated by Cursor
 * @description : Unit Test cases for Mapper
 */

@ExtendWith(MockitoExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class TestMapper {
    @Test
    public void test01_InterfaceInitAndTransform() {
        UpperCaseMapper mapper = new UpperCaseMapper();
        mapper.init("base", null, "/");
        Assertions.assertEquals("ABC", mapper.transform("abc"));
        Assertions.assertNull(mapper.transform(null));
    }

    public static class UpperCaseMapper implements Mapper {
        @Override
        public void init(String baseProperty, List<String> regexPatterns, String regexSeparator) {
            // no-op for this simple implementation
        }

        @Override
        public String transform(String attrValue) {
            return attrValue == null ? null : attrValue.toUpperCase();
        }
    }
}
