name: Git Secrets Scanner

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.6.1
        with:
          path: ./
          base: ${{ github.base_ref }}
          head: HEAD
